Include "language/arith.bb"
Include "language/array.bb"
Include "language/assignment.bb"
Include "language/comparisons.bb"
Include "language/const.bb"
Include "language/data.bb"
Include "language/function.bb"
Include "language/global.bb"
Include "language/if.bb"
Include "language/select.bb"
Include "language/types.bb"
Include "language/vector.bb"

Include "modules/math.bb"
