#!/bin/sh

# run the proper suite
bin/blitz3d run -r test test/all.bb
RESULT=$?
if [ $RESULT -ne 0 ]; then
  echo "Test suite failed. Fix it and then run the coverage generation again."
  exit 1
fi

BLITZCC=_release/bin/blitzcc

# test a few of the compiler flags
$BLITZCC -v
$BLITZCC +k
$BLITZCC -k
$BLITZCC -l
$BLITZCC -h

$BLITZCC -r test -a test/all.bb
$BLITZCC -r test -c test/all.bb
$BLITZCC -r test -j test/all.bb

# test for syntax errors
$BLITZCC -r test -j test/syntax-errors/arithmetic-on-type.bb
$BLITZCC -r test -j test/syntax-errors/division-by-zero.bb

# invalid runtime
$BLITZCC -r d3d1 test/all.bb

# generate the report...
echo "Generating coverage report..."
cd build && mkdir -p ../.coverage && gcovr -e '.*stdin.*' -r .. --html --html-details -o ../.coverage/coverage.html
