##
# A basic Debian "buster" build environment

FROM debian:10

RUN apt-get update && apt-get install -y build-essential ninja-build git libxml2-dev zlib1g-dev autoconf libtool gettext autopoint gperf cmake clang libwxgtk3.0-gtk3-dev libxrandr-dev libxinerama-dev libxcursor-dev uuid-dev libfontconfig1-dev
