##
# A basic Debian "bullseye" build environment

FROM debian:11

RUN apt-get update && apt-get install -y build-essential ninja-build git libxml2-dev zlib1g-dev autoconf libtool gettext autopoint gperf cmake clang libgtk-3-dev libpcre2-dev libxrandr-dev libxinerama-dev libxcursor-dev uuid-dev libfontconfig1-dev
