#ifndef BB_BANK_COMMANDS_H
#define BB_BANK_COMMANDS_H

#include <bb/blitz/module.h>
#include <bb/bank/bank.h>

#ifdef __cplusplus
extern "C" {
#endif

// AUTOGENERATED. DO NOT EDIT.
// RUN `make` TO UPDATE.
bbBank * BBCALL bbCreateBank( bb_int_t size );
void BBCALL bbFreeBank( bbBank *bank );
bb_int_t BBCALL bbBankSize( bbBank *bank );
void BBCALL bbResizeBank( bbBank *bank,bb_int_t size );
void BBCALL bbCopyBank( bbBank *src_bank,bb_int_t src_offset,bbBank *dest_bank,bb_int_t dest_offset,bb_int_t count );
bb_int_t BBCALL bbPeekByte( bbBank *bank,bb_int_t offset );
bb_int_t BBCALL bbPeekShort( bbBank *bank,bb_int_t offset );
bb_int_t BBCALL bbPeekInt( bbBank *bank,bb_int_t offset );
bb_float_t BBCALL bbPeekFloat( bbBank *bank,bb_int_t offset );
void BBCALL bbPokeByte( bbBank *bank,bb_int_t offset,bb_int_t value );
void BBCALL bbPokeShort( bbBank *bank,bb_int_t offset,bb_int_t value );
void BBCALL bbPokeInt( bbBank *bank,bb_int_t offset,bb_int_t value );
void BBCALL bbPokeFloat( bbBank *bank,bb_int_t offset,bb_float_t value );
bb_int_t BBCALL bbReadBytes( bbBank *bank,BBStream *file,bb_int_t offset,bb_int_t count );
bb_int_t BBCALL bbWriteBytes( bbBank *bank,BBStream *file,bb_int_t offset,bb_int_t count );

#ifdef __cplusplus
}
#endif


#endif
