// AUTOGENERATED. DO NOT EDIT.
// RUN `bin/blitz3d config` TO UPDATE.

#include <bb/blitz/module.h>
#include <bb/bank/bank.h>

#ifdef WIN32
BBMODULE_LINK( bank ){
	rtSym( "%BankSize%bank",bbBankSize );
	rtSym( "CopyBank%src_bank%src_offset%dest_bank%dest_offset%count",bbCopyBank );
	rtSym( "%CreateBank%size=0",bbCreateBank );
	rtSym( "FreeBank%bank",bbFreeBank );
	rtSym( "%PeekByte%bank%offset",bbPeekByte );
	rtSym( "#PeekFloat%bank%offset",bbPeekFloat );
	rtSym( "%PeekInt%bank%offset",bbPeekInt );
	rtSym( "%PeekShort%bank%offset",bbPeekShort );
	rtSym( "PokeByte%bank%offset%value",bbPokeByte );
	rtSym( "PokeFloat%bank%offset#value",bbPokeFloat );
	rtSym( "PokeInt%bank%offset%value",bbPokeInt );
	rtSym( "PokeShort%bank%offset%value",bbPokeShort );
	rtSym( "%ReadBytes%bank%file%offset%count",bbReadBytes );
	rtSym( "ResizeBank%bank%size",bbResizeBank );
	rtSym( "%WriteBytes%bank%file%offset%count",bbWriteBytes );
}
#endif
