#ifndef BB_STUB_STUB_H
#define BB_STUB_STUB_H

#include <bb/blitz/blitz.h>
#include "../../gxruntime/gxruntime.h"

// dynamically generated by the premake script
bool bbruntime_create();
void bbruntime_link( void (*link)( const char *sym,void *pc ) );
bool bbruntime_destroy();

const char *bbruntime_run( gxRuntime *runtime,void (*pc)(),bool debug );
void bbruntime_panic( const char *err );

//start up error
void sue( const char *t );

#endif
