#ifndef BB_STUB_STUB_H
#define BB_STUB_STUB_H

#include <bb/blitz/blitz.h>

// dynamically generated by the premake script
bool bbruntime_create();
void bbruntime_link( void (*link)( const char *sym,void *pc ) );
bool bbruntime_destroy();

#ifdef WIN32
#include "../../gxruntime/gxruntime.h"
const char *bbruntime_run( gxRuntime *runtime,void (*pc)(),bool debug );
void bbruntime_panic( const char *err );
#endif

//start up error
void sue( const char *t );

#endif
