source 'https://rubygems.org'

gem 'github-markup', require: 'github/markup'
gem 'commonmarker'
gem 'htmlbeautifier'
gem 'activesupport', '=4.2.8', require: 'active_support/core_ext/string'
gem 'colored'
gem 'nokogiri'
gem 'filewatcher'
gem 'os'
