#ifndef BB_TILTFIVE_COMMANDS_H
#define BB_TILTFIVE_COMMANDS_H

#include <bb/blitz/module.h>
#include <bb/tiltfive/tiltfive.h>

#ifdef __cplusplus
extern "C" {
#endif

// AUTOGENERATED. DO NOT EDIT.
// RUN `make` TO UPDATE.
void BBCALL bbT5_RunSample(  );

#ifdef __cplusplus
}
#endif


#endif
