// AUTOGENERATED. DO NOT EDIT.
// RUN `make` TO UPDATE.

#include <bb/blitz/module.h>
#include <bb/tiltfive/tiltfive.h>

BBMODULE_LINK( tiltfive ){
	rtSym( "%T5_Initialize","bbT5_Initialize",bbT5_Initialize );
	rtSym( "#T5_GameboardX","bbT5_GameboardX",bbT5_GameboardX );
	rtSym( "#T5_GameboardY","bbT5_GameboardY",bbT5_GameboardY );
	rtSym( "#T5_GameboardZ","bbT5_GameboardZ",bbT5_GameboardZ );
	rtSym( "#T5_GameboardWidth","bbT5_GameboardWidth",bbT5_GameboardWidth );
	rtSym( "#T5_GameboardHeight","bbT5_GameboardHeight",bbT5_GameboardHeight );
	rtSym( "#T5_GameboardDepth","bbT5_GameboardDepth",bbT5_GameboardDepth );
	rtSym( "$T5_ServiceVersion","bbT5_ServiceVersion",bbT5_ServiceVersion );
	rtSym( "%T5_UIRequestingAttention","bbT5_UIRequestingAttention",bbT5_UIRequestingAttention );
	rtSym( "%T5_CountGlasses","bbT5_CountGlasses",bbT5_CountGlasses );
	rtSym( "$T5_GlassesIdentifier%i","bbT5_GlassesIdentifier",bbT5_GlassesIdentifier );
	rtSym( "$T5_GlassesFriendlyName%i","bbT5_GlassesFriendlyName",bbT5_GlassesFriendlyName );
	rtSym( "#T5_GlassesIPD%i","bbT5_GlassesIPD",bbT5_GlassesIPD );
	rtSym( "%T5_Poll","bbT5_Poll",bbT5_Poll );
	rtSym( "T5_RunSample","bbT5_RunSample",bbT5_RunSample );
}
