// AUTOGENERATED. DO NOT EDIT.
// RUN `make` TO UPDATE.

#include <bb/blitz/module.h>
#include <bb/runtime.vrapi/runtime.vrapi.h>

BBMODULE_LINK( runtime_vrapi ){
	rtSym( "%HMDPivot",bbHMDPivot );
	rtSym( "%HMDHead",bbHMDHead );
	rtSym( "%HMDLeftEye",bbHMDLeftEye );
	rtSym( "%HMDRightEye",bbHMDRightEye );
	rtSym( "UpdateHMD",bbUpdateHMD );
}
