// AUTOGENERATED. DO NOT EDIT.
// RUN `make` TO UPDATE.

#include <bb/blitz/module.h>
#include <bb/runtime.vrapi/runtime.vrapi.h>

BBMODULE_LINK( runtime_vrapi ){
	rtSym( "%HMDPivot","bbHMDPivot",bbHMDPivot );
	rtSym( "%HMDHead","bbHMDHead",bbHMDHead );
	rtSym( "%HMDLeftEye","bbHMDLeftEye",bbHMDLeftEye );
	rtSym( "%HMDRightEye","bbHMDRightEye",bbHMDRightEye );
	rtSym( "UpdateHMD","bbUpdateHMD",bbUpdateHMD );
}
