#ifndef BB_STUB_COMMANDS_H
#define BB_STUB_COMMANDS_H

#include <bb/blitz/module.h>
#include <bb/stub/stub.h>

#ifdef __cplusplus
extern "C" {
#endif

// AUTOGENERATED. DO NOT EDIT.
// RUN `make` TO UPDATE.

#ifdef __cplusplus
}
#endif


#endif
