#ifndef BB_STREAM_COMMANDS_H
#define BB_STREAM_COMMANDS_H

#include <bb/blitz/module.h>
#include <bb/stream/stream.h>

#ifdef __cplusplus
extern "C" {
#endif

// AUTOGENERATED. DO NOT EDIT.
// RUN `make` TO UPDATE.
bb_int_t BBCALL bbEof( BBStream *stream );
bb_int_t BBCALL bbReadAvail( BBStream *stream );
bb_int_t BBCALL bbReadByte( BBStream *stream );
bb_int_t BBCALL bbReadShort( BBStream *stream );
bb_int_t BBCALL bbReadInt( BBStream *stream );
bb_float_t BBCALL bbReadFloat( BBStream *stream );
BBStr * BBCALL bbReadString( BBStream *stream );
BBStr * BBCALL bbReadLine( BBStream *stream );
void BBCALL bbWriteByte( BBStream *stream,bb_int_t byte );
void BBCALL bbWriteShort( BBStream *stream,bb_int_t short_ );
void BBCALL bbWriteInt( BBStream *stream,bb_int_t int_ );
void BBCALL bbWriteFloat( BBStream *stream,bb_float_t float_ );
void BBCALL bbWriteString( BBStream *stream,BBStr *string );
void BBCALL bbWriteLine( BBStream *stream,BBStr *string );
void BBCALL bbCopyStream( BBStream *src_stream,BBStream *dest_stream,bb_int_t buffer_size );

#ifdef __cplusplus
}
#endif


#endif
