// AUTOGENERATED. DO NOT EDIT.
// RUN `make` TO UPDATE.

#include <bb/blitz/module.h>
#include <bb/input/input.h>

BBMODULE_LINK( input ){
	rtSym( "%KeyDown%key","bbKeyDown",bbKeyDown );
	rtSym( "%KeyHit%key","bbKeyHit",bbKeyHit );
	rtSym( "%GetKey%ascii=1","bbGetKey",bbGetKey );
	rtSym( "%WaitKey","bbWaitKey",bbWaitKey );
	rtSym( "FlushKeys","bbFlushKeys",bbFlushKeys );
	rtSym( "%MouseDown%button","bbMouseDown",bbMouseDown );
	rtSym( "%MouseHit%button","bbMouseHit",bbMouseHit );
	rtSym( "%GetMouse","bbGetMouse",bbGetMouse );
	rtSym( "%WaitMouse","bbWaitMouse",bbWaitMouse );
	rtSym( "%MouseWait","bbWaitMouse",bbWaitMouse );
	rtSym( "%MouseX","bbMouseX",bbMouseX );
	rtSym( "%MouseY","bbMouseY",bbMouseY );
	rtSym( "%MouseZ","bbMouseZ",bbMouseZ );
	rtSym( "%MouseXSpeed","bbMouseXSpeed",bbMouseXSpeed );
	rtSym( "%MouseYSpeed","bbMouseYSpeed",bbMouseYSpeed );
	rtSym( "%MouseZSpeed","bbMouseZSpeed",bbMouseZSpeed );
	rtSym( "FlushMouse","bbFlushMouse",bbFlushMouse );
	rtSym( "%CountJoys","bbCountJoys",bbCountJoys );
	rtSym( "%FindJoy$id","bbFindJoy",bbFindJoy );
	rtSym( "$JoyID%port","bbJoyID",bbJoyID );
	rtSym( "$JoyName%port","bbJoyName",bbJoyName );
	rtSym( "%JoyType%port=0","bbJoyType",bbJoyType );
	rtSym( "%JoyDown%button%port=0","bbJoyDown",bbJoyDown );
	rtSym( "%JoyHit%button%port=0","bbJoyHit",bbJoyHit );
	rtSym( "%GetJoy%port=0","bbGetJoy",bbGetJoy );
	rtSym( "%WaitJoy%port=0","bbWaitJoy",bbWaitJoy );
	rtSym( "%JoyWait%port=0","bbWaitJoy",bbWaitJoy );
	rtSym( "#JoyX%port=0","bbJoyX",bbJoyX );
	rtSym( "#JoyY%port=0","bbJoyY",bbJoyY );
	rtSym( "#JoyZ%port=0","bbJoyZ",bbJoyZ );
	rtSym( "#JoyU%port=0","bbJoyU",bbJoyU );
	rtSym( "#JoyV%port=0","bbJoyV",bbJoyV );
	rtSym( "#JoyPitch%port=0","bbJoyPitch",bbJoyPitch );
	rtSym( "#JoyYaw%port=0","bbJoyYaw",bbJoyYaw );
	rtSym( "#JoyRoll%port=0","bbJoyRoll",bbJoyRoll );
	rtSym( "%JoyHat%port=0","bbJoyHat",bbJoyHat );
	rtSym( "%JoyXDir%port=0","bbJoyXDir",bbJoyXDir );
	rtSym( "%JoyYDir%port=0","bbJoyYDir",bbJoyYDir );
	rtSym( "%JoyZDir%port=0","bbJoyZDir",bbJoyZDir );
	rtSym( "%JoyUDir%port=0","bbJoyUDir",bbJoyUDir );
	rtSym( "%JoyVDir%port=0","bbJoyVDir",bbJoyVDir );
	rtSym( "FlushJoy","bbFlushJoy",bbFlushJoy );
}
