// AUTOGENERATED. DO NOT EDIT.
// RUN `bin/blitz3d config` TO UPDATE.

#include <bb/blitz/module.h>
#include <bb/input/input.h>

#ifdef WIN32
BBMODULE_LINK( input ){
	rtSym( "%CountJoys",bbCountJoys );
	rtSym( "%FindJoy$id",bbFindJoy );
	rtSym( "FlushJoy",bbFlushJoy );
	rtSym( "FlushKeys",bbFlushKeys );
	rtSym( "FlushMouse",bbFlushMouse );
	rtSym( "%GetJoy%port=0",bbGetJoy );
	rtSym( "%GetKey%ascii=1",bbGetKey );
	rtSym( "%GetMouse",bbGetMouse );
	rtSym( "%JoyDown%button%port=0",bbJoyDown );
	rtSym( "%JoyHat%port=0",bbJoyHat );
	rtSym( "%JoyHit%button%port=0",bbJoyHit );
	rtSym( "$JoyID%port",bbJoyID );
	rtSym( "$JoyName%port",bbJoyName );
	rtSym( "#JoyPitch%port=0",bbJoyPitch );
	rtSym( "#JoyRoll%port=0",bbJoyRoll );
	rtSym( "%JoyType%port=0",bbJoyType );
	rtSym( "#JoyU%port=0",bbJoyU );
	rtSym( "%JoyUDir%port=0",bbJoyUDir );
	rtSym( "#JoyV%port=0",bbJoyV );
	rtSym( "%JoyVDir%port=0",bbJoyVDir );
	rtSym( "%JoyWait%port=0",bbWaitJoy );
	rtSym( "#JoyX%port=0",bbJoyX );
	rtSym( "%JoyXDir%port=0",bbJoyXDir );
	rtSym( "#JoyY%port=0",bbJoyY );
	rtSym( "%JoyYDir%port=0",bbJoyYDir );
	rtSym( "#JoyYaw%port=0",bbJoyYaw );
	rtSym( "#JoyZ%port=0",bbJoyZ );
	rtSym( "%JoyZDir%port=0",bbJoyZDir );
	rtSym( "%KeyDown%key",bbKeyDown );
	rtSym( "%KeyHit%key",bbKeyHit );
	rtSym( "%MouseDown%button",bbMouseDown );
	rtSym( "%MouseHit%button",bbMouseHit );
	rtSym( "%MouseWait",bbWaitMouse );
	rtSym( "%MouseX",bbMouseX );
	rtSym( "%MouseXSpeed",bbMouseXSpeed );
	rtSym( "%MouseY",bbMouseY );
	rtSym( "%MouseYSpeed",bbMouseYSpeed );
	rtSym( "%MouseZ",bbMouseZ );
	rtSym( "%MouseZSpeed",bbMouseZSpeed );
	rtSym( "%WaitJoy%port=0",bbWaitJoy );
	rtSym( "%WaitKey",bbWaitKey );
	rtSym( "%WaitMouse",bbWaitMouse );
}
#endif
