// AUTOGENERATED. DO NOT EDIT.
// RUN `bin/blitz3d config` TO UPDATE.

#include <bb/blitz/module.h>
#include <bb/system/system.h>

#ifdef WIN32
BBMODULE_LINK( system ){
	rtSym( "#DPIScaleX",bbDPIScaleX );
	rtSym( "#DPIScaleY",bbDPIScaleY );
	rtSym( "Delay%millisecs",bbDelay );
	rtSym( "ExecFile$file",bbExecFile );
	rtSym( "$GetEnv$env_var",bbGetEnv );
	rtSym( "%MilliSecs",bbMilliSecs );
	rtSym( "%ScreenHeight%i=-1",bbScreenHeight );
	rtSym( "%ScreenWidth%i=-1",bbScreenWidth );
	rtSym( "SetEnv$env_var$value",bbSetEnv );
	rtSym( "$SystemProperty$property",bbSystemProperty );
}
#endif
