#ifndef BB_RUNTIME_COMMANDS_H
#define BB_RUNTIME_COMMANDS_H

#include <bb/blitz/module.h>
#include <bb/runtime/runtime.h>

#ifdef __cplusplus
extern "C" {
#endif

// AUTOGENERATED. DO NOT EDIT.
// RUN `make` TO UPDATE.
void BBCALL bbShowPointer(  );
void BBCALL bbHidePointer(  );
void BBCALL bbRuntimeError( BBStr *message );
void BBCALL bbMoveMouse( bb_int_t x,bb_int_t y );

#ifdef __cplusplus
}
#endif


#endif
