// AUTOGENERATED. DO NOT EDIT.
// RUN `bin/blitz3d config` TO UPDATE.

#include <bb/blitz/module.h>
#include <bb/runtime/runtime.h>

#ifdef WIN32
BBMODULE_LINK( runtime ){
	rtSym( "HidePointer",bbHidePointer );
	rtSym( "MoveMouse%x%y",bbMoveMouse );
	rtSym( "RuntimeError$message",bbRuntimeError );
	rtSym( "ShowPointer",bbShowPointer );
}
#endif
