// AUTOGENERATED. DO NOT EDIT.
// RUN `make` TO UPDATE.

#include <bb/blitz/module.h>
#include <bb/graphics/graphics.h>

BBMODULE_LINK( graphics ){
	rtSym( "%CountGfxDrivers",bbCountGfxDrivers );
	rtSym( "$GfxDriverName%driver",bbGfxDriverName );
	rtSym( "SetGfxDriver%driver",bbSetGfxDriver );
	rtSym( "%CountGfxModes",bbCountGfxModes );
	rtSym( "%GfxModeExists%width%height%depth",bbGfxModeExists );
	rtSym( "%GfxModeWidth%mode",bbGfxModeWidth );
	rtSym( "%GfxModeHeight%mode",bbGfxModeHeight );
	rtSym( "%GfxModeDepth%mode",bbGfxModeDepth );
	rtSym( "%AvailVidMem",bbAvailVidMem );
	rtSym( "%TotalVidMem",bbTotalVidMem );
	rtSym( "%GfxDriver3D%driver",bbGfxDriver3D );
	rtSym( "%CountGfxModes3D",bbCountGfxModes3D );
	rtSym( "%GfxMode3DExists%width%height%depth",bbGfxMode3DExists );
	rtSym( "%GfxMode3D%mode",bbGfxMode3D );
	rtSym( "%Windowed3D",bbWindowed3D );
	rtSym( "Graphics%width%height%depth=0%mode=0",bbGraphics );
	rtSym( "Graphics3D%width%height%depth=0%mode=0",bbGraphics3D );
	rtSym( "EndGraphics",bbEndGraphics );
	rtSym( "%GraphicsLost",bbGraphicsLost );
	rtSym( "%GraphicsOpen",bbGraphicsOpen );
	rtSym( "SetGamma%src_red%src_green%src_blue#dest_red#dest_green#dest_blue",bbSetGamma );
	rtSym( "UpdateGamma%calibrate=0",bbUpdateGamma );
	rtSym( "#GammaRed%red",bbGammaRed );
	rtSym( "#GammaGreen%green",bbGammaGreen );
	rtSym( "#GammaBlue%blue",bbGammaBlue );
	rtSym( "%FrontBuffer",bbFrontBuffer );
	rtSym( "%BackBuffer",bbBackBuffer );
	rtSym( "%ScanLine",bbScanLine );
	rtSym( "VWait%frames=1",bbVWait );
	rtSym( "Flip%vwait=1",bbFlip );
	rtSym( "%GraphicsWidth",bbGraphicsWidth );
	rtSym( "%GraphicsHeight",bbGraphicsHeight );
	rtSym( "%GraphicsDepth",bbGraphicsDepth );
	rtSym( "SetBuffer%buffer",bbSetBuffer );
	rtSym( "%GraphicsBuffer",bbGraphicsBuffer );
	rtSym( "%LoadBuffer%buffer$bmpfile",bbLoadBuffer );
	rtSym( "%SaveBuffer%buffer$bmpfile",bbSaveBuffer );
	rtSym( "BufferDirty%buffer",bbBufferDirty );
	rtSym( "LockBuffer%buffer=0",bbLockBuffer );
	rtSym( "UnlockBuffer%buffer=0",bbUnlockBuffer );
	rtSym( "%ReadPixel%x%y%buffer=0",bbReadPixel );
	rtSym( "WritePixel%x%y%argb%buffer=0",bbWritePixel );
	rtSym( "%ReadPixelFast%x%y%buffer=0",bbReadPixelFast );
	rtSym( "WritePixelFast%x%y%argb%buffer=0",bbWritePixelFast );
	rtSym( "CopyPixel%src_x%src_y%src_buffer%dest_x%dest_y%dest_buffer=0",bbCopyPixel );
	rtSym( "CopyPixelFast%src_x%src_y%src_buffer%dest_x%dest_y%dest_buffer=0",bbCopyPixelFast );
	rtSym( "CopyRect%source_x%source_y%width%height%dest_x%dest_y%src_buffer=0%dest_buffer=0",bbCopyRect );
}
