#ifndef BB_BLITZ_COMMANDS_H
#define BB_BLITZ_COMMANDS_H

#include <bb/blitz/module.h>
#include <bb/blitz/blitz.h>

#ifdef __cplusplus
extern "C" {
#endif

// AUTOGENERATED. DO NOT EDIT.
// RUN `make` TO UPDATE.
void BBCALL bbRuntimeStats(  );
void BBCALL bbStop(  );
void BBCALL bbDebugLog( BBStr *text );
void BBCALL bbEnd(  );
void BBCALL bbAppTitle( BBStr *title,BBStr *close_prompt );
BBStr * BBCALL bbCommandLine(  );

//symbols

//debug

#ifdef __cplusplus
}
#endif


#endif
