// AUTOGENERATED. DO NOT EDIT.
// RUN `make` TO UPDATE.

#include <bb/blitz/module.h>
#include <bb/blitz/blitz.h>

BBMODULE_LINK( blitz ){
	rtSym( "RuntimeStats",bbRuntimeStats );
	rtSym( "Stop",bbStop );
	rtSym( "DebugLog$text",bbDebugLog );
	rtSym( "End",bbEnd );
	rtSym( "AppTitle$title$close_prompt=\"\"",bbAppTitle );
	rtSym( "$CommandLine",bbCommandLine );
	rtSym( "_bbIntType",&_bbIntType );
	rtSym( "_bbFltType",&_bbFltType );
	rtSym( "_bbStrType",&_bbStrType );
	rtSym( "_bbCStrType",&_bbCStrType );
	rtSym( "_bbStrLoad",_bbStrLoad );
	rtSym( "_bbStrRelease",_bbStrRelease );
	rtSym( "_bbStrStore",_bbStrStore );
	rtSym( "_bbStrCompare",_bbStrCompare );
	rtSym( "_bbStrConcat",_bbStrConcat );
	rtSym( "_bbStrToInt",_bbStrToInt );
	rtSym( "_bbStrFromInt",_bbStrFromInt );
	rtSym( "_bbStrToFloat",_bbStrToFloat );
	rtSym( "_bbStrFromFloat",_bbStrFromFloat );
	rtSym( "_bbStrConst",_bbStrConst );
	rtSym( "_bbDimArray",_bbDimArray );
	rtSym( "_bbUndimArray",_bbUndimArray );
	rtSym( "_bbArrayBoundsEx",_bbArrayBoundsEx );
	rtSym( "_bbVecAlloc",_bbVecAlloc );
	rtSym( "_bbVecFree",_bbVecFree );
	rtSym( "_bbVecBoundsEx",_bbVecBoundsEx );
	rtSym( "_bbObjNew",_bbObjNew );
	rtSym( "_bbObjDelete",_bbObjDelete );
	rtSym( "_bbObjDeleteEach",_bbObjDeleteEach );
	rtSym( "_bbObjRelease",_bbObjRelease );
	rtSym( "_bbObjStore",_bbObjStore );
	rtSym( "_bbObjCompare",_bbObjCompare );
	rtSym( "_bbObjNext",_bbObjNext );
	rtSym( "_bbObjPrev",_bbObjPrev );
	rtSym( "_bbObjFirst",_bbObjFirst );
	rtSym( "_bbObjLast",_bbObjLast );
	rtSym( "_bbObjInsBefore",_bbObjInsBefore );
	rtSym( "_bbObjInsAfter",_bbObjInsAfter );
	rtSym( "_bbObjEachFirst",_bbObjEachFirst );
	rtSym( "_bbObjEachNext",_bbObjEachNext );
	rtSym( "_bbObjEachFirst2",_bbObjEachFirst2 );
	rtSym( "_bbObjEachNext2",_bbObjEachNext2 );
	rtSym( "_bbObjToStr",_bbObjToStr );
	rtSym( "_bbObjToHandle",_bbObjToHandle );
	rtSym( "_bbObjFromHandle",_bbObjFromHandle );
	rtSym( "_bbNullObjEx",_bbNullObjEx );
	rtSym( "_bbRestore",_bbRestore );
	rtSym( "_bbReadInt",_bbReadInt );
	rtSym( "_bbReadFloat",_bbReadFloat );
	rtSym( "_bbReadStr",_bbReadStr );
	rtSym( "_bbAbs",_bbAbs );
	rtSym( "_bbSgn",_bbSgn );
	rtSym( "_bbMod",_bbMod );
	rtSym( "_bbFAbs",_bbFAbs );
	rtSym( "_bbFSgn",_bbFSgn );
	rtSym( "_bbFMod",_bbFMod );
	rtSym( "_bbFPow",_bbFPow );
	rtSym( "_bbPushGosub",_bbPushGosub );
	rtSym( "_bbPopGosub",_bbPopGosub );
	rtSym( "_bbDebugStmt",_bbDebugStmt );
	rtSym( "_bbDebugEnter",_bbDebugEnter );
	rtSym( "_bbDebugLeave",_bbDebugLeave );
}
