// AUTOGENERATED. DO NOT EDIT.
// RUN `make` TO UPDATE.

#include <bb/blitz/module.h>
#include <bb/blitz/blitz.h>

BBMODULE_LINK( blitz ){
	rtSym( "RuntimeStats",bbRuntimeStats );
	rtSym( "Stop",bbStop );
	rtSym( "DebugLog$text",bbDebugLog );
	rtSym( "End",bbEnd );
	rtSym( "AppTitle$title$close_prompt=""",bbAppTitle );
	rtSym( "$CommandLine",bbCommandLine );
}
