#ifndef BB_STDIO_COMMANDS_H
#define BB_STDIO_COMMANDS_H

#include <bb/blitz/module.h>
#include "../config.h"

#ifdef __cplusplus
extern "C" {
#endif

// AUTOGENERATED. DO NOT EDIT.
// RUN `make` TO UPDATE.
void BBCALL bbWriteStdout( BBStr *str );
void BBCALL bbWriteStderr( BBStr *str );

#ifdef __cplusplus
}
#endif


#endif
