// AUTOGENERATED. DO NOT EDIT.
// RUN `make` TO UPDATE.

#include <bb/blitz/module.h>
#include <bb/stdio/stdio.h>

BBMODULE_LINK( stdio ){
	rtSym( "WriteStdout$str","bbWriteStdout",bbWriteStdout );
	rtSym( "WriteStderr$str","bbWriteStderr",bbWriteStderr );
}
