// AUTOGENERATED. DO NOT EDIT.
// RUN `bin/blitz3d config` TO UPDATE.

#include <bb/blitz/module.h>
#include <bb/math/math.h>

#ifdef WIN32
BBMODULE_LINK( math ){
	rtSym( "#ACos#degrees",bbACos );
	rtSym( "#ASin#degrees",bbASin );
	rtSym( "#ATan#degrees",bbATan );
	rtSym( "#ATan2#y#x",bbATan2 );
	rtSym( "#Ceil#n",bbCeil );
	rtSym( "#Cos#degrees",bbCos );
	rtSym( "#Exp#n",bbExp );
	rtSym( "#Floor#n",bbFloor );
	rtSym( "#Log#x",bbLog );
	rtSym( "#Log10#x",bbLog10 );
	rtSym( "%Rand%from%to=1",bbRand );
	rtSym( "#Rnd#from#to=0",bbRnd );
	rtSym( "%RndSeed",bbRndSeed );
	rtSym( "SeedRnd%seed",bbSeedRnd );
	rtSym( "#Sin#degrees",bbSin );
	rtSym( "#Sqr#n",bbSqr );
	rtSym( "#Tan#degrees",bbTan );
}
#endif
