#ifndef BB_INPUT_DIRECTINPUT8_COMMANDS_H
#define BB_INPUT_DIRECTINPUT8_COMMANDS_H

#include <bb/blitz/module.h>
#include <bb/input.directinput8/input.directinput8.h>

#ifdef __cplusplus
extern "C" {
#endif

// AUTOGENERATED. DO NOT EDIT.
// RUN `make` TO UPDATE.
void BBCALL bbEnableDirectInput( bb_int_t enable );
bb_int_t BBCALL bbDirectInputEnabled(  );

#ifdef __cplusplus
}
#endif


#endif
