// AUTOGENERATED. DO NOT EDIT.
// RUN `make` TO UPDATE.

#include <bb/blitz/module.h>
#include <bb/input.directinput8/input.directinput8.h>

BBMODULE_LINK( input_directinput8 ){
	rtSym( "EnableDirectInput%enable",bbEnableDirectInput );
	rtSym( "%DirectInputEnabled",bbDirectInputEnabled );
}
