#ifndef BB_RUNTIME_NX_COMMANDS_H
#define BB_RUNTIME_NX_COMMANDS_H

#include <bb/blitz/module.h>
#include <bb/runtime.nx/runtime.nx.h>

#ifdef __cplusplus
extern "C" {
#endif

// AUTOGENERATED. DO NOT EDIT.
// RUN `make` TO UPDATE.
void BBCALL bbUpdateConsole(  );
void BBCALL bbInitConsole(  );

#ifdef __cplusplus
}
#endif


#endif
