// AUTOGENERATED. DO NOT EDIT.
// RUN `make` TO UPDATE.

#include <bb/blitz/module.h>
#include <bb/runtime.nx/runtime.nx.h>

BBMODULE_LINK( runtime_nx ){
	rtSym( "UpdateConsole","bbUpdateConsole",bbUpdateConsole );
	rtSym( "InitConsole","bbInitConsole",bbInitConsole );
}
