#ifndef BB_MULTIPLAY_DIRECTPLAY_COMMANDS_H
#define BB_MULTIPLAY_DIRECTPLAY_COMMANDS_H

#include <bb/blitz/module.h>
#include <bb/multiplay.directplay/multiplay.directplay.h>

#ifdef __cplusplus
extern "C" {
#endif

// AUTOGENERATED. DO NOT EDIT.
// RUN `make` TO UPDATE.
bb_int_t BBCALL bbStartNetGame(  );
bb_int_t BBCALL bbHostNetGame( BBStr *game_name );
bb_int_t BBCALL bbJoinNetGame( BBStr *game_name,BBStr *ip_address );
void BBCALL bbStopNetGame(  );
bb_int_t BBCALL bbCreateNetPlayer( BBStr *name );
void BBCALL bbDeleteNetPlayer( bb_int_t player );
BBStr * BBCALL bbNetPlayerName( bb_int_t player );
bb_int_t BBCALL bbNetPlayerLocal( bb_int_t player );
bb_int_t BBCALL bbSendNetMsg( bb_int_t type,BBStr *msg,bb_int_t from_player,bb_int_t to_player,bb_int_t reliable );
bb_int_t BBCALL bbRecvNetMsg(  );
bb_int_t BBCALL bbNetMsgType(  );
bb_int_t BBCALL bbNetMsgFrom(  );
bb_int_t BBCALL bbNetMsgTo(  );
BBStr * BBCALL bbNetMsgData(  );

#ifdef __cplusplus
}
#endif


#endif
