require_relative './node/base'

require_relative './node/ass'
require_relative './node/call'
require_relative './node/cast'
require_relative './node/delete_each'
require_relative './node/expr_stmt'
require_relative './node/float_const'
require_relative './node/ident_var'
require_relative './node/if'
require_relative './node/int_const'
require_relative './node/new'
require_relative './node/prog'
require_relative './node/rel_expr'
require_relative './node/stmt_seq'
require_relative './node/string_const'
require_relative './node/var_expr'
