class String
  def indent
    split("\n").join("\n  ")
  end
end

require_relative './decl'

require_relative './node/base'
require_relative './node/invalid'

require_relative './node/expr'
require_relative './node/after'
require_relative './node/arith_expr'
require_relative './node/before'
require_relative './node/bin_expr'
require_relative './node/call'
require_relative './node/cast'
require_relative './node/first'
require_relative './node/last'
require_relative './node/new'
require_relative './node/null'
require_relative './node/rel_expr'
require_relative './node/uni_expr'
require_relative './node/var_expr'

require_relative './node/const'
require_relative './node/float_const'
require_relative './node/int_const'
require_relative './node/string_const'

require_relative './node/decl'
require_relative './node/func_decl'
require_relative './node/struct_decl'
require_relative './node/var_decl'
require_relative './node/vector_decl'

require_relative './node/var'
require_relative './node/array_var'
require_relative './node/decl_var'
require_relative './node/field_var'
require_relative './node/ident_var'
require_relative './node/vector_var'

require_relative './node/stmt'
require_relative './node/ass'
require_relative './node/delete'
require_relative './node/dim'
require_relative './node/exit'
require_relative './node/goto'
require_relative './node/include'
require_relative './node/insert'
require_relative './node/label'
require_relative './node/for'
require_relative './node/for_each'

require_relative './node/case'
require_relative './node/decl_stmt'
require_relative './node/delete_each'
require_relative './node/expr_stmt'
require_relative './node/if'
require_relative './node/repeat'
require_relative './node/return'
require_relative './node/select'
require_relative './node/stmt_seq'
require_relative './node/while'

require_relative './node/prog'

require_relative './type/base'
require_relative './type/array'
require_relative './type/const'
require_relative './type/invalid'
require_relative './type/int'
require_relative './type/float'
require_relative './type/func'
require_relative './type/null'
require_relative './type/string'
require_relative './type/struct'
require_relative './type/vector'
require_relative './type/void'
