// AUTOGENERATED. DO NOT EDIT.
// RUN `bin/blitz3d config` TO UPDATE.

#include <bb/blitz/module.h>
#include <bb/enet/enet.h>

#ifdef WIN32
BBMODULE_LINK( enet ){
	rtSym( "%CreateNetPlayer$name",bbCreateNetPlayer );
	rtSym( "%HostNetGame$game_name",bbHostNetGame );
	rtSym( "%JoinNetGame$game_name$ip_address",bbJoinNetGame );
	rtSym( "$NetMsgData",bbNetMsgData );
	rtSym( "%NetMsgFrom",bbNetMsgFrom );
	rtSym( "%NetMsgTo",bbNetMsgTo );
	rtSym( "%NetMsgType",bbNetMsgType );
	rtSym( "%RecvNetMsg",bbRecvNetMsg );
	rtSym( "%SendNetMsg%type$msg%from_player%to_player=0%reliable=1",bbSendNetMsg );
}
#endif
