#ifndef BB_UNIT_TEST_COMMANDS_H
#define BB_UNIT_TEST_COMMANDS_H

#include <bb/blitz/module.h>
#include <bb/unit-test/unit-test.h>

#ifdef __cplusplus
extern "C" {
#endif

// AUTOGENERATED. DO NOT EDIT.
// RUN `make` TO UPDATE.
void BBCALL bbContext( BBStr *mesg );
void BBCALL bbExpect( bb_int_t condition,BBStr *mesg );
void BBCALL bbExpectIntEq( bb_int_t a,bb_int_t b,BBStr *mesg );
void BBCALL bbExpectFloatEq( bb_float_t a,bb_float_t b,BBStr *mesg );

#ifdef __cplusplus
}
#endif


#endif
