// AUTOGENERATED. DO NOT EDIT.
// RUN `make` TO UPDATE.

#include <bb/blitz/module.h>
#include <bb/unit-test/unit-test.h>

BBMODULE_LINK( unit_test ){
	rtSym( "Context$mesg","bbContext",bbContext );
	rtSym( "Expect%condition$mesg","bbExpect",bbExpect );
	rtSym( "ExpectInt%a%b$mesg=\"\"","bbExpectInt",bbExpectInt );
	rtSym( "ExpectFloat#a#b$mesg=\"\"","bbExpectFloat",bbExpectFloat );
	rtSym( "ExpectStr$a$b$mesg=\"\"","bbExpectStr",bbExpectStr );
}
