// AUTOGENERATED. DO NOT EDIT.
// RUN `make` TO UPDATE.

#include <bb/blitz/module.h>
#include <bb/unit-test/unit-test.h>

BBMODULE_LINK( unit_test ){
	rtSym( "Context$mesg",bbContext );
	rtSym( "Expect%condition$mesg",bbExpect );
	rtSym( "ExpectIntEq%a%b$mesg",bbExpectIntEq );
	rtSym( "ExpectFloatEq#a#b$mesg",bbExpectFloatEq );
}
