#ifndef BB_SOCKETS_COMMANDS_H
#define BB_SOCKETS_COMMANDS_H

#include <bb/blitz/module.h>
#include <bb/sockets/sockets.h>

#ifdef __cplusplus
extern "C" {
#endif

// AUTOGENERATED. DO NOT EDIT.
// RUN `make` TO UPDATE.
BBStr * BBCALL bbDottedIP( bb_int_t IP );
bb_int_t BBCALL bbCountHostIPs( BBStr *host_name );
bb_int_t BBCALL bbHostIP( bb_int_t host_index );
UDPStream * BBCALL bbCreateUDPStream( bb_int_t port );
void BBCALL bbCloseUDPStream( UDPStream *udp_stream );
void BBCALL bbSendUDPMsg( UDPStream *udp_stream,bb_int_t dest_ip,bb_int_t dest_port );
bb_int_t BBCALL bbRecvUDPMsg( UDPStream *udp_stream );
bb_int_t BBCALL bbUDPStreamIP( UDPStream *udp_stream );
bb_int_t BBCALL bbUDPStreamPort( UDPStream *udp_stream );
bb_int_t BBCALL bbUDPMsgIP( UDPStream *udp_stream );
bb_int_t BBCALL bbUDPMsgPort( UDPStream *udp_stream );
void BBCALL bbUDPTimeouts( bb_int_t recv_timeout );
TCPStream * BBCALL bbOpenTCPStream( BBStr *server,bb_int_t server_port,bb_int_t local_port );
void BBCALL bbCloseTCPStream( TCPStream *tcp_stream );
TCPServer * BBCALL bbCreateTCPServer( bb_int_t port );
void BBCALL bbCloseTCPServer( TCPServer *tcp_server );
TCPStream * BBCALL bbAcceptTCPStream( TCPServer *tcp_server );
bb_int_t BBCALL bbTCPStreamIP( TCPStream *tcp_stream );
bb_int_t BBCALL bbTCPStreamPort( TCPStream *tcp_stream );
void BBCALL bbTCPTimeouts( bb_int_t read_millis,bb_int_t accept_millis );

#ifdef __cplusplus
}
#endif


#endif
