// AUTOGENERATED. DO NOT EDIT.
// RUN `bin/blitz3d config` TO UPDATE.

#include <bb/blitz/module.h>
#include <bb/sockets/sockets.h>

#ifdef WIN32
BBMODULE_LINK( sockets ){
	rtSym( "%AcceptTCPStream%tcp_server",bbAcceptTCPStream );
	rtSym( "CloseTCPServer%tcp_server",bbCloseTCPServer );
	rtSym( "CloseTCPStream%tcp_stream",bbCloseTCPStream );
	rtSym( "CloseUDPStream%udp_stream",bbCloseUDPStream );
	rtSym( "%CountHostIPs$host_name",bbCountHostIPs );
	rtSym( "%CreateTCPServer%port",bbCreateTCPServer );
	rtSym( "%CreateUDPStream%port=0",bbCreateUDPStream );
	rtSym( "$DottedIP%IP",bbDottedIP );
	rtSym( "%HostIP%host_index",bbHostIP );
	rtSym( "%OpenTCPStream$server%server_port%local_port=0",bbOpenTCPStream );
	rtSym( "%RecvUDPMsg%udp_stream",bbRecvUDPMsg );
	rtSym( "SendUDPMsg%udp_stream%dest_ip%dest_port=0",bbSendUDPMsg );
	rtSym( "%TCPStreamIP%tcp_stream",bbTCPStreamIP );
	rtSym( "%TCPStreamPort%tcp_stream",bbTCPStreamPort );
	rtSym( "TCPTimeouts%read_millis%accept_millis",bbTCPTimeouts );
	rtSym( "%UDPMsgIP%udp_stream",bbUDPMsgIP );
	rtSym( "%UDPMsgPort%udp_stream",bbUDPMsgPort );
	rtSym( "%UDPStreamIP%udp_stream",bbUDPStreamIP );
	rtSym( "%UDPStreamPort%udp_stream",bbUDPStreamPort );
	rtSym( "UDPTimeouts%recv_timeout",bbUDPTimeouts );
}
#endif
