// AUTOGENERATED. DO NOT EDIT.
// RUN `make` TO UPDATE.

#include <bb/blitz/module.h>
#include <bb/ode/ode.h>

BBMODULE_LINK( ode ){
	rtSym( "dInitODE","_odeInitODE",_odeInitODE );
	rtSym( "dCloseODE","_odeCloseODE",_odeCloseODE );
	rtSym( "%dWorldCreate","_odeWorldCreate",_odeWorldCreate );
	rtSym( "dWorldDestroy%world","_odeWorldDestroy",_odeWorldDestroy );
	rtSym( "dWorldSetGravity%world#x#y#z","_odeWorldSetGravity",_odeWorldSetGravity );
	rtSym( "%dWorldQuickStep%world#stepsize","_odeWorldQuickStep",_odeWorldQuickStep );
	rtSym( "dWorldSetAutoDisableFlag%world%do_auto_disable","_odeWorldSetAutoDisableFlag",_odeWorldSetAutoDisableFlag );
	rtSym( "%dHashSpaceCreate%space","_odeHashSpaceCreate",_odeHashSpaceCreate );
	rtSym( "dSpaceDestroy%space","_odeSpaceDestroy",_odeSpaceDestroy );
	rtSym( "dBodySetAutoDisableFlag%body%do_auto_disable","_odeBodySetAutoDisableFlag",_odeBodySetAutoDisableFlag );
	rtSym( "%dBodyCreate%world","_odeBodyCreate",_odeBodyCreate );
	rtSym( "dBodySetPosition%body#x#y#z","_odeBodySetPosition",_odeBodySetPosition );
	rtSym( "dBodySetRotation%body#pitch#yaw#roll","_odeBodySetRotation",_odeBodySetRotation );
	rtSym( "dGeomSetBody%geom%body","_odeGeomSetBody",_odeGeomSetBody );
	rtSym( "#dGeomGetPositionX%geom","_odeGeomGetPositionX",_odeGeomGetPositionX );
	rtSym( "#dGeomGetPositionY%geom","_odeGeomGetPositionY",_odeGeomGetPositionY );
	rtSym( "#dGeomGetPositionZ%geom","_odeGeomGetPositionZ",_odeGeomGetPositionZ );
	rtSym( "#dGeomGetPitch%geom","_odeGeomGetPitch",_odeGeomGetPitch );
	rtSym( "#dGeomGetYaw%geom","_odeGeomGetYaw",_odeGeomGetYaw );
	rtSym( "#dGeomGetRoll%geom","_odeGeomGetRoll",_odeGeomGetRoll );
	rtSym( "%dCreateBox%space#lx#ly#lz","_odeCreateBox",_odeCreateBox );
	rtSym( "%dCreatePlane%space#a#b#c#d","_odeCreatePlane",_odeCreatePlane );
	rtSym( "%dJointGroupCreate%max_size","_odeJointGroupCreate",_odeJointGroupCreate );
	rtSym( "dJointGroupDestroy%group","_odeJointGroupDestroy",_odeJointGroupDestroy );
	rtSym( "dJointGroupEmpty%group","_odeJointGroupEmpty",_odeJointGroupEmpty );
	rtSym( "dSpaceCollide%space%world%group","_odeSpaceCollide",_odeSpaceCollide );
	rtSym( "dContactSetMaxContacts%max","_odeContactSetMaxContacts",_odeContactSetMaxContacts );
	rtSym( "%dContactGetMaxContacts","_odeContactGetMaxContacts",_odeContactGetMaxContacts );
	rtSym( "dContactSetMode%mode","_odeContactSetMode",_odeContactSetMode );
	rtSym( "%dContactGetMode","_odeContactGetMode",_odeContactGetMode );
	rtSym( "dContactSetMu#mu","_odeContactSetMu",_odeContactSetMu );
	rtSym( "#dContactGetMu","_odeContactGetMu",_odeContactGetMu );
	rtSym( "dContactSetMu2#mu","_odeContactSetMu2",_odeContactSetMu2 );
	rtSym( "#dContactGetMu2","_odeContactGetMu2",_odeContactGetMu2 );
	rtSym( "dContactSetFDir1#fdir1x#fdir1y#fdir1z","_odeContactSetFDir1",_odeContactSetFDir1 );
	rtSym( "dContactGetFDir1","_odeContactGetFDir1",_odeContactGetFDir1 );
	rtSym( "dContactSetBounce#bounce","_odeContactSetBounce",_odeContactSetBounce );
	rtSym( "#dContactGetBounce","_odeContactGetBounce",_odeContactGetBounce );
	rtSym( "dContactSetBounceVel#vel","_odeContactSetBounceVel",_odeContactSetBounceVel );
	rtSym( "#dContactGetBounceVel","_odeContactGetBounceVel",_odeContactGetBounceVel );
	rtSym( "dContactSetSoftERP#erp","_odeContactSetSoftERP",_odeContactSetSoftERP );
	rtSym( "#dContactGetSoftERP","_odeContactGetSoftERP",_odeContactGetSoftERP );
	rtSym( "dContactSetSoftCFM#cfm","_odeContactSetSoftCFM",_odeContactSetSoftCFM );
	rtSym( "#dContactGetSoftCFM","_odeContactGetSoftCFM",_odeContactGetSoftCFM );
	rtSym( "dContactSetMotion1#motion","_odeContactSetMotion1",_odeContactSetMotion1 );
	rtSym( "#dContactGetMotion1","_odeContactGetMotion1",_odeContactGetMotion1 );
	rtSym( "dContactSetMotion2#motion","_odeContactSetMotion2",_odeContactSetMotion2 );
	rtSym( "#dContactGetMotion2","_odeContactGetMotion2",_odeContactGetMotion2 );
	rtSym( "dContactSetSlip1#slip","_odeContactSetSlip1",_odeContactSetSlip1 );
	rtSym( "#dContactGetSlip1","_odeContactGetSlip1",_odeContactGetSlip1 );
	rtSym( "dContactSetSlip2#slip","_odeContactSetSlip2",_odeContactSetSlip2 );
	rtSym( "#dContactGetSlip2","_odeContactGetSlip2",_odeContactGetSlip2 );
	rtSym( "dGeomSyncEntity%geom%entity","_odeGeomSyncEntity",_odeGeomSyncEntity );
	rtSym( "dRegisterODE%key1%key2%key3%key4","_odeRegisterODE",_odeRegisterODE );
	rtSym( "#dGetVersion","_odeGetVersion",_odeGetVersion );
	rtSym( "%dDemoTime","_odeDemoTime",_odeDemoTime );
}
