// AUTOGENERATED. DO NOT EDIT.
// RUN `make` TO UPDATE.

#include <bb/blitz/module.h>
#include <bb/ode/ode.h>

BBMODULE_LINK( ode ){
	rtSym( "dInitODE",_odeInitODE );
	rtSym( "dCloseODE",_odeCloseODE );
	rtSym( "%dWorldCreate",_odeWorldCreate );
	rtSym( "dWorldDestroy%world",_odeWorldDestroy );
	rtSym( "dWorldSetGravity%world#x#y#z",_odeWorldSetGravity );
	rtSym( "%dWorldQuickStep%world#stepsize",_odeWorldQuickStep );
	rtSym( "dWorldSetAutoDisableFlag%world%do_auto_disable",_odeWorldSetAutoDisableFlag );
	rtSym( "%dHashSpaceCreate%space",_odeHashSpaceCreate );
	rtSym( "dSpaceDestroy%space",_odeSpaceDestroy );
	rtSym( "dBodySetAutoDisableFlag%body%do_auto_disable",_odeBodySetAutoDisableFlag );
	rtSym( "%dBodyCreate%world",_odeBodyCreate );
	rtSym( "dBodySetPosition%body#x#y#z",_odeBodySetPosition );
	rtSym( "dBodySetRotation%body#pitch#yaw#roll",_odeBodySetRotation );
	rtSym( "dGeomSetBody%geom%body",_odeGeomSetBody );
	rtSym( "#dGeomGetPositionX%geom",_odeGeomGetPositionX );
	rtSym( "#dGeomGetPositionY%geom",_odeGeomGetPositionY );
	rtSym( "#dGeomGetPositionZ%geom",_odeGeomGetPositionZ );
	rtSym( "#dGeomGetPitch%geom",_odeGeomGetPitch );
	rtSym( "#dGeomGetYaw%geom",_odeGeomGetYaw );
	rtSym( "#dGeomGetRoll%geom",_odeGeomGetRoll );
	rtSym( "%dCreateBox%space#lx#ly#lz",_odeCreateBox );
	rtSym( "%dCreatePlane%space#a#b#c#d",_odeCreatePlane );
	rtSym( "%dJointGroupCreate%max_size",_odeJointGroupCreate );
	rtSym( "dJointGroupDestroy%group",_odeJointGroupDestroy );
	rtSym( "dJointGroupEmpty%group",_odeJointGroupEmpty );
	rtSym( "dSpaceCollide%space%world%group",_odeSpaceCollide );
	rtSym( "dContactSetMaxContacts%max",_odeContactSetMaxContacts );
	rtSym( "%dContactGetMaxContacts",_odeContactGetMaxContacts );
	rtSym( "dContactSetMode%mode",_odeContactSetMode );
	rtSym( "%dContactGetMode",_odeContactGetMode );
	rtSym( "dContactSetMu#mu",_odeContactSetMu );
	rtSym( "#dContactGetMu",_odeContactGetMu );
	rtSym( "dContactSetMu2#mu",_odeContactSetMu2 );
	rtSym( "#dContactGetMu2",_odeContactGetMu2 );
	rtSym( "dContactSetFDir1#fdir1x#fdir1y#fdir1z",_odeContactSetFDir1 );
	rtSym( "dContactGetFDir1",_odeContactGetFDir1 );
	rtSym( "dContactSetBounce#bounce",_odeContactSetBounce );
	rtSym( "#dContactGetBounce",_odeContactGetBounce );
	rtSym( "dContactSetBounceVel#vel",_odeContactSetBounceVel );
	rtSym( "#dContactGetBounceVel",_odeContactGetBounceVel );
	rtSym( "dContactSetSoftERP#erp",_odeContactSetSoftERP );
	rtSym( "#dContactGetSoftERP",_odeContactGetSoftERP );
	rtSym( "dContactSetSoftCFM#cfm",_odeContactSetSoftCFM );
	rtSym( "#dContactGetSoftCFM",_odeContactGetSoftCFM );
	rtSym( "dContactSetMotion1#motion",_odeContactSetMotion1 );
	rtSym( "#dContactGetMotion1",_odeContactGetMotion1 );
	rtSym( "dContactSetMotion2#motion",_odeContactSetMotion2 );
	rtSym( "#dContactGetMotion2",_odeContactGetMotion2 );
	rtSym( "dContactSetSlip1#slip",_odeContactSetSlip1 );
	rtSym( "#dContactGetSlip1",_odeContactGetSlip1 );
	rtSym( "dContactSetSlip2#slip",_odeContactSetSlip2 );
	rtSym( "#dContactGetSlip2",_odeContactGetSlip2 );
	rtSym( "dGeomSyncEntity%geom%entity",_odeGeomSyncEntity );
	rtSym( "dRegisterODE%key1%key2%key3%key4",_odeRegisterODE );
	rtSym( "#dGetVersion",_odeGetVersion );
	rtSym( "%dDemoTime",_odeDemoTime );
}
