#ifndef BB_FILESYSTEM_COMMANDS_H
#define BB_FILESYSTEM_COMMANDS_H

#include <bb/blitz/module.h>
#include <bb/filesystem/filesystem.h>

#ifdef __cplusplus
extern "C" {
#endif

// AUTOGENERATED. DO NOT EDIT.
// RUN `make` TO UPDATE.
BBFile * BBCALL bbOpenFile( BBStr *filename );
BBFile * BBCALL bbReadFile( BBStr *filename );
BBFile * BBCALL bbWriteFile( BBStr *filename );
void BBCALL bbCloseFile( BBFile *file_stream );
bb_int_t BBCALL bbFilePos( BBFile *file_stream );
bb_int_t BBCALL bbSeekFile( BBFile *file_stream,bb_int_t pos );
BBDir * BBCALL bbReadDir( BBStr *dirname );
void BBCALL bbCloseDir( BBDir *dir );
BBStr * BBCALL bbNextFile( BBDir *dir );
BBStr * BBCALL bbCurrentDir(  );
void BBCALL bbChangeDir( BBStr *dir );
void BBCALL bbCreateDir( BBStr *dir );
void BBCALL bbDeleteDir( BBStr *dir );
bb_int_t BBCALL bbFileSize( BBStr *file );
bb_int_t BBCALL bbFileType( BBStr *file );
void BBCALL bbCopyFile( BBStr *file,BBStr *to );
void BBCALL bbDeleteFile( BBStr *file );

#ifdef __cplusplus
}
#endif


#endif
