// AUTOGENERATED. DO NOT EDIT.
// RUN `make` TO UPDATE.

#include <bb/blitz/module.h>
#include <bb/filesystem/filesystem.h>

BBMODULE_LINK( filesystem ){
	rtSym( "%OpenFile$filename","bbOpenFile",bbOpenFile );
	rtSym( "%ReadFile$filename","bbReadFile",bbReadFile );
	rtSym( "%WriteFile$filename","bbWriteFile",bbWriteFile );
	rtSym( "CloseFile%file_stream","bbCloseFile",bbCloseFile );
	rtSym( "%FilePos%file_stream","bbFilePos",bbFilePos );
	rtSym( "%SeekFile%file_stream%pos","bbSeekFile",bbSeekFile );
	rtSym( "%ReadDir$dirname","bbReadDir",bbReadDir );
	rtSym( "CloseDir%dir","bbCloseDir",bbCloseDir );
	rtSym( "$NextFile%dir","bbNextFile",bbNextFile );
	rtSym( "$CurrentDir","bbCurrentDir",bbCurrentDir );
	rtSym( "ChangeDir$dir","bbChangeDir",bbChangeDir );
	rtSym( "CreateDir$dir","bbCreateDir",bbCreateDir );
	rtSym( "DeleteDir$dir","bbDeleteDir",bbDeleteDir );
	rtSym( "%FileSize$file","bbFileSize",bbFileSize );
	rtSym( "%FileType$file","bbFileType",bbFileType );
	rtSym( "CopyFile$file$to","bbCopyFile",bbCopyFile );
	rtSym( "DeleteFile$file","bbDeleteFile",bbDeleteFile );
}
