// AUTOGENERATED. DO NOT EDIT.
// RUN `bin/blitz3d config` TO UPDATE.

#include <bb/blitz/module.h>
#include <bb/string/string.h>

#ifdef WIN32
BBMODULE_LINK( string ){
	rtSym( "%Asc$string",bbAsc );
	rtSym( "$Bin%value",bbBin );
	rtSym( "$Chr%ascii",bbChr );
	rtSym( "$CurrentDate",bbCurrentDate );
	rtSym( "$CurrentTime",bbCurrentTime );
	rtSym( "$Hex%value",bbHex );
	rtSym( "%Instr$string$find%from=1",bbInstr );
	rtSym( "$LSet$string%size",bbLSet );
	rtSym( "$Left$string%count",bbLeft );
	rtSym( "%Len$string",bbLen );
	rtSym( "$Lower$string",bbLower );
	rtSym( "$Mid$string%start%count=-1",bbMid );
	rtSym( "$RSet$string%size",bbRSet );
	rtSym( "$Replace$string$from$to",bbReplace );
	rtSym( "$Right$string%count",bbRight );
	rtSym( "$String$string%repeat",bbString );
	rtSym( "$Trim$string",bbTrim );
	rtSym( "$Upper$string",bbUpper );
}
#endif
