// AUTOGENERATED. DO NOT EDIT.
// RUN `bin/blitz3d config` TO UPDATE.

#include <bb/blitz/module.h>
#include <bb/timer/timer.h>

#ifdef WIN32
BBMODULE_LINK( timer ){
	rtSym( "%CreateTimer%hertz",bbCreateTimer );
	rtSym( "FreeTimer%timer",bbFreeTimer );
	rtSym( "%WaitTimer%timer",bbWaitTimer );
}
#endif
