#ifndef BB_BLITZ2D_COMMANDS_H
#define BB_BLITZ2D_COMMANDS_H

#include <bb/blitz/module.h>
#include <bb/blitz2d/blitz2d.h>

#ifdef __cplusplus
extern "C" {
#endif

// AUTOGENERATED. DO NOT EDIT.
// RUN `make` TO UPDATE.

//rendering
void BBCALL bbOrigin( bb_int_t x,bb_int_t y );
void BBCALL bbViewport( bb_int_t x,bb_int_t y,bb_int_t width,bb_int_t height );
void BBCALL bbColor( bb_int_t red,bb_int_t green,bb_int_t blue );
void BBCALL bbGetColor( bb_int_t x,bb_int_t y );
bb_int_t BBCALL bbColorRed(  );
bb_int_t BBCALL bbColorGreen(  );
bb_int_t BBCALL bbColorBlue(  );
void BBCALL bbClsColor( bb_int_t red,bb_int_t green,bb_int_t blue );
void BBCALL bbCls(  );
void BBCALL bbPlot( bb_int_t x,bb_int_t y );
void BBCALL bbRect( bb_int_t x,bb_int_t y,bb_int_t width,bb_int_t height,bb_int_t solid );
void BBCALL bbOval( bb_int_t x,bb_int_t y,bb_int_t width,bb_int_t height,bb_int_t solid );
void BBCALL bbLine( bb_int_t x1,bb_int_t y1,bb_int_t x2,bb_int_t y2 );
void BBCALL bbText( bb_int_t x,bb_int_t y,BBStr *text,bb_int_t centre_x,bb_int_t centre_y );

//fonts
BBFont * BBCALL bbLoadFont( BBStr *fontname,bb_int_t height,bb_int_t bold,bb_int_t italic,bb_int_t underline );
void BBCALL bbFreeFont( BBFont *font );
void BBCALL bbSetFont( BBFont *font );
bb_int_t BBCALL bbFontWidth(  );
bb_int_t BBCALL bbFontHeight(  );
bb_int_t BBCALL bbStringWidth( BBStr *string );
bb_int_t BBCALL bbStringHeight( BBStr *string );

//movies
BBMovie * BBCALL bbOpenMovie( BBStr *file );
bb_int_t BBCALL bbDrawMovie( BBMovie *movie,bb_int_t x,bb_int_t y,bb_int_t w,bb_int_t h );
bb_int_t BBCALL bbMovieWidth( BBMovie *movie );
bb_int_t BBCALL bbMovieHeight( BBMovie *movie );
bb_int_t BBCALL bbMoviePlaying( BBMovie *movie );
void BBCALL bbCloseMovie( BBMovie *movie );

#ifdef __cplusplus
}
#endif


#endif
