// AUTOGENERATED. DO NOT EDIT.
// RUN `bin/blitz3d config` TO UPDATE.

#include <bb/blitz/module.h>
#include <bb/blitz2d/blitz2d.h>

#ifdef WIN32
BBMODULE_LINK( blitz2d ){
	rtSym( "CloseMovie%movie",bbCloseMovie );
	rtSym( "Cls",bbCls );
	rtSym( "ClsColor%red%green%blue",bbClsColor );
	rtSym( "Color%red%green%blue",bbColor );
	rtSym( "%ColorBlue",bbColorBlue );
	rtSym( "%ColorGreen",bbColorGreen );
	rtSym( "%ColorRed",bbColorRed );
	rtSym( "%DrawMovie%movie%x=0%y=0%w=-1%h=-1",bbDrawMovie );
	rtSym( "%FontHeight",bbFontHeight );
	rtSym( "%FontWidth",bbFontWidth );
	rtSym( "FreeFont%font",bbFreeFont );
	rtSym( "GetColor%x%y",bbGetColor );
	rtSym( "Line%x1%y1%x2%y2",bbLine );
	rtSym( "%LoadFont$fontname%height=12%bold=0%italic=0%underline=0",bbLoadFont );
	rtSym( "%MovieHeight%movie",bbMovieHeight );
	rtSym( "%MoviePlaying%movie",bbMoviePlaying );
	rtSym( "%MovieWidth%movie",bbMovieWidth );
	rtSym( "%OpenMovie$file",bbOpenMovie );
	rtSym( "Origin%x%y",bbOrigin );
	rtSym( "Oval%x%y%width%height%solid=1",bbOval );
	rtSym( "Plot%x%y",bbPlot );
	rtSym( "Rect%x%y%width%height%solid=1",bbRect );
	rtSym( "SetFont%font",bbSetFont );
	rtSym( "%StringHeight$string",bbStringHeight );
	rtSym( "%StringWidth$string",bbStringWidth );
	rtSym( "Text%x%y$text%centre_x=0%centre_y=0",bbText );
	rtSym( "Viewport%x%y%width%height",bbViewport );
}
#endif
