#ifndef BB_AUDIO_COMMANDS_H
#define BB_AUDIO_COMMANDS_H

#include <bb/blitz/module.h>
#include <bb/audio/audio.h>

#ifdef __cplusplus
extern "C" {
#endif

// AUTOGENERATED. DO NOT EDIT.
// RUN `make` TO UPDATE.
BBSound * BBCALL bbLoadSound( BBStr *filename );
BBSound * BBCALL bbLoad3DSound( BBStr *filename );
void BBCALL bbFreeSound( BBSound *sound );
void BBCALL bbLoopSound( BBSound *sound );
void BBCALL bbSoundPitch( BBSound *sound,bb_int_t pitch );
void BBCALL bbSoundVolume( BBSound *sound,bb_float_t volume );
void BBCALL bbSoundPan( BBSound *sound,bb_float_t pan );
BBChannel * BBCALL bbPlaySound( BBSound *sound );
BBChannel * BBCALL bbPlayMusic( BBStr *filename );
BBChannel * BBCALL bbPlayCDTrack( bb_int_t track,bb_int_t mode );
void BBCALL bbStopChannel( BBChannel *channel );
void BBCALL bbPauseChannel( BBChannel *channel );
void BBCALL bbResumeChannel( BBChannel *channel );
void BBCALL bbChannelPitch( BBChannel *channel,bb_int_t pitch );
void BBCALL bbChannelVolume( BBChannel *channel,bb_float_t volume );
void BBCALL bbChannelPan( BBChannel *channel,bb_float_t pan );
bb_int_t BBCALL bbChannelPlaying( BBChannel *channel );

#ifdef __cplusplus
}
#endif


#endif
