// AUTOGENERATED. DO NOT EDIT.
// RUN `bin/blitz3d config` TO UPDATE.

#include <bb/blitz/module.h>
#include <bb/userlibs/userlibs.h>

BBMODULE_LINK( userlibs ){
	rtSym( "_bbCStrToStr",_bbCStrToStr );
	rtSym( "_bbLoadLibs",_bbLoadLibs );
	rtSym( "_bbStrToCStr",_bbStrToCStr );
}
