// AUTOGENERATED. DO NOT EDIT.
// RUN `make` TO UPDATE.

#include <bb/blitz/module.h>
#include <bb/userlibs/userlibs.h>

BBMODULE_LINK( userlibs ){
	rtSym( "_bbLoadLibs",_bbLoadLibs );
	rtSym( "_bbStrToCStr",_bbStrToCStr );
	rtSym( "_bbCStrToStr",_bbCStrToStr );
}
