require 'assimp.convertutf'

project "assimp"
  language "C++"
  kind "StaticLib"

  removeplatforms { "win32", "win64", "mingw32" }

  defines {
    "ASSIMP_BUILD_NO_OWN_ZLIB",

    -- TODO: once the ASSIMP loader code is solid, we can disable a bunch of these
    -- "ASSIMP_BUILD_NO_MAKELEFTHANDED_PROCESS",
    -- "ASSIMP_BUILD_NO_FLIPUVS_PROCESS",
    -- "ASSIMP_BUILD_NO_FLIPWINDINGORDER_PROCESS",
    -- "ASSIMP_BUILD_NO_REMOVEVC_PROCESS",
    -- "ASSIMP_BUILD_NO_REMOVE_REDUNDANTMATERIALS_PROCESS",
    -- "ASSIMP_BUILD_NO_FINDINSTANCES_PROCESS",
    -- "ASSIMP_BUILD_NO_OPTIMIZEGRAPH_PROCESS",
    -- "ASSIMP_BUILD_NO_FINDDEGENERATES_PROCESS",
    -- "ASSIMP_BUILD_NO_GENUVCOORDS_PROCESS",
    -- "ASSIMP_BUILD_NO_TRANSFORMTEXCOORDS_PROCESS",
    -- "ASSIMP_BUILD_NO_PRETRANSFORMVERTICES_PROCESS",
    -- "ASSIMP_BUILD_NO_TRIANGULATE_PROCESS",
    -- "ASSIMP_BUILD_NO_SORTBYPTYPE_PROCESS",
    -- "ASSIMP_BUILD_NO_FINDINVALIDDATA_PROCESS",
    -- "ASSIMP_BUILD_NO_OPTIMIZEMESHES_PROCESS",
    -- "ASSIMP_BUILD_NO_FIXINFACINGNORMALS_PROCESS",
    -- "ASSIMP_BUILD_NO_SPLITBYBONECOUNT_PROCESS",
    -- "ASSIMP_BUILD_NO_SPLITLARGEMESHES_PROCESS",
    -- "ASSIMP_BUILD_NO_GENFACENORMALS_PROCESS",
    -- "ASSIMP_BUILD_NO_GENVERTEXNORMALS_PROCESS",
    -- "ASSIMP_BUILD_NO_CALCTANGENTS_PROCESS",
    -- "ASSIMP_BUILD_NO_JOINVERTICES_PROCESS",
    -- "ASSIMP_BUILD_NO_SPLITLARGEMESHES_PROCESS",
    -- "ASSIMP_BUILD_NO_DEBONE_PROCESS",
    -- "ASSIMP_BUILD_NO_LIMITBONEWEIGHTS_PROCESS",
    -- "ASSIMP_BUILD_NO_IMPROVECACHELOCALITY_PROCESS",

    -- "ASSIMP_BUILD_NO_X_IMPORTER",
    "ASSIMP_BUILD_NO_3DS_IMPORTER",
    "ASSIMP_BUILD_NO_MD3_IMPORTER",
    "ASSIMP_BUILD_NO_MDL_IMPORTER",
    "ASSIMP_BUILD_NO_MD2_IMPORTER",
    "ASSIMP_BUILD_NO_PLY_IMPORTER",
    "ASSIMP_BUILD_NO_ASE_IMPORTER",
    "ASSIMP_BUILD_NO_OBJ_IMPORTER",
    "ASSIMP_BUILD_NO_HMP_IMPORTER",
    "ASSIMP_BUILD_NO_SMD_IMPORTER",
    "ASSIMP_BUILD_NO_MDC_IMPORTER",
    "ASSIMP_BUILD_NO_MD5_IMPORTER",
    "ASSIMP_BUILD_NO_STL_IMPORTER",
    "ASSIMP_BUILD_NO_LWO_IMPORTER",
    "ASSIMP_BUILD_NO_DXF_IMPORTER",
    "ASSIMP_BUILD_NO_NFF_IMPORTER",
    "ASSIMP_BUILD_NO_RAW_IMPORTER",
    "ASSIMP_BUILD_NO_SIB_IMPORTER",
    "ASSIMP_BUILD_NO_OFF_IMPORTER",
    "ASSIMP_BUILD_NO_AC_IMPORTER",
    "ASSIMP_BUILD_NO_BVH_IMPORTER",
    "ASSIMP_BUILD_NO_IRRMESH_IMPORTER",
    "ASSIMP_BUILD_NO_IRR_IMPORTER",
    "ASSIMP_BUILD_NO_Q3D_IMPORTER",
    "ASSIMP_BUILD_NO_B3D_IMPORTER",
    "ASSIMP_BUILD_NO_COLLADA_IMPORTER",
    "ASSIMP_BUILD_NO_TERRAGEN_IMPORTER",
    "ASSIMP_BUILD_NO_CSM_IMPORTER",
    "ASSIMP_BUILD_NO_3D_IMPORTER",
    "ASSIMP_BUILD_NO_LWS_IMPORTER",
    "ASSIMP_BUILD_NO_OGRE_IMPORTER",
    "ASSIMP_BUILD_NO_OPENGEX_IMPORTER",
    "ASSIMP_BUILD_NO_MS3D_IMPORTER",
    "ASSIMP_BUILD_NO_COB_IMPORTER",
    "ASSIMP_BUILD_NO_BLEND_IMPORTER",
    "ASSIMP_BUILD_NO_Q3BSP_IMPORTER",
    "ASSIMP_BUILD_NO_NDO_IMPORTER",
    "ASSIMP_BUILD_NO_IFC_IMPORTER",
    "ASSIMP_BUILD_NO_XGL_IMPORTER",
    "ASSIMP_BUILD_NO_FBX_IMPORTER",
    "ASSIMP_BUILD_NO_ASSBIN_IMPORTER",
    "ASSIMP_BUILD_NO_GLTF_IMPORTER",
    "ASSIMP_BUILD_NO_C4D_IMPORTER",
    "ASSIMP_BUILD_NO_3MF_IMPORTER"
  }

  includedirs {
    "assimp/include",
    "assimp.include"
  }

  links "assimp.convertutf"

  files {
    "assimp/code/Assimp.cpp",
    "assimp/code/BaseImporter.h",
    "assimp/code/BaseImporter.cpp",
    "assimp/code/BaseProcess.h",
    "assimp/code/BaseProcess.cpp",
    "assimp/code/CalcTangentsProcess.cpp",
    "assimp/code/CalcTangentsProcess.h",
    "assimp/code/ConvertToLHProcess.h",
    "assimp/code/ConvertToLHProcess.cpp",
    "assimp/code/ComputeUVMappingProcess.cpp",
    "assimp/code/ComputeUVMappingProcess.h",
    "assimp/code/DeboneProcess.cpp",
    "assimp/code/DeboneProcess.h",
    "assimp/code/DefaultIOStream.h",
    "assimp/code/DefaultIOStream.cpp",
    "assimp/code/DefaultIOSystem.h",
    "assimp/code/DefaultIOSystem.cpp",
    "assimp/code/DefaultLogger.h",
    "assimp/code/DefaultLogger.cpp",
    "assimp/code/FindDegenerates.cpp",
    "assimp/code/FindDegenerates.h",
    "assimp/code/FindInstancesProcess.cpp",
    "assimp/code/FindInstancesProcess.h",
    "assimp/code/FindInvalidDataProcess.cpp",
    "assimp/code/FindInvalidDataProcess.h",
    "assimp/code/FixNormalsStep.cpp",
    "assimp/code/FixNormalsStep.h",
    "assimp/code/GenFaceNormalsProcess.cpp",
    "assimp/code/GenFaceNormalsProcess.h",
    "assimp/code/GenVertexNormalsProcess.cpp",
    "assimp/code/GenVertexNormalsProcess.h",
    "assimp/code/Importer.h",
    "assimp/code/Importer.cpp",
    "assimp/code/ImporterRegistry.h",
    "assimp/code/ImporterRegistry.cpp",
    "assimp/code/ImproveCacheLocality.cpp",
    "assimp/code/ImproveCacheLocality.h",
    "assimp/code/JoinVerticesProcess.cpp",
    "assimp/code/JoinVerticesProcess.h",
    "assimp/code/LimitBoneWeightsProcess.cpp",
    "assimp/code/LimitBoneWeightsProcess.h",
    "assimp/code/MaterialSystem.h",
    "assimp/code/MaterialSystem.cpp",
    "assimp/code/OptimizeGraph.cpp",
    "assimp/code/OptimizeGraph.h",
    "assimp/code/OptimizeMeshes.cpp",
    "assimp/code/OptimizeMeshes.h",
    "assimp/code/PostStepRegistry.h",
    "assimp/code/PostStepRegistry.cpp",
    "assimp/code/PretransformVertices.cpp",
    "assimp/code/PretransformVertices.h",
    "assimp/code/ProcessHelper.h",
    "assimp/code/ProcessHelper.cpp",
    "assimp/code/RemoveVCProcess.cpp",
    "assimp/code/RemoveVCProcess.h",
    "assimp/code/RemoveRedundantMaterials.cpp",
    "assimp/code/RemoveRedundantMaterials.h",
    "assimp/code/SceneCombiner.h",
    "assimp/code/SceneCombiner.cpp",
    "assimp/code/ScenePreprocessor.h",
    "assimp/code/ScenePreprocessor.cpp",
    "assimp/code/SortByPTypeProcess.cpp",
    "assimp/code/SortByPTypeProcess.h",
    "assimp/code/SpatialSort.h",
    "assimp/code/SpatialSort.cpp",
    "assimp/code/SplitByBoneCountProcess.cpp",
    "assimp/code/SplitByBoneCountProcess.h",
    "assimp/code/SplitLargeMeshes.cpp",
    "assimp/code/SplitLargeMeshes.h",
    "assimp/code/TextureTransform.cpp",
    "assimp/code/TextureTransform.h",
    "assimp/code/TriangulateProcess.cpp",
    "assimp/code/TriangulateProcess.h",
    "assimp/code/ValidateDataStructure.h",
    "assimp/code/ValidateDataStructure.cpp",
    "assimp/code/Version.cpp",
    "assimp/code/VertexTriangleAdjacency.h",
    "assimp/code/VertexTriangleAdjacency.cpp",

    "assimp/code/XFileHelper.h",
    "assimp/code/XFileImporter.cpp",
    "assimp/code/XFileImporter.h",
    "assimp/code/XFileParser.cpp",
    "assimp/code/XFileParser.h",
  }
