##
# Uncomment for LLVM build. TODO: make this better.

# set(LLVM_ROOT ${PROJECT_SOURCE_DIR}/_release/toolchains/macos/llvm)
#
# set(CMAKE_C_COMPILER ${LLVM_ROOT}/bin/clang)
# set(CMAKE_CXX_COMPILER ${LLVM_ROOT}/bin/clang++)
# set(CMAKE_OBJC_COMPILER ${LLVM_ROOT}/bin/clang++)

# set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
# set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
# set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
# set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
