#ifndef BB_MULTIPLAY_ENET_COMMANDS_H
#define BB_MULTIPLAY_ENET_COMMANDS_H

#include <bb/blitz/module.h>
#include <bb/multiplay.enet/multiplay.enet.h>

#ifdef __cplusplus
extern "C" {
#endif

// AUTOGENERATED. DO NOT EDIT.
// RUN `make` TO UPDATE.

//StartNetGame%():"bbStartNetGame"
bb_int_t BBCALL bbHostNetGame( BBStr *game_name );
bb_int_t BBCALL bbJoinNetGame( BBStr *game_name,BBStr *ip_address );

//StopNetGame():"bbStopNetGame"
BBPlayer * BBCALL bbCreateNetPlayer( BBStr *name );

//DeleteNetPlayer( player.BBPlayer ):"bbDeleteNetPlayer"

//NetPlayerName$( player.BBPlayer ):"bbNetPlayerName"

//NetPlayerLocal%( player.BBPlayer ):"bbNetPlayerLocal"
bb_int_t BBCALL bbSendNetMsg( bb_int_t type,BBStr *msg,BBPlayer *from_player,BBPlayer *to_player,bb_int_t reliable );
bb_int_t BBCALL bbRecvNetMsg(  );
bb_int_t BBCALL bbNetMsgType(  );
BBPlayer * BBCALL bbNetMsgFrom(  );
BBPlayer * BBCALL bbNetMsgTo(  );
BBStr * BBCALL bbNetMsgData(  );

#ifdef __cplusplus
}
#endif


#endif
