// AUTOGENERATED. DO NOT EDIT.
// RUN `ruby src/bindings/luajit/generate.rb` TO UPDATE.

#include <bb/audio/commands.h>

#if defined(BB_WIN32) || defined(BB_WIN64) || defined(BB_MINGW32) || defined(BB_MACOS) || defined(BB_LINUX) || defined(BB_IOS) || defined(BB_ANDROID) || defined(BB_EMSCRIPTEN) || defined(BB_NX)
#define BB_AUDIO_ENABLED

static int l_audio_ChannelPan( lua_State *L ){
  bb_int_t __channel = luaL_checknumber( L,1 );
  bb_float_t __pan = luaL_checknumber( L,2 );
  bbChannelPan( __channel,__pan );
  return 0;
}

static int l_audio_ChannelPitch( lua_State *L ){
  bb_int_t __channel = luaL_checknumber( L,1 );
  bb_int_t __pitch = luaL_checknumber( L,2 );
  bbChannelPitch( __channel,__pitch );
  return 0;
}

static int l_audio_ChannelPlaying( lua_State *L ){
  bb_int_t __channel = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)bbChannelPlaying( __channel ) );
  return 1;
}

static int l_audio_ChannelVolume( lua_State *L ){
  bb_int_t __channel = luaL_checknumber( L,1 );
  bb_float_t __volume = luaL_checknumber( L,2 );
  bbChannelVolume( __channel,__volume );
  return 0;
}

static int l_audio_FreeSound( lua_State *L ){
  bb_int_t __sound = luaL_checknumber( L,1 );
  bbFreeSound( __sound );
  return 0;
}

static int l_audio_Load3DSound( lua_State *L ){
  BBStr * __filename = _bbStrConst( luaL_checkstring( L,1 ) );
  lua_pushnumber( L,(bb_int_t)bbLoad3DSound( __filename ) );
  return 1;
}

static int l_audio_LoadSound( lua_State *L ){
  BBStr * __filename = _bbStrConst( luaL_checkstring( L,1 ) );
  lua_pushnumber( L,(bb_int_t)bbLoadSound( __filename ) );
  return 1;
}

static int l_audio_LoopSound( lua_State *L ){
  bb_int_t __sound = luaL_checknumber( L,1 );
  bbLoopSound( __sound );
  return 0;
}

static int l_audio_PauseChannel( lua_State *L ){
  bb_int_t __channel = luaL_checknumber( L,1 );
  bbPauseChannel( __channel );
  return 0;
}

static int l_audio_PlayCDTrack( lua_State *L ){
  bb_int_t __track = luaL_checknumber( L,1 );
  bb_int_t __mode;
  if( lua_gettop( L ) > 1 ){
    __mode = luaL_checknumber( L,2 );
  }else{
   __mode = 1;
  }
  lua_pushnumber( L,(bb_int_t)bbPlayCDTrack( __track,__mode ) );
  return 1;
}

static int l_audio_PlayMusic( lua_State *L ){
  BBStr * __filename = _bbStrConst( luaL_checkstring( L,1 ) );
  lua_pushnumber( L,(bb_int_t)bbPlayMusic( __filename ) );
  return 1;
}

static int l_audio_PlaySound( lua_State *L ){
  bb_int_t __sound = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)bbPlaySound( __sound ) );
  return 1;
}

static int l_audio_ResumeChannel( lua_State *L ){
  bb_int_t __channel = luaL_checknumber( L,1 );
  bbResumeChannel( __channel );
  return 0;
}

static int l_audio_SoundPan( lua_State *L ){
  bb_int_t __sound = luaL_checknumber( L,1 );
  bb_float_t __pan = luaL_checknumber( L,2 );
  bbSoundPan( __sound,__pan );
  return 0;
}

static int l_audio_SoundPitch( lua_State *L ){
  bb_int_t __sound = luaL_checknumber( L,1 );
  bb_int_t __pitch = luaL_checknumber( L,2 );
  bbSoundPitch( __sound,__pitch );
  return 0;
}

static int l_audio_SoundVolume( lua_State *L ){
  bb_int_t __sound = luaL_checknumber( L,1 );
  bb_float_t __volume = luaL_checknumber( L,2 );
  bbSoundVolume( __sound,__volume );
  return 0;
}

static int l_audio_StopChannel( lua_State *L ){
  bb_int_t __channel = luaL_checknumber( L,1 );
  bbStopChannel( __channel );
  return 0;
}

#endif
