// AUTOGENERATED. DO NOT EDIT.
// RUN `ruby src/bindings/luajit/generate.rb` TO UPDATE.

#include <bb/blitz3d/commands.h>

#if defined(BB_WIN32) || defined(BB_WIN64) || defined(BB_MINGW32) || defined(BB_MACOS) || defined(BB_LINUX) || defined(BB_IOS) || defined(BB_ANDROID) || defined(BB_EMSCRIPTEN)
#define BB_BLITZ3D_ENABLED

static int l_blitz3d_ActiveTextures( lua_State *L ){
  lua_pushnumber( L,(bb_int_t)bbActiveTextures(  ) );
  return 1;
}

static int l_blitz3d_AddAnimSeq( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_int_t __length = luaL_checknumber( L,2 );
  lua_pushnumber( L,(bb_int_t)bbAddAnimSeq( __entity,__length ) );
  return 1;
}

static int l_blitz3d_AddMesh( lua_State *L ){
  bb_int_t __source_mesh = luaL_checknumber( L,1 );
  bb_int_t __dest_mesh = luaL_checknumber( L,2 );
  bbAddMesh( __source_mesh,__dest_mesh );
  return 0;
}

static int l_blitz3d_AddTriangle( lua_State *L ){
  bb_int_t __surface = luaL_checknumber( L,1 );
  bb_int_t __v0 = luaL_checknumber( L,2 );
  bb_int_t __v1 = luaL_checknumber( L,3 );
  bb_int_t __v2 = luaL_checknumber( L,4 );
  lua_pushnumber( L,(bb_int_t)bbAddTriangle( __surface,__v0,__v1,__v2 ) );
  return 1;
}

static int l_blitz3d_AddVertex( lua_State *L ){
  bb_int_t __surface = luaL_checknumber( L,1 );
  bb_float_t __x = luaL_checknumber( L,2 );
  bb_float_t __y = luaL_checknumber( L,3 );
  bb_float_t __z = luaL_checknumber( L,4 );
  bb_float_t __u;
  if( lua_gettop( L ) > 4 ){
    __u = luaL_checknumber( L,5 );
  }else{
   __u = 0;
  }
  bb_float_t __v;
  if( lua_gettop( L ) > 5 ){
    __v = luaL_checknumber( L,6 );
  }else{
   __v = 0;
  }
  bb_float_t __w;
  if( lua_gettop( L ) > 6 ){
    __w = luaL_checknumber( L,7 );
  }else{
   __w = 1;
  }
  lua_pushnumber( L,(bb_int_t)bbAddVertex( __surface,__x,__y,__z,__u,__v,__w ) );
  return 1;
}

static int l_blitz3d_AlignToVector( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_float_t __vector_x = luaL_checknumber( L,2 );
  bb_float_t __vector_y = luaL_checknumber( L,3 );
  bb_float_t __vector_z = luaL_checknumber( L,4 );
  bb_int_t __axis = luaL_checknumber( L,5 );
  bb_float_t __rate;
  if( lua_gettop( L ) > 5 ){
    __rate = luaL_checknumber( L,6 );
  }else{
   __rate = 1;
  }
  bbAlignToVector( __entity,__vector_x,__vector_y,__vector_z,__axis,__rate );
  return 0;
}

static int l_blitz3d_AmbientLight( lua_State *L ){
  bb_float_t __red = luaL_checknumber( L,1 );
  bb_float_t __green = luaL_checknumber( L,2 );
  bb_float_t __blue = luaL_checknumber( L,3 );
  bbAmbientLight( __red,__green,__blue );
  return 0;
}

static int l_blitz3d_AnimLength( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)bbAnimLength( __entity ) );
  return 1;
}

static int l_blitz3d_AnimSeq( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)bbAnimSeq( __entity ) );
  return 1;
}

static int l_blitz3d_AnimTime( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_float_t)bbAnimTime( __entity ) );
  return 1;
}

static int l_blitz3d_Animate( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_int_t __mode;
  if( lua_gettop( L ) > 1 ){
    __mode = luaL_checknumber( L,2 );
  }else{
   __mode = 1;
  }
  bb_float_t __speed;
  if( lua_gettop( L ) > 2 ){
    __speed = luaL_checknumber( L,3 );
  }else{
   __speed = 1;
  }
  bb_int_t __sequence;
  if( lua_gettop( L ) > 3 ){
    __sequence = luaL_checknumber( L,4 );
  }else{
   __sequence = 0;
  }
  bb_float_t __transition;
  if( lua_gettop( L ) > 4 ){
    __transition = luaL_checknumber( L,5 );
  }else{
   __transition = 0;
  }
  bbAnimate( __entity,__mode,__speed,__sequence,__transition );
  return 0;
}

static int l_blitz3d_AnimateMD2( lua_State *L ){
  bb_int_t __md2 = luaL_checknumber( L,1 );
  bb_int_t __mode;
  if( lua_gettop( L ) > 1 ){
    __mode = luaL_checknumber( L,2 );
  }else{
   __mode = 1;
  }
  bb_float_t __speed;
  if( lua_gettop( L ) > 2 ){
    __speed = luaL_checknumber( L,3 );
  }else{
   __speed = 1;
  }
  bb_int_t __first_frame;
  if( lua_gettop( L ) > 3 ){
    __first_frame = luaL_checknumber( L,4 );
  }else{
   __first_frame = 0;
  }
  bb_int_t __last_frame;
  if( lua_gettop( L ) > 4 ){
    __last_frame = luaL_checknumber( L,5 );
  }else{
   __last_frame = 9999;
  }
  bb_float_t __transition;
  if( lua_gettop( L ) > 5 ){
    __transition = luaL_checknumber( L,6 );
  }else{
   __transition = 0;
  }
  bbAnimateMD2( __md2,__mode,__speed,__first_frame,__last_frame,__transition );
  return 0;
}

static int l_blitz3d_Animating( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)bbAnimating( __entity ) );
  return 1;
}

static int l_blitz3d_AntiAlias( lua_State *L ){
  bb_int_t __enable = luaL_checknumber( L,1 );
  bbAntiAlias( __enable );
  return 0;
}

static int l_blitz3d_BSPAmbientLight( lua_State *L ){
  bb_int_t __bsp = luaL_checknumber( L,1 );
  bb_float_t __red = luaL_checknumber( L,2 );
  bb_float_t __green = luaL_checknumber( L,3 );
  bb_float_t __blue = luaL_checknumber( L,4 );
  bbBSPAmbientLight( __bsp,__red,__green,__blue );
  return 0;
}

static int l_blitz3d_BSPLighting( lua_State *L ){
  bb_int_t __bsp = luaL_checknumber( L,1 );
  bb_int_t __use_lightmaps = luaL_checknumber( L,2 );
  bbBSPLighting( __bsp,__use_lightmaps );
  return 0;
}

static int l_blitz3d_BrushAlpha( lua_State *L ){
  bb_int_t __brush = luaL_checknumber( L,1 );
  bb_float_t __alpha = luaL_checknumber( L,2 );
  bbBrushAlpha( __brush,__alpha );
  return 0;
}

static int l_blitz3d_BrushBlend( lua_State *L ){
  bb_int_t __brush = luaL_checknumber( L,1 );
  bb_int_t __blend = luaL_checknumber( L,2 );
  bbBrushBlend( __brush,__blend );
  return 0;
}

static int l_blitz3d_BrushColor( lua_State *L ){
  bb_int_t __brush = luaL_checknumber( L,1 );
  bb_float_t __red = luaL_checknumber( L,2 );
  bb_float_t __green = luaL_checknumber( L,3 );
  bb_float_t __blue = luaL_checknumber( L,4 );
  bbBrushColor( __brush,__red,__green,__blue );
  return 0;
}

static int l_blitz3d_BrushFX( lua_State *L ){
  bb_int_t __brush = luaL_checknumber( L,1 );
  bb_int_t __fx = luaL_checknumber( L,2 );
  bbBrushFX( __brush,__fx );
  return 0;
}

static int l_blitz3d_BrushShininess( lua_State *L ){
  bb_int_t __brush = luaL_checknumber( L,1 );
  bb_float_t __shininess = luaL_checknumber( L,2 );
  bbBrushShininess( __brush,__shininess );
  return 0;
}

static int l_blitz3d_BrushTexture( lua_State *L ){
  bb_int_t __brush = luaL_checknumber( L,1 );
  bb_int_t __texture = luaL_checknumber( L,2 );
  bb_int_t __frame;
  if( lua_gettop( L ) > 2 ){
    __frame = luaL_checknumber( L,3 );
  }else{
   __frame = 0;
  }
  bb_int_t __index;
  if( lua_gettop( L ) > 3 ){
    __index = luaL_checknumber( L,4 );
  }else{
   __index = 0;
  }
  bbBrushTexture( __brush,__texture,__frame,__index );
  return 0;
}

static int l_blitz3d_CameraClsColor( lua_State *L ){
  bb_int_t __camera = luaL_checknumber( L,1 );
  bb_float_t __red = luaL_checknumber( L,2 );
  bb_float_t __green = luaL_checknumber( L,3 );
  bb_float_t __blue = luaL_checknumber( L,4 );
  bbCameraClsColor( __camera,__red,__green,__blue );
  return 0;
}

static int l_blitz3d_CameraClsMode( lua_State *L ){
  bb_int_t __camera = luaL_checknumber( L,1 );
  bb_int_t __cls_color = luaL_checknumber( L,2 );
  bb_int_t __cls_zbuffer = luaL_checknumber( L,3 );
  bbCameraClsMode( __camera,__cls_color,__cls_zbuffer );
  return 0;
}

static int l_blitz3d_CameraFogColor( lua_State *L ){
  bb_int_t __camera = luaL_checknumber( L,1 );
  bb_float_t __red = luaL_checknumber( L,2 );
  bb_float_t __green = luaL_checknumber( L,3 );
  bb_float_t __blue = luaL_checknumber( L,4 );
  bbCameraFogColor( __camera,__red,__green,__blue );
  return 0;
}

static int l_blitz3d_CameraFogMode( lua_State *L ){
  bb_int_t __camera = luaL_checknumber( L,1 );
  bb_int_t __mode = luaL_checknumber( L,2 );
  bbCameraFogMode( __camera,__mode );
  return 0;
}

static int l_blitz3d_CameraFogRange( lua_State *L ){
  bb_int_t __camera = luaL_checknumber( L,1 );
  bb_float_t __near = luaL_checknumber( L,2 );
  bb_float_t __far = luaL_checknumber( L,3 );
  bbCameraFogRange( __camera,__near,__far );
  return 0;
}

static int l_blitz3d_CameraPick( lua_State *L ){
  bb_int_t __camera = luaL_checknumber( L,1 );
  bb_float_t __viewport_x = luaL_checknumber( L,2 );
  bb_float_t __viewport_y = luaL_checknumber( L,3 );
  lua_pushnumber( L,(bb_int_t)bbCameraPick( __camera,__viewport_x,__viewport_y ) );
  return 1;
}

static int l_blitz3d_CameraProjMode( lua_State *L ){
  bb_int_t __camera = luaL_checknumber( L,1 );
  bb_int_t __mode = luaL_checknumber( L,2 );
  bbCameraProjMode( __camera,__mode );
  return 0;
}

static int l_blitz3d_CameraProject( lua_State *L ){
  bb_int_t __camera = luaL_checknumber( L,1 );
  bb_float_t __x = luaL_checknumber( L,2 );
  bb_float_t __y = luaL_checknumber( L,3 );
  bb_float_t __z = luaL_checknumber( L,4 );
  bbCameraProject( __camera,__x,__y,__z );
  return 0;
}

static int l_blitz3d_CameraRange( lua_State *L ){
  bb_int_t __camera = luaL_checknumber( L,1 );
  bb_float_t __near = luaL_checknumber( L,2 );
  bb_float_t __far = luaL_checknumber( L,3 );
  bbCameraRange( __camera,__near,__far );
  return 0;
}

static int l_blitz3d_CameraViewport( lua_State *L ){
  bb_int_t __camera = luaL_checknumber( L,1 );
  bb_int_t __x = luaL_checknumber( L,2 );
  bb_int_t __y = luaL_checknumber( L,3 );
  bb_int_t __width = luaL_checknumber( L,4 );
  bb_int_t __height = luaL_checknumber( L,5 );
  bbCameraViewport( __camera,__x,__y,__width,__height );
  return 0;
}

static int l_blitz3d_CameraZoom( lua_State *L ){
  bb_int_t __camera = luaL_checknumber( L,1 );
  bb_float_t __zoom = luaL_checknumber( L,2 );
  bbCameraZoom( __camera,__zoom );
  return 0;
}

static int l_blitz3d_CaptureWorld( lua_State *L ){
  bbCaptureWorld(  );
  return 0;
}

static int l_blitz3d_ClearCollisions( lua_State *L ){
  bbClearCollisions(  );
  return 0;
}

static int l_blitz3d_ClearSurface( lua_State *L ){
  bb_int_t __surface = luaL_checknumber( L,1 );
  bb_int_t __clear_vertices;
  if( lua_gettop( L ) > 1 ){
    __clear_vertices = luaL_checknumber( L,2 );
  }else{
   __clear_vertices = 1;
  }
  bb_int_t __clear_triangles;
  if( lua_gettop( L ) > 2 ){
    __clear_triangles = luaL_checknumber( L,3 );
  }else{
   __clear_triangles = 1;
  }
  bbClearSurface( __surface,__clear_vertices,__clear_triangles );
  return 0;
}

static int l_blitz3d_ClearTextureFilters( lua_State *L ){
  bbClearTextureFilters(  );
  return 0;
}

static int l_blitz3d_ClearWorld( lua_State *L ){
  bb_int_t __entities;
  if( lua_gettop( L ) > 0 ){
    __entities = luaL_checknumber( L,1 );
  }else{
   __entities = 1;
  }
  bb_int_t __brushes;
  if( lua_gettop( L ) > 1 ){
    __brushes = luaL_checknumber( L,2 );
  }else{
   __brushes = 1;
  }
  bb_int_t __textures;
  if( lua_gettop( L ) > 2 ){
    __textures = luaL_checknumber( L,3 );
  }else{
   __textures = 1;
  }
  bbClearWorld( __entities,__brushes,__textures );
  return 0;
}

static int l_blitz3d_CollisionEntity( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_int_t __collision_index = luaL_checknumber( L,2 );
  lua_pushnumber( L,(bb_int_t)bbCollisionEntity( __entity,__collision_index ) );
  return 1;
}

static int l_blitz3d_CollisionNX( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_int_t __collision_index = luaL_checknumber( L,2 );
  lua_pushnumber( L,(bb_float_t)bbCollisionNX( __entity,__collision_index ) );
  return 1;
}

static int l_blitz3d_CollisionNY( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_int_t __collision_index = luaL_checknumber( L,2 );
  lua_pushnumber( L,(bb_float_t)bbCollisionNY( __entity,__collision_index ) );
  return 1;
}

static int l_blitz3d_CollisionNZ( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_int_t __collision_index = luaL_checknumber( L,2 );
  lua_pushnumber( L,(bb_float_t)bbCollisionNZ( __entity,__collision_index ) );
  return 1;
}

static int l_blitz3d_CollisionSurface( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_int_t __collision_index = luaL_checknumber( L,2 );
  lua_pushnumber( L,(bb_int_t)bbCollisionSurface( __entity,__collision_index ) );
  return 1;
}

static int l_blitz3d_CollisionTime( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_int_t __collision_index = luaL_checknumber( L,2 );
  lua_pushnumber( L,(bb_float_t)bbCollisionTime( __entity,__collision_index ) );
  return 1;
}

static int l_blitz3d_CollisionTriangle( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_int_t __collision_index = luaL_checknumber( L,2 );
  lua_pushnumber( L,(bb_int_t)bbCollisionTriangle( __entity,__collision_index ) );
  return 1;
}

static int l_blitz3d_CollisionX( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_int_t __collision_index = luaL_checknumber( L,2 );
  lua_pushnumber( L,(bb_float_t)bbCollisionX( __entity,__collision_index ) );
  return 1;
}

static int l_blitz3d_CollisionY( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_int_t __collision_index = luaL_checknumber( L,2 );
  lua_pushnumber( L,(bb_float_t)bbCollisionY( __entity,__collision_index ) );
  return 1;
}

static int l_blitz3d_CollisionZ( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_int_t __collision_index = luaL_checknumber( L,2 );
  lua_pushnumber( L,(bb_float_t)bbCollisionZ( __entity,__collision_index ) );
  return 1;
}

static int l_blitz3d_Collisions( lua_State *L ){
  bb_int_t __source_type = luaL_checknumber( L,1 );
  bb_int_t __destination_type = luaL_checknumber( L,2 );
  bb_int_t __method = luaL_checknumber( L,3 );
  bb_int_t __response = luaL_checknumber( L,4 );
  bbCollisions( __source_type,__destination_type,__method,__response );
  return 0;
}

static int l_blitz3d_CopyEntity( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_int_t __parent;
  if( lua_gettop( L ) > 1 ){
    __parent = luaL_checknumber( L,2 );
  }else{
   __parent = 0;
  }
  lua_pushnumber( L,(bb_int_t)bbCopyEntity( __entity,__parent ) );
  return 1;
}

static int l_blitz3d_CopyMesh( lua_State *L ){
  bb_int_t __mesh = luaL_checknumber( L,1 );
  bb_int_t __parent;
  if( lua_gettop( L ) > 1 ){
    __parent = luaL_checknumber( L,2 );
  }else{
   __parent = 0;
  }
  lua_pushnumber( L,(bb_int_t)bbCopyMesh( __mesh,__parent ) );
  return 1;
}

static int l_blitz3d_CountChildren( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)bbCountChildren( __entity ) );
  return 1;
}

static int l_blitz3d_CountCollisions( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)bbCountCollisions( __entity ) );
  return 1;
}

static int l_blitz3d_CountSurfaces( lua_State *L ){
  bb_int_t __mesh = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)bbCountSurfaces( __mesh ) );
  return 1;
}

static int l_blitz3d_CountTriangles( lua_State *L ){
  bb_int_t __surface = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)bbCountTriangles( __surface ) );
  return 1;
}

static int l_blitz3d_CountVertices( lua_State *L ){
  bb_int_t __surface = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)bbCountVertices( __surface ) );
  return 1;
}

static int l_blitz3d_CreateBrush( lua_State *L ){
  bb_float_t __red;
  if( lua_gettop( L ) > 0 ){
    __red = luaL_checknumber( L,1 );
  }else{
   __red = 255;
  }
  bb_float_t __green;
  if( lua_gettop( L ) > 1 ){
    __green = luaL_checknumber( L,2 );
  }else{
   __green = 255;
  }
  bb_float_t __blue;
  if( lua_gettop( L ) > 2 ){
    __blue = luaL_checknumber( L,3 );
  }else{
   __blue = 255;
  }
  lua_pushnumber( L,(bb_int_t)bbCreateBrush( __red,__green,__blue ) );
  return 1;
}

static int l_blitz3d_CreateCamera( lua_State *L ){
  bb_int_t __parent;
  if( lua_gettop( L ) > 0 ){
    __parent = luaL_checknumber( L,1 );
  }else{
   __parent = 0;
  }
  lua_pushnumber( L,(bb_int_t)bbCreateCamera( __parent ) );
  return 1;
}

static int l_blitz3d_CreateCone( lua_State *L ){
  bb_int_t __segments;
  if( lua_gettop( L ) > 0 ){
    __segments = luaL_checknumber( L,1 );
  }else{
   __segments = 8;
  }
  bb_int_t __solid;
  if( lua_gettop( L ) > 1 ){
    __solid = luaL_checknumber( L,2 );
  }else{
   __solid = 1;
  }
  bb_int_t __parent;
  if( lua_gettop( L ) > 2 ){
    __parent = luaL_checknumber( L,3 );
  }else{
   __parent = 0;
  }
  lua_pushnumber( L,(bb_int_t)bbCreateCone( __segments,__solid,__parent ) );
  return 1;
}

static int l_blitz3d_CreateCube( lua_State *L ){
  bb_int_t __parent;
  if( lua_gettop( L ) > 0 ){
    __parent = luaL_checknumber( L,1 );
  }else{
   __parent = 0;
  }
  lua_pushnumber( L,(bb_int_t)bbCreateCube( __parent ) );
  return 1;
}

static int l_blitz3d_CreateCylinder( lua_State *L ){
  bb_int_t __segments;
  if( lua_gettop( L ) > 0 ){
    __segments = luaL_checknumber( L,1 );
  }else{
   __segments = 8;
  }
  bb_int_t __solid;
  if( lua_gettop( L ) > 1 ){
    __solid = luaL_checknumber( L,2 );
  }else{
   __solid = 1;
  }
  bb_int_t __parent;
  if( lua_gettop( L ) > 2 ){
    __parent = luaL_checknumber( L,3 );
  }else{
   __parent = 0;
  }
  lua_pushnumber( L,(bb_int_t)bbCreateCylinder( __segments,__solid,__parent ) );
  return 1;
}

static int l_blitz3d_CreateLight( lua_State *L ){
  bb_int_t __type;
  if( lua_gettop( L ) > 0 ){
    __type = luaL_checknumber( L,1 );
  }else{
   __type = 1;
  }
  bb_int_t __parent;
  if( lua_gettop( L ) > 1 ){
    __parent = luaL_checknumber( L,2 );
  }else{
   __parent = 0;
  }
  lua_pushnumber( L,(bb_int_t)bbCreateLight( __type,__parent ) );
  return 1;
}

static int l_blitz3d_CreateListener( lua_State *L ){
  bb_int_t __parent = luaL_checknumber( L,1 );
  bb_float_t __rolloff_factor;
  if( lua_gettop( L ) > 1 ){
    __rolloff_factor = luaL_checknumber( L,2 );
  }else{
   __rolloff_factor = 1;
  }
  bb_float_t __doppler_scale;
  if( lua_gettop( L ) > 2 ){
    __doppler_scale = luaL_checknumber( L,3 );
  }else{
   __doppler_scale = 1;
  }
  bb_float_t __distance_scale;
  if( lua_gettop( L ) > 3 ){
    __distance_scale = luaL_checknumber( L,4 );
  }else{
   __distance_scale = 1;
  }
  lua_pushnumber( L,(bb_int_t)bbCreateListener( __parent,__rolloff_factor,__doppler_scale,__distance_scale ) );
  return 1;
}

static int l_blitz3d_CreateMesh( lua_State *L ){
  bb_int_t __parent;
  if( lua_gettop( L ) > 0 ){
    __parent = luaL_checknumber( L,1 );
  }else{
   __parent = 0;
  }
  lua_pushnumber( L,(bb_int_t)bbCreateMesh( __parent ) );
  return 1;
}

static int l_blitz3d_CreateMirror( lua_State *L ){
  bb_int_t __parent;
  if( lua_gettop( L ) > 0 ){
    __parent = luaL_checknumber( L,1 );
  }else{
   __parent = 0;
  }
  lua_pushnumber( L,(bb_int_t)bbCreateMirror( __parent ) );
  return 1;
}

static int l_blitz3d_CreatePivot( lua_State *L ){
  bb_int_t __parent;
  if( lua_gettop( L ) > 0 ){
    __parent = luaL_checknumber( L,1 );
  }else{
   __parent = 0;
  }
  lua_pushnumber( L,(bb_int_t)bbCreatePivot( __parent ) );
  return 1;
}

static int l_blitz3d_CreatePlane( lua_State *L ){
  bb_int_t __segments;
  if( lua_gettop( L ) > 0 ){
    __segments = luaL_checknumber( L,1 );
  }else{
   __segments = 1;
  }
  bb_int_t __parent;
  if( lua_gettop( L ) > 1 ){
    __parent = luaL_checknumber( L,2 );
  }else{
   __parent = 0;
  }
  lua_pushnumber( L,(bb_int_t)bbCreatePlane( __segments,__parent ) );
  return 1;
}

static int l_blitz3d_CreateSphere( lua_State *L ){
  bb_int_t __segments;
  if( lua_gettop( L ) > 0 ){
    __segments = luaL_checknumber( L,1 );
  }else{
   __segments = 8;
  }
  bb_int_t __parent;
  if( lua_gettop( L ) > 1 ){
    __parent = luaL_checknumber( L,2 );
  }else{
   __parent = 0;
  }
  lua_pushnumber( L,(bb_int_t)bbCreateSphere( __segments,__parent ) );
  return 1;
}

static int l_blitz3d_CreateSprite( lua_State *L ){
  bb_int_t __parent;
  if( lua_gettop( L ) > 0 ){
    __parent = luaL_checknumber( L,1 );
  }else{
   __parent = 0;
  }
  lua_pushnumber( L,(bb_int_t)bbCreateSprite( __parent ) );
  return 1;
}

static int l_blitz3d_CreateSurface( lua_State *L ){
  bb_int_t __mesh = luaL_checknumber( L,1 );
  bb_int_t __brush;
  if( lua_gettop( L ) > 1 ){
    __brush = luaL_checknumber( L,2 );
  }else{
   __brush = 0;
  }
  lua_pushnumber( L,(bb_int_t)bbCreateSurface( __mesh,__brush ) );
  return 1;
}

static int l_blitz3d_CreateTerrain( lua_State *L ){
  bb_int_t __grid_size = luaL_checknumber( L,1 );
  bb_int_t __parent;
  if( lua_gettop( L ) > 1 ){
    __parent = luaL_checknumber( L,2 );
  }else{
   __parent = 0;
  }
  lua_pushnumber( L,(bb_int_t)bbCreateTerrain( __grid_size,__parent ) );
  return 1;
}

static int l_blitz3d_CreateTexture( lua_State *L ){
  bb_int_t __width = luaL_checknumber( L,1 );
  bb_int_t __height = luaL_checknumber( L,2 );
  bb_int_t __flags;
  if( lua_gettop( L ) > 2 ){
    __flags = luaL_checknumber( L,3 );
  }else{
   __flags = 0;
  }
  bb_int_t __frames;
  if( lua_gettop( L ) > 3 ){
    __frames = luaL_checknumber( L,4 );
  }else{
   __frames = 1;
  }
  lua_pushnumber( L,(bb_int_t)bbCreateTexture( __width,__height,__flags,__frames ) );
  return 1;
}

static int l_blitz3d_DeltaPitch( lua_State *L ){
  bb_int_t __src_entity = luaL_checknumber( L,1 );
  bb_int_t __dest_entity = luaL_checknumber( L,2 );
  lua_pushnumber( L,(bb_float_t)bbDeltaPitch( __src_entity,__dest_entity ) );
  return 1;
}

static int l_blitz3d_DeltaYaw( lua_State *L ){
  bb_int_t __src_entity = luaL_checknumber( L,1 );
  bb_int_t __dest_entity = luaL_checknumber( L,2 );
  lua_pushnumber( L,(bb_float_t)bbDeltaYaw( __src_entity,__dest_entity ) );
  return 1;
}

static int l_blitz3d_Dither( lua_State *L ){
  bb_int_t __enable = luaL_checknumber( L,1 );
  bbDither( __enable );
  return 0;
}

static int l_blitz3d_EmitSound( lua_State *L ){
  bb_int_t __sound = luaL_checknumber( L,1 );
  bb_int_t __entity = luaL_checknumber( L,2 );
  lua_pushnumber( L,(bb_int_t)bbEmitSound( __sound,__entity ) );
  return 1;
}

static int l_blitz3d_EntityAlpha( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_float_t __alpha = luaL_checknumber( L,2 );
  bbEntityAlpha( __entity,__alpha );
  return 0;
}

static int l_blitz3d_EntityAutoFade( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_float_t __near = luaL_checknumber( L,2 );
  bb_float_t __far = luaL_checknumber( L,3 );
  bbEntityAutoFade( __entity,__near,__far );
  return 0;
}

static int l_blitz3d_EntityBlend( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_int_t __blend = luaL_checknumber( L,2 );
  bbEntityBlend( __entity,__blend );
  return 0;
}

static int l_blitz3d_EntityBox( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_float_t __x = luaL_checknumber( L,2 );
  bb_float_t __y = luaL_checknumber( L,3 );
  bb_float_t __z = luaL_checknumber( L,4 );
  bb_float_t __width = luaL_checknumber( L,5 );
  bb_float_t __height = luaL_checknumber( L,6 );
  bb_float_t __depth = luaL_checknumber( L,7 );
  bbEntityBox( __entity,__x,__y,__z,__width,__height,__depth );
  return 0;
}

static int l_blitz3d_EntityClass( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  lua_pushstring( L,bbEntityClass( __entity ) );
  return 1;
}

static int l_blitz3d_EntityCollided( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_int_t __type = luaL_checknumber( L,2 );
  lua_pushnumber( L,(bb_int_t)bbEntityCollided( __entity,__type ) );
  return 1;
}

static int l_blitz3d_EntityColor( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_float_t __red = luaL_checknumber( L,2 );
  bb_float_t __green = luaL_checknumber( L,3 );
  bb_float_t __blue = luaL_checknumber( L,4 );
  bbEntityColor( __entity,__red,__green,__blue );
  return 0;
}

static int l_blitz3d_EntityDistance( lua_State *L ){
  bb_int_t __source_entity = luaL_checknumber( L,1 );
  bb_int_t __destination_entity = luaL_checknumber( L,2 );
  lua_pushnumber( L,(bb_float_t)bbEntityDistance( __source_entity,__destination_entity ) );
  return 1;
}

static int l_blitz3d_EntityFX( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_int_t __fx = luaL_checknumber( L,2 );
  bbEntityFX( __entity,__fx );
  return 0;
}

static int l_blitz3d_EntityInView( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_int_t __camera = luaL_checknumber( L,2 );
  lua_pushnumber( L,(bb_int_t)bbEntityInView( __entity,__camera ) );
  return 1;
}

static int l_blitz3d_EntityName( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  lua_pushstring( L,bbEntityName( __entity ) );
  return 1;
}

static int l_blitz3d_EntityOrder( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_int_t __order = luaL_checknumber( L,2 );
  bbEntityOrder( __entity,__order );
  return 0;
}

static int l_blitz3d_EntityParent( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_int_t __parent = luaL_checknumber( L,2 );
  bb_int_t __global;
  if( lua_gettop( L ) > 2 ){
    __global = luaL_checknumber( L,3 );
  }else{
   __global = 1;
  }
  bbEntityParent( __entity,__parent,__global );
  return 0;
}

static int l_blitz3d_EntityPick( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_float_t __range = luaL_checknumber( L,2 );
  lua_pushnumber( L,(bb_int_t)bbEntityPick( __entity,__range ) );
  return 1;
}

static int l_blitz3d_EntityPickMode( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_int_t __pick_geometry = luaL_checknumber( L,2 );
  bb_int_t __obscurer;
  if( lua_gettop( L ) > 2 ){
    __obscurer = luaL_checknumber( L,3 );
  }else{
   __obscurer = 1;
  }
  bbEntityPickMode( __entity,__pick_geometry,__obscurer );
  return 0;
}

static int l_blitz3d_EntityPitch( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_int_t __global;
  if( lua_gettop( L ) > 1 ){
    __global = luaL_checknumber( L,2 );
  }else{
   __global = 0;
  }
  lua_pushnumber( L,(bb_float_t)bbEntityPitch( __entity,__global ) );
  return 1;
}

static int l_blitz3d_EntityRadius( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_float_t __x_radius = luaL_checknumber( L,2 );
  bb_float_t __y_radius;
  if( lua_gettop( L ) > 2 ){
    __y_radius = luaL_checknumber( L,3 );
  }else{
   __y_radius = 0;
  }
  bbEntityRadius( __entity,__x_radius,__y_radius );
  return 0;
}

static int l_blitz3d_EntityRoll( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_int_t __global;
  if( lua_gettop( L ) > 1 ){
    __global = luaL_checknumber( L,2 );
  }else{
   __global = 0;
  }
  lua_pushnumber( L,(bb_float_t)bbEntityRoll( __entity,__global ) );
  return 1;
}

static int l_blitz3d_EntityShininess( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_float_t __shininess = luaL_checknumber( L,2 );
  bbEntityShininess( __entity,__shininess );
  return 0;
}

static int l_blitz3d_EntityTexture( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_int_t __texture = luaL_checknumber( L,2 );
  bb_int_t __frame;
  if( lua_gettop( L ) > 2 ){
    __frame = luaL_checknumber( L,3 );
  }else{
   __frame = 0;
  }
  bb_int_t __index;
  if( lua_gettop( L ) > 3 ){
    __index = luaL_checknumber( L,4 );
  }else{
   __index = 0;
  }
  bbEntityTexture( __entity,__texture,__frame,__index );
  return 0;
}

static int l_blitz3d_EntityType( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_int_t __collision_type = luaL_checknumber( L,2 );
  bb_int_t __recursive;
  if( lua_gettop( L ) > 2 ){
    __recursive = luaL_checknumber( L,3 );
  }else{
   __recursive = 0;
  }
  bbEntityType( __entity,__collision_type,__recursive );
  return 0;
}

static int l_blitz3d_EntityVisible( lua_State *L ){
  bb_int_t __src_entity = luaL_checknumber( L,1 );
  bb_int_t __dest_entity = luaL_checknumber( L,2 );
  lua_pushnumber( L,(bb_int_t)bbEntityVisible( __src_entity,__dest_entity ) );
  return 1;
}

static int l_blitz3d_EntityX( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_int_t __global;
  if( lua_gettop( L ) > 1 ){
    __global = luaL_checknumber( L,2 );
  }else{
   __global = 0;
  }
  lua_pushnumber( L,(bb_float_t)bbEntityX( __entity,__global ) );
  return 1;
}

static int l_blitz3d_EntityY( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_int_t __global;
  if( lua_gettop( L ) > 1 ){
    __global = luaL_checknumber( L,2 );
  }else{
   __global = 0;
  }
  lua_pushnumber( L,(bb_float_t)bbEntityY( __entity,__global ) );
  return 1;
}

static int l_blitz3d_EntityYaw( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_int_t __global;
  if( lua_gettop( L ) > 1 ){
    __global = luaL_checknumber( L,2 );
  }else{
   __global = 0;
  }
  lua_pushnumber( L,(bb_float_t)bbEntityYaw( __entity,__global ) );
  return 1;
}

static int l_blitz3d_EntityZ( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_int_t __global;
  if( lua_gettop( L ) > 1 ){
    __global = luaL_checknumber( L,2 );
  }else{
   __global = 0;
  }
  lua_pushnumber( L,(bb_float_t)bbEntityZ( __entity,__global ) );
  return 1;
}

static int l_blitz3d_ExtractAnimSeq( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_int_t __first_frame = luaL_checknumber( L,2 );
  bb_int_t __last_frame = luaL_checknumber( L,3 );
  bb_int_t __anim_seq;
  if( lua_gettop( L ) > 3 ){
    __anim_seq = luaL_checknumber( L,4 );
  }else{
   __anim_seq = 0;
  }
  lua_pushnumber( L,(bb_int_t)bbExtractAnimSeq( __entity,__first_frame,__last_frame,__anim_seq ) );
  return 1;
}

static int l_blitz3d_FindChild( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  BBStr * __name = _bbStrConst( luaL_checkstring( L,2 ) );
  lua_pushnumber( L,(bb_int_t)bbFindChild( __entity,__name ) );
  return 1;
}

static int l_blitz3d_FindSurface( lua_State *L ){
  bb_int_t __mesh = luaL_checknumber( L,1 );
  bb_int_t __brush = luaL_checknumber( L,2 );
  lua_pushnumber( L,(bb_int_t)bbFindSurface( __mesh,__brush ) );
  return 1;
}

static int l_blitz3d_FitMesh( lua_State *L ){
  bb_int_t __mesh = luaL_checknumber( L,1 );
  bb_float_t __x = luaL_checknumber( L,2 );
  bb_float_t __y = luaL_checknumber( L,3 );
  bb_float_t __z = luaL_checknumber( L,4 );
  bb_float_t __width = luaL_checknumber( L,5 );
  bb_float_t __height = luaL_checknumber( L,6 );
  bb_float_t __depth = luaL_checknumber( L,7 );
  bb_int_t __uniform;
  if( lua_gettop( L ) > 7 ){
    __uniform = luaL_checknumber( L,8 );
  }else{
   __uniform = 0;
  }
  bbFitMesh( __mesh,__x,__y,__z,__width,__height,__depth,__uniform );
  return 0;
}

static int l_blitz3d_FlipMesh( lua_State *L ){
  bb_int_t __mesh = luaL_checknumber( L,1 );
  bbFlipMesh( __mesh );
  return 0;
}

static int l_blitz3d_FreeBrush( lua_State *L ){
  bb_int_t __brush = luaL_checknumber( L,1 );
  bbFreeBrush( __brush );
  return 0;
}

static int l_blitz3d_FreeEntity( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bbFreeEntity( __entity );
  return 0;
}

static int l_blitz3d_FreeTexture( lua_State *L ){
  bb_int_t __texture = luaL_checknumber( L,1 );
  bbFreeTexture( __texture );
  return 0;
}

static int l_blitz3d_GetBrushAlpha( lua_State *L ){
  bb_int_t __brush = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_float_t)bbGetBrushAlpha( __brush ) );
  return 1;
}

static int l_blitz3d_GetBrushBlend( lua_State *L ){
  bb_int_t __brush = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)bbGetBrushBlend( __brush ) );
  return 1;
}

static int l_blitz3d_GetBrushBlue( lua_State *L ){
  bb_int_t __brush = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)bbGetBrushBlue( __brush ) );
  return 1;
}

static int l_blitz3d_GetBrushFX( lua_State *L ){
  bb_int_t __brush = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)bbGetBrushFX( __brush ) );
  return 1;
}

static int l_blitz3d_GetBrushGreen( lua_State *L ){
  bb_int_t __brush = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)bbGetBrushGreen( __brush ) );
  return 1;
}

static int l_blitz3d_GetBrushRed( lua_State *L ){
  bb_int_t __brush = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)bbGetBrushRed( __brush ) );
  return 1;
}

static int l_blitz3d_GetBrushShininess( lua_State *L ){
  bb_int_t __brush = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_float_t)bbGetBrushShininess( __brush ) );
  return 1;
}

static int l_blitz3d_GetBrushTexture( lua_State *L ){
  bb_int_t __brush = luaL_checknumber( L,1 );
  bb_int_t __index;
  if( lua_gettop( L ) > 1 ){
    __index = luaL_checknumber( L,2 );
  }else{
   __index = 0;
  }
  lua_pushnumber( L,(bb_int_t)bbGetBrushTexture( __brush,__index ) );
  return 1;
}

static int l_blitz3d_GetChild( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_int_t __index = luaL_checknumber( L,2 );
  lua_pushnumber( L,(bb_int_t)bbGetChild( __entity,__index ) );
  return 1;
}

static int l_blitz3d_GetEntityBrush( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)bbGetEntityBrush( __entity ) );
  return 1;
}

static int l_blitz3d_GetEntityType( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)bbGetEntityType( __entity ) );
  return 1;
}

static int l_blitz3d_GetMatElement( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_int_t __row = luaL_checknumber( L,2 );
  bb_int_t __column = luaL_checknumber( L,3 );
  lua_pushnumber( L,(bb_float_t)bbGetMatElement( __entity,__row,__column ) );
  return 1;
}

static int l_blitz3d_GetParent( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)bbGetParent( __entity ) );
  return 1;
}

static int l_blitz3d_GetSurface( lua_State *L ){
  bb_int_t __mesh = luaL_checknumber( L,1 );
  bb_int_t __surface_index = luaL_checknumber( L,2 );
  lua_pushnumber( L,(bb_int_t)bbGetSurface( __mesh,__surface_index ) );
  return 1;
}

static int l_blitz3d_GetSurfaceBrush( lua_State *L ){
  bb_int_t __surface = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)bbGetSurfaceBrush( __surface ) );
  return 1;
}

static int l_blitz3d_GfxDriverCaps3D( lua_State *L ){
  lua_pushnumber( L,(bb_int_t)bbGfxDriverCaps3D(  ) );
  return 1;
}

static int l_blitz3d_HWMultiTex( lua_State *L ){
  bb_int_t __enable = luaL_checknumber( L,1 );
  bbHWMultiTex( __enable );
  return 0;
}

static int l_blitz3d_HWTexUnits( lua_State *L ){
  lua_pushnumber( L,(bb_int_t)bbHWTexUnits(  ) );
  return 1;
}

static int l_blitz3d_HandleSprite( lua_State *L ){
  bb_int_t __sprite = luaL_checknumber( L,1 );
  bb_float_t __x_handle = luaL_checknumber( L,2 );
  bb_float_t __y_handle = luaL_checknumber( L,3 );
  bbHandleSprite( __sprite,__x_handle,__y_handle );
  return 0;
}

static int l_blitz3d_HideEntity( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bbHideEntity( __entity );
  return 0;
}

static int l_blitz3d_LightColor( lua_State *L ){
  bb_int_t __light = luaL_checknumber( L,1 );
  bb_float_t __red = luaL_checknumber( L,2 );
  bb_float_t __green = luaL_checknumber( L,3 );
  bb_float_t __blue = luaL_checknumber( L,4 );
  bbLightColor( __light,__red,__green,__blue );
  return 0;
}

static int l_blitz3d_LightConeAngles( lua_State *L ){
  bb_int_t __light = luaL_checknumber( L,1 );
  bb_float_t __inner_angle = luaL_checknumber( L,2 );
  bb_float_t __outer_angle = luaL_checknumber( L,3 );
  bbLightConeAngles( __light,__inner_angle,__outer_angle );
  return 0;
}

static int l_blitz3d_LightMesh( lua_State *L ){
  bb_int_t __mesh = luaL_checknumber( L,1 );
  bb_float_t __red = luaL_checknumber( L,2 );
  bb_float_t __green = luaL_checknumber( L,3 );
  bb_float_t __blue = luaL_checknumber( L,4 );
  bb_float_t __range;
  if( lua_gettop( L ) > 4 ){
    __range = luaL_checknumber( L,5 );
  }else{
   __range = 0;
  }
  bb_float_t __x;
  if( lua_gettop( L ) > 5 ){
    __x = luaL_checknumber( L,6 );
  }else{
   __x = 0;
  }
  bb_float_t __y;
  if( lua_gettop( L ) > 6 ){
    __y = luaL_checknumber( L,7 );
  }else{
   __y = 0;
  }
  bb_float_t __z;
  if( lua_gettop( L ) > 7 ){
    __z = luaL_checknumber( L,8 );
  }else{
   __z = 0;
  }
  bbLightMesh( __mesh,__red,__green,__blue,__range,__x,__y,__z );
  return 0;
}

static int l_blitz3d_LightRange( lua_State *L ){
  bb_int_t __light = luaL_checknumber( L,1 );
  bb_float_t __range = luaL_checknumber( L,2 );
  bbLightRange( __light,__range );
  return 0;
}

static int l_blitz3d_LinePick( lua_State *L ){
  bb_float_t __x = luaL_checknumber( L,1 );
  bb_float_t __y = luaL_checknumber( L,2 );
  bb_float_t __z = luaL_checknumber( L,3 );
  bb_float_t __dx = luaL_checknumber( L,4 );
  bb_float_t __dy = luaL_checknumber( L,5 );
  bb_float_t __dz = luaL_checknumber( L,6 );
  bb_float_t __radius;
  if( lua_gettop( L ) > 6 ){
    __radius = luaL_checknumber( L,7 );
  }else{
   __radius = 0;
  }
  lua_pushnumber( L,(bb_int_t)bbLinePick( __x,__y,__z,__dx,__dy,__dz,__radius ) );
  return 1;
}

static int l_blitz3d_LoadAnimMesh( lua_State *L ){
  BBStr * __file = _bbStrConst( luaL_checkstring( L,1 ) );
  bb_int_t __parent;
  if( lua_gettop( L ) > 1 ){
    __parent = luaL_checknumber( L,2 );
  }else{
   __parent = 0;
  }
  lua_pushnumber( L,(bb_int_t)bbLoadAnimMesh( __file,__parent ) );
  return 1;
}

static int l_blitz3d_LoadAnimSeq( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  BBStr * __file = _bbStrConst( luaL_checkstring( L,2 ) );
  lua_pushnumber( L,(bb_int_t)bbLoadAnimSeq( __entity,__file ) );
  return 1;
}

static int l_blitz3d_LoadAnimTexture( lua_State *L ){
  BBStr * __file = _bbStrConst( luaL_checkstring( L,1 ) );
  bb_int_t __flags = luaL_checknumber( L,2 );
  bb_int_t __width = luaL_checknumber( L,3 );
  bb_int_t __height = luaL_checknumber( L,4 );
  bb_int_t __first = luaL_checknumber( L,5 );
  bb_int_t __count = luaL_checknumber( L,6 );
  lua_pushnumber( L,(bb_int_t)bbLoadAnimTexture( __file,__flags,__width,__height,__first,__count ) );
  return 1;
}

static int l_blitz3d_LoadBSP( lua_State *L ){
  BBStr * __file = _bbStrConst( luaL_checkstring( L,1 ) );
  bb_float_t __gamma_adj;
  if( lua_gettop( L ) > 1 ){
    __gamma_adj = luaL_checknumber( L,2 );
  }else{
   __gamma_adj = 0;
  }
  bb_int_t __parent;
  if( lua_gettop( L ) > 2 ){
    __parent = luaL_checknumber( L,3 );
  }else{
   __parent = 0;
  }
  lua_pushnumber( L,(bb_int_t)bbLoadBSP( __file,__gamma_adj,__parent ) );
  return 1;
}

static int l_blitz3d_LoadBrush( lua_State *L ){
  BBStr * __file = _bbStrConst( luaL_checkstring( L,1 ) );
  bb_int_t __texture_flags;
  if( lua_gettop( L ) > 1 ){
    __texture_flags = luaL_checknumber( L,2 );
  }else{
   __texture_flags = 1;
  }
  bb_float_t __u_scale;
  if( lua_gettop( L ) > 2 ){
    __u_scale = luaL_checknumber( L,3 );
  }else{
   __u_scale = 1;
  }
  bb_float_t __v_scale;
  if( lua_gettop( L ) > 3 ){
    __v_scale = luaL_checknumber( L,4 );
  }else{
   __v_scale = 1;
  }
  lua_pushnumber( L,(bb_int_t)bbLoadBrush( __file,__texture_flags,__u_scale,__v_scale ) );
  return 1;
}

static int l_blitz3d_LoadMD2( lua_State *L ){
  BBStr * __file = _bbStrConst( luaL_checkstring( L,1 ) );
  bb_int_t __parent;
  if( lua_gettop( L ) > 1 ){
    __parent = luaL_checknumber( L,2 );
  }else{
   __parent = 0;
  }
  lua_pushnumber( L,(bb_int_t)bbLoadMD2( __file,__parent ) );
  return 1;
}

static int l_blitz3d_LoadMesh( lua_State *L ){
  BBStr * __file = _bbStrConst( luaL_checkstring( L,1 ) );
  bb_int_t __parent;
  if( lua_gettop( L ) > 1 ){
    __parent = luaL_checknumber( L,2 );
  }else{
   __parent = 0;
  }
  lua_pushnumber( L,(bb_int_t)bbLoadMesh( __file,__parent ) );
  return 1;
}

static int l_blitz3d_LoadSprite( lua_State *L ){
  BBStr * __file = _bbStrConst( luaL_checkstring( L,1 ) );
  bb_int_t __texture_flags;
  if( lua_gettop( L ) > 1 ){
    __texture_flags = luaL_checknumber( L,2 );
  }else{
   __texture_flags = 1;
  }
  bb_int_t __parent;
  if( lua_gettop( L ) > 2 ){
    __parent = luaL_checknumber( L,3 );
  }else{
   __parent = 0;
  }
  lua_pushnumber( L,(bb_int_t)bbLoadSprite( __file,__texture_flags,__parent ) );
  return 1;
}

static int l_blitz3d_LoadTerrain( lua_State *L ){
  BBStr * __heightmap_file = _bbStrConst( luaL_checkstring( L,1 ) );
  bb_int_t __parent;
  if( lua_gettop( L ) > 1 ){
    __parent = luaL_checknumber( L,2 );
  }else{
   __parent = 0;
  }
  lua_pushnumber( L,(bb_int_t)bbLoadTerrain( __heightmap_file,__parent ) );
  return 1;
}

static int l_blitz3d_LoadTexture( lua_State *L ){
  BBStr * __file = _bbStrConst( luaL_checkstring( L,1 ) );
  bb_int_t __flags;
  if( lua_gettop( L ) > 1 ){
    __flags = luaL_checknumber( L,2 );
  }else{
   __flags = 1;
  }
  lua_pushnumber( L,(bb_int_t)bbLoadTexture( __file,__flags ) );
  return 1;
}

static int l_blitz3d_LoaderMatrix( lua_State *L ){
  BBStr * __file_ext = _bbStrConst( luaL_checkstring( L,1 ) );
  bb_float_t __xx = luaL_checknumber( L,2 );
  bb_float_t __xy = luaL_checknumber( L,3 );
  bb_float_t __xz = luaL_checknumber( L,4 );
  bb_float_t __yx = luaL_checknumber( L,5 );
  bb_float_t __yy = luaL_checknumber( L,6 );
  bb_float_t __yz = luaL_checknumber( L,7 );
  bb_float_t __zx = luaL_checknumber( L,8 );
  bb_float_t __zy = luaL_checknumber( L,9 );
  bb_float_t __zz = luaL_checknumber( L,10 );
  bbLoaderMatrix( __file_ext,__xx,__xy,__xz,__yx,__yy,__yz,__zx,__zy,__zz );
  return 0;
}

static int l_blitz3d_MD2AnimLength( lua_State *L ){
  bb_int_t __md2 = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)bbMD2AnimLength( __md2 ) );
  return 1;
}

static int l_blitz3d_MD2AnimTime( lua_State *L ){
  bb_int_t __md2 = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_float_t)bbMD2AnimTime( __md2 ) );
  return 1;
}

static int l_blitz3d_MD2Animating( lua_State *L ){
  bb_int_t __md2 = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)bbMD2Animating( __md2 ) );
  return 1;
}

static int l_blitz3d_MeshCullBox( lua_State *L ){
  bb_int_t __mesh = luaL_checknumber( L,1 );
  bb_float_t __x = luaL_checknumber( L,2 );
  bb_float_t __y = luaL_checknumber( L,3 );
  bb_float_t __z = luaL_checknumber( L,4 );
  bb_float_t __width = luaL_checknumber( L,5 );
  bb_float_t __height = luaL_checknumber( L,6 );
  bb_float_t __depth = luaL_checknumber( L,7 );
  bbMeshCullBox( __mesh,__x,__y,__z,__width,__height,__depth );
  return 0;
}

static int l_blitz3d_MeshDepth( lua_State *L ){
  bb_int_t __mesh = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_float_t)bbMeshDepth( __mesh ) );
  return 1;
}

static int l_blitz3d_MeshHeight( lua_State *L ){
  bb_int_t __mesh = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_float_t)bbMeshHeight( __mesh ) );
  return 1;
}

static int l_blitz3d_MeshWidth( lua_State *L ){
  bb_int_t __mesh = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_float_t)bbMeshWidth( __mesh ) );
  return 1;
}

static int l_blitz3d_MeshesIntersect( lua_State *L ){
  bb_int_t __mesh_a = luaL_checknumber( L,1 );
  bb_int_t __mesh_b = luaL_checknumber( L,2 );
  lua_pushnumber( L,(bb_int_t)bbMeshesIntersect( __mesh_a,__mesh_b ) );
  return 1;
}

static int l_blitz3d_ModifyTerrain( lua_State *L ){
  bb_int_t __terrain = luaL_checknumber( L,1 );
  bb_int_t __terrain_x = luaL_checknumber( L,2 );
  bb_int_t __terrain_z = luaL_checknumber( L,3 );
  bb_float_t __height = luaL_checknumber( L,4 );
  bb_int_t __realtime;
  if( lua_gettop( L ) > 4 ){
    __realtime = luaL_checknumber( L,5 );
  }else{
   __realtime = 0;
  }
  bbModifyTerrain( __terrain,__terrain_x,__terrain_z,__height,__realtime );
  return 0;
}

static int l_blitz3d_MoveEntity( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_float_t __x = luaL_checknumber( L,2 );
  bb_float_t __y = luaL_checknumber( L,3 );
  bb_float_t __z = luaL_checknumber( L,4 );
  bbMoveEntity( __entity,__x,__y,__z );
  return 0;
}

static int l_blitz3d_NameEntity( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  BBStr * __name = _bbStrConst( luaL_checkstring( L,2 ) );
  bbNameEntity( __entity,__name );
  return 0;
}

static int l_blitz3d_PaintEntity( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_int_t __brush = luaL_checknumber( L,2 );
  bbPaintEntity( __entity,__brush );
  return 0;
}

static int l_blitz3d_PaintMesh( lua_State *L ){
  bb_int_t __mesh = luaL_checknumber( L,1 );
  bb_int_t __brush = luaL_checknumber( L,2 );
  bbPaintMesh( __mesh,__brush );
  return 0;
}

static int l_blitz3d_PaintSurface( lua_State *L ){
  bb_int_t __surface = luaL_checknumber( L,1 );
  bb_int_t __brush = luaL_checknumber( L,2 );
  bbPaintSurface( __surface,__brush );
  return 0;
}

static int l_blitz3d_PickedEntity( lua_State *L ){
  lua_pushnumber( L,(bb_int_t)bbPickedEntity(  ) );
  return 1;
}

static int l_blitz3d_PickedNX( lua_State *L ){
  lua_pushnumber( L,(bb_float_t)bbPickedNX(  ) );
  return 1;
}

static int l_blitz3d_PickedNY( lua_State *L ){
  lua_pushnumber( L,(bb_float_t)bbPickedNY(  ) );
  return 1;
}

static int l_blitz3d_PickedNZ( lua_State *L ){
  lua_pushnumber( L,(bb_float_t)bbPickedNZ(  ) );
  return 1;
}

static int l_blitz3d_PickedSurface( lua_State *L ){
  lua_pushnumber( L,(bb_int_t)bbPickedSurface(  ) );
  return 1;
}

static int l_blitz3d_PickedTime( lua_State *L ){
  lua_pushnumber( L,(bb_float_t)bbPickedTime(  ) );
  return 1;
}

static int l_blitz3d_PickedTriangle( lua_State *L ){
  lua_pushnumber( L,(bb_int_t)bbPickedTriangle(  ) );
  return 1;
}

static int l_blitz3d_PickedX( lua_State *L ){
  lua_pushnumber( L,(bb_float_t)bbPickedX(  ) );
  return 1;
}

static int l_blitz3d_PickedY( lua_State *L ){
  lua_pushnumber( L,(bb_float_t)bbPickedY(  ) );
  return 1;
}

static int l_blitz3d_PickedZ( lua_State *L ){
  lua_pushnumber( L,(bb_float_t)bbPickedZ(  ) );
  return 1;
}

static int l_blitz3d_PointEntity( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_int_t __target = luaL_checknumber( L,2 );
  bb_float_t __roll;
  if( lua_gettop( L ) > 2 ){
    __roll = luaL_checknumber( L,3 );
  }else{
   __roll = 0;
  }
  bbPointEntity( __entity,__target,__roll );
  return 0;
}

static int l_blitz3d_PositionEntity( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_float_t __x = luaL_checknumber( L,2 );
  bb_float_t __y = luaL_checknumber( L,3 );
  bb_float_t __z = luaL_checknumber( L,4 );
  bb_int_t __global;
  if( lua_gettop( L ) > 4 ){
    __global = luaL_checknumber( L,5 );
  }else{
   __global = 0;
  }
  bbPositionEntity( __entity,__x,__y,__z,__global );
  return 0;
}

static int l_blitz3d_PositionMesh( lua_State *L ){
  bb_int_t __mesh = luaL_checknumber( L,1 );
  bb_float_t __x = luaL_checknumber( L,2 );
  bb_float_t __y = luaL_checknumber( L,3 );
  bb_float_t __z = luaL_checknumber( L,4 );
  bbPositionMesh( __mesh,__x,__y,__z );
  return 0;
}

static int l_blitz3d_PositionTexture( lua_State *L ){
  bb_int_t __texture = luaL_checknumber( L,1 );
  bb_float_t __u_offset = luaL_checknumber( L,2 );
  bb_float_t __v_offset = luaL_checknumber( L,3 );
  bbPositionTexture( __texture,__u_offset,__v_offset );
  return 0;
}

static int l_blitz3d_ProjectedX( lua_State *L ){
  lua_pushnumber( L,(bb_float_t)bbProjectedX(  ) );
  return 1;
}

static int l_blitz3d_ProjectedY( lua_State *L ){
  lua_pushnumber( L,(bb_float_t)bbProjectedY(  ) );
  return 1;
}

static int l_blitz3d_ProjectedZ( lua_State *L ){
  lua_pushnumber( L,(bb_float_t)bbProjectedZ(  ) );
  return 1;
}

static int l_blitz3d_RenderWorld( lua_State *L ){
  bb_float_t __tween;
  if( lua_gettop( L ) > 0 ){
    __tween = luaL_checknumber( L,1 );
  }else{
   __tween = 1;
  }
  bbRenderWorld( __tween );
  return 0;
}

static int l_blitz3d_ResetEntity( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bbResetEntity( __entity );
  return 0;
}

static int l_blitz3d_RotateEntity( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_float_t __pitch = luaL_checknumber( L,2 );
  bb_float_t __yaw = luaL_checknumber( L,3 );
  bb_float_t __roll = luaL_checknumber( L,4 );
  bb_int_t __global;
  if( lua_gettop( L ) > 4 ){
    __global = luaL_checknumber( L,5 );
  }else{
   __global = 0;
  }
  bbRotateEntity( __entity,__pitch,__yaw,__roll,__global );
  return 0;
}

static int l_blitz3d_RotateMesh( lua_State *L ){
  bb_int_t __mesh = luaL_checknumber( L,1 );
  bb_float_t __pitch = luaL_checknumber( L,2 );
  bb_float_t __yaw = luaL_checknumber( L,3 );
  bb_float_t __roll = luaL_checknumber( L,4 );
  bbRotateMesh( __mesh,__pitch,__yaw,__roll );
  return 0;
}

static int l_blitz3d_RotateSprite( lua_State *L ){
  bb_int_t __sprite = luaL_checknumber( L,1 );
  bb_float_t __angle = luaL_checknumber( L,2 );
  bbRotateSprite( __sprite,__angle );
  return 0;
}

static int l_blitz3d_RotateTexture( lua_State *L ){
  bb_int_t __texture = luaL_checknumber( L,1 );
  bb_float_t __angle = luaL_checknumber( L,2 );
  bbRotateTexture( __texture,__angle );
  return 0;
}

static int l_blitz3d_ScaleEntity( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_float_t __x_scale = luaL_checknumber( L,2 );
  bb_float_t __y_scale = luaL_checknumber( L,3 );
  bb_float_t __z_scale = luaL_checknumber( L,4 );
  bb_int_t __global;
  if( lua_gettop( L ) > 4 ){
    __global = luaL_checknumber( L,5 );
  }else{
   __global = 0;
  }
  bbScaleEntity( __entity,__x_scale,__y_scale,__z_scale,__global );
  return 0;
}

static int l_blitz3d_ScaleMesh( lua_State *L ){
  bb_int_t __mesh = luaL_checknumber( L,1 );
  bb_float_t __x_scale = luaL_checknumber( L,2 );
  bb_float_t __y_scale = luaL_checknumber( L,3 );
  bb_float_t __z_scale = luaL_checknumber( L,4 );
  bbScaleMesh( __mesh,__x_scale,__y_scale,__z_scale );
  return 0;
}

static int l_blitz3d_ScaleSprite( lua_State *L ){
  bb_int_t __sprite = luaL_checknumber( L,1 );
  bb_float_t __x_scale = luaL_checknumber( L,2 );
  bb_float_t __y_scale = luaL_checknumber( L,3 );
  bbScaleSprite( __sprite,__x_scale,__y_scale );
  return 0;
}

static int l_blitz3d_ScaleTexture( lua_State *L ){
  bb_int_t __texture = luaL_checknumber( L,1 );
  bb_float_t __u_scale = luaL_checknumber( L,2 );
  bb_float_t __v_scale = luaL_checknumber( L,3 );
  bbScaleTexture( __texture,__u_scale,__v_scale );
  return 0;
}

static int l_blitz3d_SetAnimKey( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_int_t __frame = luaL_checknumber( L,2 );
  bb_int_t __pos_key;
  if( lua_gettop( L ) > 2 ){
    __pos_key = luaL_checknumber( L,3 );
  }else{
   __pos_key = 1;
  }
  bb_int_t __rot_key;
  if( lua_gettop( L ) > 3 ){
    __rot_key = luaL_checknumber( L,4 );
  }else{
   __rot_key = 1;
  }
  bb_int_t __scale_key;
  if( lua_gettop( L ) > 4 ){
    __scale_key = luaL_checknumber( L,5 );
  }else{
   __scale_key = 1;
  }
  bbSetAnimKey( __entity,__frame,__pos_key,__rot_key,__scale_key );
  return 0;
}

static int l_blitz3d_SetAnimTime( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_float_t __time = luaL_checknumber( L,2 );
  bb_int_t __anim_seq;
  if( lua_gettop( L ) > 2 ){
    __anim_seq = luaL_checknumber( L,3 );
  }else{
   __anim_seq = 0;
  }
  bbSetAnimTime( __entity,__time,__anim_seq );
  return 0;
}

static int l_blitz3d_SetCubeFace( lua_State *L ){
  bb_int_t __texture = luaL_checknumber( L,1 );
  bb_int_t __face = luaL_checknumber( L,2 );
  bbSetCubeFace( __texture,__face );
  return 0;
}

static int l_blitz3d_SetCubeMode( lua_State *L ){
  bb_int_t __texture = luaL_checknumber( L,1 );
  bb_int_t __mode = luaL_checknumber( L,2 );
  bbSetCubeMode( __texture,__mode );
  return 0;
}

static int l_blitz3d_ShowEntity( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bbShowEntity( __entity );
  return 0;
}

static int l_blitz3d_SpriteViewMode( lua_State *L ){
  bb_int_t __sprite = luaL_checknumber( L,1 );
  bb_int_t __view_mode = luaL_checknumber( L,2 );
  bbSpriteViewMode( __sprite,__view_mode );
  return 0;
}

static int l_blitz3d_Stats3D( lua_State *L ){
  bb_int_t __type = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_float_t)bbStats3D( __type ) );
  return 1;
}

static int l_blitz3d_TFormNormal( lua_State *L ){
  bb_float_t __x = luaL_checknumber( L,1 );
  bb_float_t __y = luaL_checknumber( L,2 );
  bb_float_t __z = luaL_checknumber( L,3 );
  bb_int_t __source_entity = luaL_checknumber( L,4 );
  bb_int_t __dest_entity = luaL_checknumber( L,5 );
  bbTFormNormal( __x,__y,__z,__source_entity,__dest_entity );
  return 0;
}

static int l_blitz3d_TFormPoint( lua_State *L ){
  bb_float_t __x = luaL_checknumber( L,1 );
  bb_float_t __y = luaL_checknumber( L,2 );
  bb_float_t __z = luaL_checknumber( L,3 );
  bb_int_t __source_entity = luaL_checknumber( L,4 );
  bb_int_t __dest_entity = luaL_checknumber( L,5 );
  bbTFormPoint( __x,__y,__z,__source_entity,__dest_entity );
  return 0;
}

static int l_blitz3d_TFormVector( lua_State *L ){
  bb_float_t __x = luaL_checknumber( L,1 );
  bb_float_t __y = luaL_checknumber( L,2 );
  bb_float_t __z = luaL_checknumber( L,3 );
  bb_int_t __source_entity = luaL_checknumber( L,4 );
  bb_int_t __dest_entity = luaL_checknumber( L,5 );
  bbTFormVector( __x,__y,__z,__source_entity,__dest_entity );
  return 0;
}

static int l_blitz3d_TFormedX( lua_State *L ){
  lua_pushnumber( L,(bb_float_t)bbTFormedX(  ) );
  return 1;
}

static int l_blitz3d_TFormedY( lua_State *L ){
  lua_pushnumber( L,(bb_float_t)bbTFormedY(  ) );
  return 1;
}

static int l_blitz3d_TFormedZ( lua_State *L ){
  lua_pushnumber( L,(bb_float_t)bbTFormedZ(  ) );
  return 1;
}

static int l_blitz3d_TerrainDetail( lua_State *L ){
  bb_int_t __terrain = luaL_checknumber( L,1 );
  bb_int_t __detail_level = luaL_checknumber( L,2 );
  bb_int_t __morph;
  if( lua_gettop( L ) > 2 ){
    __morph = luaL_checknumber( L,3 );
  }else{
   __morph = 0;
  }
  bbTerrainDetail( __terrain,__detail_level,__morph );
  return 0;
}

static int l_blitz3d_TerrainHeight( lua_State *L ){
  bb_int_t __terrain = luaL_checknumber( L,1 );
  bb_int_t __terrain_x = luaL_checknumber( L,2 );
  bb_int_t __terrain_z = luaL_checknumber( L,3 );
  lua_pushnumber( L,(bb_float_t)bbTerrainHeight( __terrain,__terrain_x,__terrain_z ) );
  return 1;
}

static int l_blitz3d_TerrainShading( lua_State *L ){
  bb_int_t __terrain = luaL_checknumber( L,1 );
  bb_int_t __enable = luaL_checknumber( L,2 );
  bbTerrainShading( __terrain,__enable );
  return 0;
}

static int l_blitz3d_TerrainSize( lua_State *L ){
  bb_int_t __terrain = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)bbTerrainSize( __terrain ) );
  return 1;
}

static int l_blitz3d_TerrainX( lua_State *L ){
  bb_int_t __terrain = luaL_checknumber( L,1 );
  bb_float_t __world_x = luaL_checknumber( L,2 );
  bb_float_t __world_y = luaL_checknumber( L,3 );
  bb_float_t __world_z = luaL_checknumber( L,4 );
  lua_pushnumber( L,(bb_float_t)bbTerrainX( __terrain,__world_x,__world_y,__world_z ) );
  return 1;
}

static int l_blitz3d_TerrainY( lua_State *L ){
  bb_int_t __terrain = luaL_checknumber( L,1 );
  bb_float_t __world_x = luaL_checknumber( L,2 );
  bb_float_t __world_y = luaL_checknumber( L,3 );
  bb_float_t __world_z = luaL_checknumber( L,4 );
  lua_pushnumber( L,(bb_float_t)bbTerrainY( __terrain,__world_x,__world_y,__world_z ) );
  return 1;
}

static int l_blitz3d_TerrainZ( lua_State *L ){
  bb_int_t __terrain = luaL_checknumber( L,1 );
  bb_float_t __world_x = luaL_checknumber( L,2 );
  bb_float_t __world_y = luaL_checknumber( L,3 );
  bb_float_t __world_z = luaL_checknumber( L,4 );
  lua_pushnumber( L,(bb_float_t)bbTerrainZ( __terrain,__world_x,__world_y,__world_z ) );
  return 1;
}

static int l_blitz3d_TextureBlend( lua_State *L ){
  bb_int_t __texture = luaL_checknumber( L,1 );
  bb_int_t __blend = luaL_checknumber( L,2 );
  bbTextureBlend( __texture,__blend );
  return 0;
}

static int l_blitz3d_TextureBuffer( lua_State *L ){
  bb_int_t __texture = luaL_checknumber( L,1 );
  bb_int_t __frame;
  if( lua_gettop( L ) > 1 ){
    __frame = luaL_checknumber( L,2 );
  }else{
   __frame = 0;
  }
  lua_pushnumber( L,(bb_int_t)bbTextureBuffer( __texture,__frame ) );
  return 1;
}

static int l_blitz3d_TextureCoords( lua_State *L ){
  bb_int_t __texture = luaL_checknumber( L,1 );
  bb_int_t __coords = luaL_checknumber( L,2 );
  bbTextureCoords( __texture,__coords );
  return 0;
}

static int l_blitz3d_TextureFilter( lua_State *L ){
  BBStr * __match_text = _bbStrConst( luaL_checkstring( L,1 ) );
  bb_int_t __texture_flags;
  if( lua_gettop( L ) > 1 ){
    __texture_flags = luaL_checknumber( L,2 );
  }else{
   __texture_flags = 0;
  }
  bbTextureFilter( __match_text,__texture_flags );
  return 0;
}

static int l_blitz3d_TextureHeight( lua_State *L ){
  bb_int_t __texture = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)bbTextureHeight( __texture ) );
  return 1;
}

static int l_blitz3d_TextureName( lua_State *L ){
  bb_int_t __texture = luaL_checknumber( L,1 );
  lua_pushstring( L,bbTextureName( __texture ) );
  return 1;
}

static int l_blitz3d_TextureWidth( lua_State *L ){
  bb_int_t __texture = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)bbTextureWidth( __texture ) );
  return 1;
}

static int l_blitz3d_TranslateEntity( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_float_t __x = luaL_checknumber( L,2 );
  bb_float_t __y = luaL_checknumber( L,3 );
  bb_float_t __z = luaL_checknumber( L,4 );
  bb_int_t __global;
  if( lua_gettop( L ) > 4 ){
    __global = luaL_checknumber( L,5 );
  }else{
   __global = 0;
  }
  bbTranslateEntity( __entity,__x,__y,__z,__global );
  return 0;
}

static int l_blitz3d_TriangleVertex( lua_State *L ){
  bb_int_t __surface = luaL_checknumber( L,1 );
  bb_int_t __index = luaL_checknumber( L,2 );
  bb_int_t __vertex = luaL_checknumber( L,3 );
  lua_pushnumber( L,(bb_int_t)bbTriangleVertex( __surface,__index,__vertex ) );
  return 1;
}

static int l_blitz3d_TrisRendered( lua_State *L ){
  lua_pushnumber( L,(bb_int_t)bbTrisRendered(  ) );
  return 1;
}

static int l_blitz3d_TurnEntity( lua_State *L ){
  bb_int_t __entity = luaL_checknumber( L,1 );
  bb_float_t __pitch = luaL_checknumber( L,2 );
  bb_float_t __yaw = luaL_checknumber( L,3 );
  bb_float_t __roll = luaL_checknumber( L,4 );
  bb_int_t __global;
  if( lua_gettop( L ) > 4 ){
    __global = luaL_checknumber( L,5 );
  }else{
   __global = 0;
  }
  bbTurnEntity( __entity,__pitch,__yaw,__roll,__global );
  return 0;
}

static int l_blitz3d_UpdateNormals( lua_State *L ){
  bb_int_t __mesh = luaL_checknumber( L,1 );
  bbUpdateNormals( __mesh );
  return 0;
}

static int l_blitz3d_UpdateWorld( lua_State *L ){
  bb_float_t __elapsed_time;
  if( lua_gettop( L ) > 0 ){
    __elapsed_time = luaL_checknumber( L,1 );
  }else{
   __elapsed_time = 1;
  }
  bbUpdateWorld( __elapsed_time );
  return 0;
}

static int l_blitz3d_VectorPitch( lua_State *L ){
  bb_float_t __x = luaL_checknumber( L,1 );
  bb_float_t __y = luaL_checknumber( L,2 );
  bb_float_t __z = luaL_checknumber( L,3 );
  lua_pushnumber( L,(bb_float_t)bbVectorPitch( __x,__y,__z ) );
  return 1;
}

static int l_blitz3d_VectorYaw( lua_State *L ){
  bb_float_t __x = luaL_checknumber( L,1 );
  bb_float_t __y = luaL_checknumber( L,2 );
  bb_float_t __z = luaL_checknumber( L,3 );
  lua_pushnumber( L,(bb_float_t)bbVectorYaw( __x,__y,__z ) );
  return 1;
}

static int l_blitz3d_VertexAlpha( lua_State *L ){
  bb_int_t __surface = luaL_checknumber( L,1 );
  bb_int_t __index = luaL_checknumber( L,2 );
  lua_pushnumber( L,(bb_float_t)bbVertexAlpha( __surface,__index ) );
  return 1;
}

static int l_blitz3d_VertexBlue( lua_State *L ){
  bb_int_t __surface = luaL_checknumber( L,1 );
  bb_int_t __index = luaL_checknumber( L,2 );
  lua_pushnumber( L,(bb_float_t)bbVertexBlue( __surface,__index ) );
  return 1;
}

static int l_blitz3d_VertexColor( lua_State *L ){
  bb_int_t __surface = luaL_checknumber( L,1 );
  bb_int_t __index = luaL_checknumber( L,2 );
  bb_float_t __red = luaL_checknumber( L,3 );
  bb_float_t __green = luaL_checknumber( L,4 );
  bb_float_t __blue = luaL_checknumber( L,5 );
  bb_float_t __alpha;
  if( lua_gettop( L ) > 5 ){
    __alpha = luaL_checknumber( L,6 );
  }else{
   __alpha = 1;
  }
  bbVertexColor( __surface,__index,__red,__green,__blue,__alpha );
  return 0;
}

static int l_blitz3d_VertexCoords( lua_State *L ){
  bb_int_t __surface = luaL_checknumber( L,1 );
  bb_int_t __index = luaL_checknumber( L,2 );
  bb_float_t __x = luaL_checknumber( L,3 );
  bb_float_t __y = luaL_checknumber( L,4 );
  bb_float_t __z = luaL_checknumber( L,5 );
  bbVertexCoords( __surface,__index,__x,__y,__z );
  return 0;
}

static int l_blitz3d_VertexGreen( lua_State *L ){
  bb_int_t __surface = luaL_checknumber( L,1 );
  bb_int_t __index = luaL_checknumber( L,2 );
  lua_pushnumber( L,(bb_float_t)bbVertexGreen( __surface,__index ) );
  return 1;
}

static int l_blitz3d_VertexNX( lua_State *L ){
  bb_int_t __surface = luaL_checknumber( L,1 );
  bb_int_t __index = luaL_checknumber( L,2 );
  lua_pushnumber( L,(bb_float_t)bbVertexNX( __surface,__index ) );
  return 1;
}

static int l_blitz3d_VertexNY( lua_State *L ){
  bb_int_t __surface = luaL_checknumber( L,1 );
  bb_int_t __index = luaL_checknumber( L,2 );
  lua_pushnumber( L,(bb_float_t)bbVertexNY( __surface,__index ) );
  return 1;
}

static int l_blitz3d_VertexNZ( lua_State *L ){
  bb_int_t __surface = luaL_checknumber( L,1 );
  bb_int_t __index = luaL_checknumber( L,2 );
  lua_pushnumber( L,(bb_float_t)bbVertexNZ( __surface,__index ) );
  return 1;
}

static int l_blitz3d_VertexNormal( lua_State *L ){
  bb_int_t __surface = luaL_checknumber( L,1 );
  bb_int_t __index = luaL_checknumber( L,2 );
  bb_float_t __nx = luaL_checknumber( L,3 );
  bb_float_t __ny = luaL_checknumber( L,4 );
  bb_float_t __nz = luaL_checknumber( L,5 );
  bbVertexNormal( __surface,__index,__nx,__ny,__nz );
  return 0;
}

static int l_blitz3d_VertexRed( lua_State *L ){
  bb_int_t __surface = luaL_checknumber( L,1 );
  bb_int_t __index = luaL_checknumber( L,2 );
  lua_pushnumber( L,(bb_float_t)bbVertexRed( __surface,__index ) );
  return 1;
}

static int l_blitz3d_VertexTexCoords( lua_State *L ){
  bb_int_t __surface = luaL_checknumber( L,1 );
  bb_int_t __index = luaL_checknumber( L,2 );
  bb_float_t __u = luaL_checknumber( L,3 );
  bb_float_t __v = luaL_checknumber( L,4 );
  bb_float_t __w;
  if( lua_gettop( L ) > 4 ){
    __w = luaL_checknumber( L,5 );
  }else{
   __w = 1;
  }
  bb_int_t __coord_set;
  if( lua_gettop( L ) > 5 ){
    __coord_set = luaL_checknumber( L,6 );
  }else{
   __coord_set = 0;
  }
  bbVertexTexCoords( __surface,__index,__u,__v,__w,__coord_set );
  return 0;
}

static int l_blitz3d_VertexU( lua_State *L ){
  bb_int_t __surface = luaL_checknumber( L,1 );
  bb_int_t __index = luaL_checknumber( L,2 );
  bb_int_t __coord_set;
  if( lua_gettop( L ) > 2 ){
    __coord_set = luaL_checknumber( L,3 );
  }else{
   __coord_set = 0;
  }
  lua_pushnumber( L,(bb_float_t)bbVertexU( __surface,__index,__coord_set ) );
  return 1;
}

static int l_blitz3d_VertexV( lua_State *L ){
  bb_int_t __surface = luaL_checknumber( L,1 );
  bb_int_t __index = luaL_checknumber( L,2 );
  bb_int_t __coord_set;
  if( lua_gettop( L ) > 2 ){
    __coord_set = luaL_checknumber( L,3 );
  }else{
   __coord_set = 0;
  }
  lua_pushnumber( L,(bb_float_t)bbVertexV( __surface,__index,__coord_set ) );
  return 1;
}

static int l_blitz3d_VertexW( lua_State *L ){
  bb_int_t __surface = luaL_checknumber( L,1 );
  bb_int_t __index = luaL_checknumber( L,2 );
  bb_int_t __coord_set;
  if( lua_gettop( L ) > 2 ){
    __coord_set = luaL_checknumber( L,3 );
  }else{
   __coord_set = 0;
  }
  lua_pushnumber( L,(bb_float_t)bbVertexW( __surface,__index,__coord_set ) );
  return 1;
}

static int l_blitz3d_VertexX( lua_State *L ){
  bb_int_t __surface = luaL_checknumber( L,1 );
  bb_int_t __index = luaL_checknumber( L,2 );
  lua_pushnumber( L,(bb_float_t)bbVertexX( __surface,__index ) );
  return 1;
}

static int l_blitz3d_VertexY( lua_State *L ){
  bb_int_t __surface = luaL_checknumber( L,1 );
  bb_int_t __index = luaL_checknumber( L,2 );
  lua_pushnumber( L,(bb_float_t)bbVertexY( __surface,__index ) );
  return 1;
}

static int l_blitz3d_VertexZ( lua_State *L ){
  bb_int_t __surface = luaL_checknumber( L,1 );
  bb_int_t __index = luaL_checknumber( L,2 );
  lua_pushnumber( L,(bb_float_t)bbVertexZ( __surface,__index ) );
  return 1;
}

static int l_blitz3d_WBuffer( lua_State *L ){
  bb_int_t __enable = luaL_checknumber( L,1 );
  bbWBuffer( __enable );
  return 0;
}

static int l_blitz3d_WireFrame( lua_State *L ){
  bb_int_t __enable = luaL_checknumber( L,1 );
  bbWireFrame( __enable );
  return 0;
}

#endif
