// AUTOGENERATED. DO NOT EDIT.
// RUN `ruby bindings/luajit/generate.rb` TO UPDATE.

#include <bb/blitz/commands.h>

#if defined(BB_WIN32) || defined(BB_WIN64) || defined(BB_MINGW32) || defined(BB_MACOS) || defined(BB_LINUX) || defined(BB_IOS) || defined(BB_ANDROID) || defined(BB_EMSCRIPTEN)
#define BB_BLITZ_ENABLED

static int l_blitz_AppTitle( lua_State *L ){
  BBStr * __title = _bbStrConst( luaL_checkstring( L,1 ) );
  BBStr * __close_prompt;
  if( lua_gettop( L ) > 1 ){
    __close_prompt = _bbStrConst( luaL_checkstring( L,2 ) );
  }else{
   __close_prompt = "";
  }
  bbAppTitle( __title,__close_prompt );
  return 0;
}

static int l_blitz_CommandLine( lua_State *L ){
  lua_pushstring( L,bbCommandLine(  ) );
  return 1;
}

static int l_blitz_DebugLog( lua_State *L ){
  BBStr * __text = _bbStrConst( luaL_checkstring( L,1 ) );
  bbDebugLog( __text );
  return 0;
}

static int l_blitz_End( lua_State *L ){
  bbEnd(  );
  return 0;
}

static int l_blitz_RuntimeStats( lua_State *L ){
  bbRuntimeStats(  );
  return 0;
}

static int l_blitz_Stop( lua_State *L ){
  bbStop(  );
  return 0;
}

#endif
