// AUTOGENERATED. DO NOT EDIT.
// RUN `ruby bindings/luajit/generate.rb` TO UPDATE.

#include <bb/blitz2d/commands.h>

#if defined(BB_WIN32) || defined(BB_WIN64) || defined(BB_MINGW32) || defined(BB_MACOS) || defined(BB_LINUX) || defined(BB_IOS) || defined(BB_ANDROID) || defined(BB_EMSCRIPTEN)
#define BB_BLITZ2D_ENABLED

static int l_blitz2d_CloseMovie( lua_State *L ){
  bb_int_t __movie = luaL_checknumber( L,1 );
  bbCloseMovie( __movie );
  return 0;
}

static int l_blitz2d_Cls( lua_State *L ){
  bbCls(  );
  return 0;
}

static int l_blitz2d_ClsColor( lua_State *L ){
  bb_int_t __red = luaL_checknumber( L,1 );
  bb_int_t __green = luaL_checknumber( L,2 );
  bb_int_t __blue = luaL_checknumber( L,3 );
  bbClsColor( __red,__green,__blue );
  return 0;
}

static int l_blitz2d_Color( lua_State *L ){
  bb_int_t __red = luaL_checknumber( L,1 );
  bb_int_t __green = luaL_checknumber( L,2 );
  bb_int_t __blue = luaL_checknumber( L,3 );
  bbColor( __red,__green,__blue );
  return 0;
}

static int l_blitz2d_ColorBlue( lua_State *L ){
  lua_pushnumber( L,(bb_int_t)bbColorBlue(  ) );
  return 1;
}

static int l_blitz2d_ColorGreen( lua_State *L ){
  lua_pushnumber( L,(bb_int_t)bbColorGreen(  ) );
  return 1;
}

static int l_blitz2d_ColorRed( lua_State *L ){
  lua_pushnumber( L,(bb_int_t)bbColorRed(  ) );
  return 1;
}

static int l_blitz2d_DrawMovie( lua_State *L ){
  bb_int_t __movie = luaL_checknumber( L,1 );
  bb_int_t __x;
  if( lua_gettop( L ) > 1 ){
    __x = luaL_checknumber( L,2 );
  }else{
   __x = 0;
  }
  bb_int_t __y;
  if( lua_gettop( L ) > 2 ){
    __y = luaL_checknumber( L,3 );
  }else{
   __y = 0;
  }
  bb_int_t __w;
  if( lua_gettop( L ) > 3 ){
    __w = luaL_checknumber( L,4 );
  }else{
   __w = -1;
  }
  bb_int_t __h;
  if( lua_gettop( L ) > 4 ){
    __h = luaL_checknumber( L,5 );
  }else{
   __h = -1;
  }
  lua_pushnumber( L,(bb_int_t)bbDrawMovie( __movie,__x,__y,__w,__h ) );
  return 1;
}

static int l_blitz2d_FontHeight( lua_State *L ){
  lua_pushnumber( L,(bb_int_t)bbFontHeight(  ) );
  return 1;
}

static int l_blitz2d_FontWidth( lua_State *L ){
  lua_pushnumber( L,(bb_int_t)bbFontWidth(  ) );
  return 1;
}

static int l_blitz2d_FreeFont( lua_State *L ){
  bb_int_t __font = luaL_checknumber( L,1 );
  bbFreeFont( __font );
  return 0;
}

static int l_blitz2d_GetColor( lua_State *L ){
  bb_int_t __x = luaL_checknumber( L,1 );
  bb_int_t __y = luaL_checknumber( L,2 );
  bbGetColor( __x,__y );
  return 0;
}

static int l_blitz2d_Line( lua_State *L ){
  bb_int_t __x1 = luaL_checknumber( L,1 );
  bb_int_t __y1 = luaL_checknumber( L,2 );
  bb_int_t __x2 = luaL_checknumber( L,3 );
  bb_int_t __y2 = luaL_checknumber( L,4 );
  bbLine( __x1,__y1,__x2,__y2 );
  return 0;
}

static int l_blitz2d_LoadFont( lua_State *L ){
  BBStr * __fontname = _bbStrConst( luaL_checkstring( L,1 ) );
  bb_int_t __height;
  if( lua_gettop( L ) > 1 ){
    __height = luaL_checknumber( L,2 );
  }else{
   __height = 12;
  }
  bb_int_t __bold;
  if( lua_gettop( L ) > 2 ){
    __bold = luaL_checknumber( L,3 );
  }else{
   __bold = 0;
  }
  bb_int_t __italic;
  if( lua_gettop( L ) > 3 ){
    __italic = luaL_checknumber( L,4 );
  }else{
   __italic = 0;
  }
  bb_int_t __underline;
  if( lua_gettop( L ) > 4 ){
    __underline = luaL_checknumber( L,5 );
  }else{
   __underline = 0;
  }
  lua_pushnumber( L,(bb_int_t)bbLoadFont( __fontname,__height,__bold,__italic,__underline ) );
  return 1;
}

static int l_blitz2d_MovieHeight( lua_State *L ){
  bb_int_t __movie = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)bbMovieHeight( __movie ) );
  return 1;
}

static int l_blitz2d_MoviePlaying( lua_State *L ){
  bb_int_t __movie = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)bbMoviePlaying( __movie ) );
  return 1;
}

static int l_blitz2d_MovieWidth( lua_State *L ){
  bb_int_t __movie = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)bbMovieWidth( __movie ) );
  return 1;
}

static int l_blitz2d_OpenMovie( lua_State *L ){
  BBStr * __file = _bbStrConst( luaL_checkstring( L,1 ) );
  lua_pushnumber( L,(bb_int_t)bbOpenMovie( __file ) );
  return 1;
}

static int l_blitz2d_Origin( lua_State *L ){
  bb_int_t __x = luaL_checknumber( L,1 );
  bb_int_t __y = luaL_checknumber( L,2 );
  bbOrigin( __x,__y );
  return 0;
}

static int l_blitz2d_Oval( lua_State *L ){
  bb_int_t __x = luaL_checknumber( L,1 );
  bb_int_t __y = luaL_checknumber( L,2 );
  bb_int_t __width = luaL_checknumber( L,3 );
  bb_int_t __height = luaL_checknumber( L,4 );
  bb_int_t __solid;
  if( lua_gettop( L ) > 4 ){
    __solid = luaL_checknumber( L,5 );
  }else{
   __solid = 1;
  }
  bbOval( __x,__y,__width,__height,__solid );
  return 0;
}

static int l_blitz2d_Plot( lua_State *L ){
  bb_int_t __x = luaL_checknumber( L,1 );
  bb_int_t __y = luaL_checknumber( L,2 );
  bbPlot( __x,__y );
  return 0;
}

static int l_blitz2d_Rect( lua_State *L ){
  bb_int_t __x = luaL_checknumber( L,1 );
  bb_int_t __y = luaL_checknumber( L,2 );
  bb_int_t __width = luaL_checknumber( L,3 );
  bb_int_t __height = luaL_checknumber( L,4 );
  bb_int_t __solid;
  if( lua_gettop( L ) > 4 ){
    __solid = luaL_checknumber( L,5 );
  }else{
   __solid = 1;
  }
  bbRect( __x,__y,__width,__height,__solid );
  return 0;
}

static int l_blitz2d_SetFont( lua_State *L ){
  bb_int_t __font = luaL_checknumber( L,1 );
  bbSetFont( __font );
  return 0;
}

static int l_blitz2d_StringHeight( lua_State *L ){
  BBStr * __string = _bbStrConst( luaL_checkstring( L,1 ) );
  lua_pushnumber( L,(bb_int_t)bbStringHeight( __string ) );
  return 1;
}

static int l_blitz2d_StringWidth( lua_State *L ){
  BBStr * __string = _bbStrConst( luaL_checkstring( L,1 ) );
  lua_pushnumber( L,(bb_int_t)bbStringWidth( __string ) );
  return 1;
}

static int l_blitz2d_Text( lua_State *L ){
  bb_int_t __x = luaL_checknumber( L,1 );
  bb_int_t __y = luaL_checknumber( L,2 );
  BBStr * __text = _bbStrConst( luaL_checkstring( L,3 ) );
  bb_int_t __centre_x;
  if( lua_gettop( L ) > 3 ){
    __centre_x = luaL_checknumber( L,4 );
  }else{
   __centre_x = 0;
  }
  bb_int_t __centre_y;
  if( lua_gettop( L ) > 4 ){
    __centre_y = luaL_checknumber( L,5 );
  }else{
   __centre_y = 0;
  }
  bbText( __x,__y,__text,__centre_x,__centre_y );
  return 0;
}

static int l_blitz2d_Viewport( lua_State *L ){
  bb_int_t __x = luaL_checknumber( L,1 );
  bb_int_t __y = luaL_checknumber( L,2 );
  bb_int_t __width = luaL_checknumber( L,3 );
  bb_int_t __height = luaL_checknumber( L,4 );
  bbViewport( __x,__y,__width,__height );
  return 0;
}

#endif
