// AUTOGENERATED. DO NOT EDIT.
// RUN `ruby src/bindings/luajit/generate.rb` TO UPDATE.

#include <bb/filesystem/commands.h>

#if defined(BB_WIN32) || defined(BB_WIN64) || defined(BB_MINGW32) || defined(BB_MACOS) || defined(BB_LINUX) || defined(BB_IOS) || defined(BB_ANDROID) || defined(BB_EMSCRIPTEN)
#define BB_FILESYSTEM_ENABLED

static int l_filesystem_ChangeDir( lua_State *L ){
  BBStr * __dir = _bbStrConst( luaL_checkstring( L,1 ) );
  bbChangeDir( __dir );
  return 0;
}

static int l_filesystem_CloseDir( lua_State *L ){
  bb_int_t __dir = luaL_checknumber( L,1 );
  bbCloseDir( __dir );
  return 0;
}

static int l_filesystem_CloseFile( lua_State *L ){
  bb_int_t __file_stream = luaL_checknumber( L,1 );
  bbCloseFile( __file_stream );
  return 0;
}

static int l_filesystem_CopyFile( lua_State *L ){
  BBStr * __file = _bbStrConst( luaL_checkstring( L,1 ) );
  BBStr * __to = _bbStrConst( luaL_checkstring( L,2 ) );
  bbCopyFile( __file,__to );
  return 0;
}

static int l_filesystem_CreateDir( lua_State *L ){
  BBStr * __dir = _bbStrConst( luaL_checkstring( L,1 ) );
  bbCreateDir( __dir );
  return 0;
}

static int l_filesystem_CurrentDir( lua_State *L ){
  lua_pushstring( L,bbCurrentDir(  ) );
  return 1;
}

static int l_filesystem_DeleteDir( lua_State *L ){
  BBStr * __dir = _bbStrConst( luaL_checkstring( L,1 ) );
  bbDeleteDir( __dir );
  return 0;
}

static int l_filesystem_DeleteFile( lua_State *L ){
  BBStr * __file = _bbStrConst( luaL_checkstring( L,1 ) );
  bbDeleteFile( __file );
  return 0;
}

static int l_filesystem_FilePos( lua_State *L ){
  bb_int_t __file_stream = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)bbFilePos( __file_stream ) );
  return 1;
}

static int l_filesystem_FileSize( lua_State *L ){
  BBStr * __file = _bbStrConst( luaL_checkstring( L,1 ) );
  lua_pushnumber( L,(bb_int_t)bbFileSize( __file ) );
  return 1;
}

static int l_filesystem_FileType( lua_State *L ){
  BBStr * __file = _bbStrConst( luaL_checkstring( L,1 ) );
  lua_pushnumber( L,(bb_int_t)bbFileType( __file ) );
  return 1;
}

static int l_filesystem_NextFile( lua_State *L ){
  bb_int_t __dir = luaL_checknumber( L,1 );
  lua_pushstring( L,bbNextFile( __dir ) );
  return 1;
}

static int l_filesystem_OpenFile( lua_State *L ){
  BBStr * __filename = _bbStrConst( luaL_checkstring( L,1 ) );
  lua_pushnumber( L,(bb_int_t)bbOpenFile( __filename ) );
  return 1;
}

static int l_filesystem_ReadDir( lua_State *L ){
  BBStr * __dirname = _bbStrConst( luaL_checkstring( L,1 ) );
  lua_pushnumber( L,(bb_int_t)bbReadDir( __dirname ) );
  return 1;
}

static int l_filesystem_ReadFile( lua_State *L ){
  BBStr * __filename = _bbStrConst( luaL_checkstring( L,1 ) );
  lua_pushnumber( L,(bb_int_t)bbReadFile( __filename ) );
  return 1;
}

static int l_filesystem_SeekFile( lua_State *L ){
  bb_int_t __file_stream = luaL_checknumber( L,1 );
  bb_int_t __pos = luaL_checknumber( L,2 );
  lua_pushnumber( L,(bb_int_t)bbSeekFile( __file_stream,__pos ) );
  return 1;
}

static int l_filesystem_WriteFile( lua_State *L ){
  BBStr * __filename = _bbStrConst( luaL_checkstring( L,1 ) );
  lua_pushnumber( L,(bb_int_t)bbWriteFile( __filename ) );
  return 1;
}

#endif
