// AUTOGENERATED. DO NOT EDIT.
// RUN `ruby src/bindings/luajit/generate.rb` TO UPDATE.

#include <bb/graphics/commands.h>

#if defined(BB_WIN32) || defined(BB_WIN64) || defined(BB_MINGW32) || defined(BB_MACOS) || defined(BB_LINUX) || defined(BB_IOS) || defined(BB_ANDROID) || defined(BB_EMSCRIPTEN) || defined(BB_NX)
#define BB_GRAPHICS_ENABLED

static int l_graphics_AutoMidHandle( lua_State *L ){
  bb_int_t __enable = luaL_checknumber( L,1 );
  bbAutoMidHandle( __enable );
  return 0;
}

static int l_graphics_AvailVidMem( lua_State *L ){
  lua_pushnumber( L,(bb_int_t)bbAvailVidMem(  ) );
  return 1;
}

static int l_graphics_BackBuffer( lua_State *L ){
  lua_pushnumber( L,(bb_int_t)bbBackBuffer(  ) );
  return 1;
}

static int l_graphics_BufferDirty( lua_State *L ){
  bb_int_t __buffer = luaL_checknumber( L,1 );
  bbBufferDirty( __buffer );
  return 0;
}

static int l_graphics_CopyImage( lua_State *L ){
  bb_int_t __image = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)bbCopyImage( __image ) );
  return 1;
}

static int l_graphics_CopyPixel( lua_State *L ){
  bb_int_t __src_x = luaL_checknumber( L,1 );
  bb_int_t __src_y = luaL_checknumber( L,2 );
  bb_int_t __src_buffer = luaL_checknumber( L,3 );
  bb_int_t __dest_x = luaL_checknumber( L,4 );
  bb_int_t __dest_y = luaL_checknumber( L,5 );
  bb_int_t __dest_buffer;
  if( lua_gettop( L ) > 5 ){
    __dest_buffer = luaL_checknumber( L,6 );
  }else{
   __dest_buffer = 0;
  }
  bbCopyPixel( __src_x,__src_y,__src_buffer,__dest_x,__dest_y,__dest_buffer );
  return 0;
}

static int l_graphics_CopyPixelFast( lua_State *L ){
  bb_int_t __src_x = luaL_checknumber( L,1 );
  bb_int_t __src_y = luaL_checknumber( L,2 );
  bb_int_t __src_buffer = luaL_checknumber( L,3 );
  bb_int_t __dest_x = luaL_checknumber( L,4 );
  bb_int_t __dest_y = luaL_checknumber( L,5 );
  bb_int_t __dest_buffer;
  if( lua_gettop( L ) > 5 ){
    __dest_buffer = luaL_checknumber( L,6 );
  }else{
   __dest_buffer = 0;
  }
  bbCopyPixelFast( __src_x,__src_y,__src_buffer,__dest_x,__dest_y,__dest_buffer );
  return 0;
}

static int l_graphics_CopyRect( lua_State *L ){
  bb_int_t __source_x = luaL_checknumber( L,1 );
  bb_int_t __source_y = luaL_checknumber( L,2 );
  bb_int_t __width = luaL_checknumber( L,3 );
  bb_int_t __height = luaL_checknumber( L,4 );
  bb_int_t __dest_x = luaL_checknumber( L,5 );
  bb_int_t __dest_y = luaL_checknumber( L,6 );
  bb_int_t __src_buffer;
  if( lua_gettop( L ) > 6 ){
    __src_buffer = luaL_checknumber( L,7 );
  }else{
   __src_buffer = 0;
  }
  bb_int_t __dest_buffer;
  if( lua_gettop( L ) > 7 ){
    __dest_buffer = luaL_checknumber( L,8 );
  }else{
   __dest_buffer = 0;
  }
  bbCopyRect( __source_x,__source_y,__width,__height,__dest_x,__dest_y,__src_buffer,__dest_buffer );
  return 0;
}

static int l_graphics_CountGfxDrivers( lua_State *L ){
  lua_pushnumber( L,(bb_int_t)bbCountGfxDrivers(  ) );
  return 1;
}

static int l_graphics_CountGfxModes( lua_State *L ){
  lua_pushnumber( L,(bb_int_t)bbCountGfxModes(  ) );
  return 1;
}

static int l_graphics_CountGfxModes3D( lua_State *L ){
  lua_pushnumber( L,(bb_int_t)bbCountGfxModes3D(  ) );
  return 1;
}

static int l_graphics_CreateImage( lua_State *L ){
  bb_int_t __width = luaL_checknumber( L,1 );
  bb_int_t __height = luaL_checknumber( L,2 );
  bb_int_t __frames;
  if( lua_gettop( L ) > 2 ){
    __frames = luaL_checknumber( L,3 );
  }else{
   __frames = 1;
  }
  lua_pushnumber( L,(bb_int_t)bbCreateImage( __width,__height,__frames ) );
  return 1;
}

static int l_graphics_DrawBlock( lua_State *L ){
  bb_int_t __image = luaL_checknumber( L,1 );
  bb_int_t __x = luaL_checknumber( L,2 );
  bb_int_t __y = luaL_checknumber( L,3 );
  bb_int_t __frame;
  if( lua_gettop( L ) > 3 ){
    __frame = luaL_checknumber( L,4 );
  }else{
   __frame = 0;
  }
  bbDrawBlock( __image,__x,__y,__frame );
  return 0;
}

static int l_graphics_DrawBlockRect( lua_State *L ){
  bb_int_t __image = luaL_checknumber( L,1 );
  bb_int_t __x = luaL_checknumber( L,2 );
  bb_int_t __y = luaL_checknumber( L,3 );
  bb_int_t __rect_x = luaL_checknumber( L,4 );
  bb_int_t __rect_y = luaL_checknumber( L,5 );
  bb_int_t __rect_width = luaL_checknumber( L,6 );
  bb_int_t __rect_height = luaL_checknumber( L,7 );
  bb_int_t __frame;
  if( lua_gettop( L ) > 7 ){
    __frame = luaL_checknumber( L,8 );
  }else{
   __frame = 0;
  }
  bbDrawBlockRect( __image,__x,__y,__rect_x,__rect_y,__rect_width,__rect_height,__frame );
  return 0;
}

static int l_graphics_DrawImage( lua_State *L ){
  bb_int_t __image = luaL_checknumber( L,1 );
  bb_int_t __x = luaL_checknumber( L,2 );
  bb_int_t __y = luaL_checknumber( L,3 );
  bb_int_t __frame;
  if( lua_gettop( L ) > 3 ){
    __frame = luaL_checknumber( L,4 );
  }else{
   __frame = 0;
  }
  bbDrawImage( __image,__x,__y,__frame );
  return 0;
}

static int l_graphics_DrawImageRect( lua_State *L ){
  bb_int_t __image = luaL_checknumber( L,1 );
  bb_int_t __x = luaL_checknumber( L,2 );
  bb_int_t __y = luaL_checknumber( L,3 );
  bb_int_t __rect_x = luaL_checknumber( L,4 );
  bb_int_t __rect_y = luaL_checknumber( L,5 );
  bb_int_t __rect_width = luaL_checknumber( L,6 );
  bb_int_t __rect_height = luaL_checknumber( L,7 );
  bb_int_t __frame;
  if( lua_gettop( L ) > 7 ){
    __frame = luaL_checknumber( L,8 );
  }else{
   __frame = 0;
  }
  bbDrawImageRect( __image,__x,__y,__rect_x,__rect_y,__rect_width,__rect_height,__frame );
  return 0;
}

static int l_graphics_EndGraphics( lua_State *L ){
  bbEndGraphics(  );
  return 0;
}

static int l_graphics_Flip( lua_State *L ){
  bb_int_t __vwait;
  if( lua_gettop( L ) > 0 ){
    __vwait = luaL_checknumber( L,1 );
  }else{
   __vwait = 1;
  }
  bbFlip( __vwait );
  return 0;
}

static int l_graphics_FreeImage( lua_State *L ){
  bb_int_t __image = luaL_checknumber( L,1 );
  bbFreeImage( __image );
  return 0;
}

static int l_graphics_FrontBuffer( lua_State *L ){
  lua_pushnumber( L,(bb_int_t)bbFrontBuffer(  ) );
  return 1;
}

static int l_graphics_GammaBlue( lua_State *L ){
  bb_int_t __blue = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_float_t)bbGammaBlue( __blue ) );
  return 1;
}

static int l_graphics_GammaGreen( lua_State *L ){
  bb_int_t __green = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_float_t)bbGammaGreen( __green ) );
  return 1;
}

static int l_graphics_GammaRed( lua_State *L ){
  bb_int_t __red = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_float_t)bbGammaRed( __red ) );
  return 1;
}

static int l_graphics_GfxDriver3D( lua_State *L ){
  bb_int_t __driver = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)bbGfxDriver3D( __driver ) );
  return 1;
}

static int l_graphics_GfxDriverName( lua_State *L ){
  bb_int_t __driver = luaL_checknumber( L,1 );
  lua_pushstring( L,bbGfxDriverName( __driver ) );
  return 1;
}

static int l_graphics_GfxMode3D( lua_State *L ){
  bb_int_t __mode = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)bbGfxMode3D( __mode ) );
  return 1;
}

static int l_graphics_GfxMode3DExists( lua_State *L ){
  bb_int_t __width = luaL_checknumber( L,1 );
  bb_int_t __height = luaL_checknumber( L,2 );
  bb_int_t __depth = luaL_checknumber( L,3 );
  lua_pushnumber( L,(bb_int_t)bbGfxMode3DExists( __width,__height,__depth ) );
  return 1;
}

static int l_graphics_GfxModeDepth( lua_State *L ){
  bb_int_t __mode = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)bbGfxModeDepth( __mode ) );
  return 1;
}

static int l_graphics_GfxModeExists( lua_State *L ){
  bb_int_t __width = luaL_checknumber( L,1 );
  bb_int_t __height = luaL_checknumber( L,2 );
  bb_int_t __depth = luaL_checknumber( L,3 );
  lua_pushnumber( L,(bb_int_t)bbGfxModeExists( __width,__height,__depth ) );
  return 1;
}

static int l_graphics_GfxModeHeight( lua_State *L ){
  bb_int_t __mode = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)bbGfxModeHeight( __mode ) );
  return 1;
}

static int l_graphics_GfxModeWidth( lua_State *L ){
  bb_int_t __mode = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)bbGfxModeWidth( __mode ) );
  return 1;
}

static int l_graphics_GrabImage( lua_State *L ){
  bb_int_t __image = luaL_checknumber( L,1 );
  bb_int_t __x = luaL_checknumber( L,2 );
  bb_int_t __y = luaL_checknumber( L,3 );
  bb_int_t __frame;
  if( lua_gettop( L ) > 3 ){
    __frame = luaL_checknumber( L,4 );
  }else{
   __frame = 0;
  }
  bbGrabImage( __image,__x,__y,__frame );
  return 0;
}

static int l_graphics_Graphics( lua_State *L ){
  bb_int_t __width = luaL_checknumber( L,1 );
  bb_int_t __height = luaL_checknumber( L,2 );
  bb_int_t __depth;
  if( lua_gettop( L ) > 2 ){
    __depth = luaL_checknumber( L,3 );
  }else{
   __depth = 0;
  }
  bb_int_t __mode;
  if( lua_gettop( L ) > 3 ){
    __mode = luaL_checknumber( L,4 );
  }else{
   __mode = 0;
  }
  bbGraphics( __width,__height,__depth,__mode );
  return 0;
}

static int l_graphics_Graphics3D( lua_State *L ){
  bb_int_t __width = luaL_checknumber( L,1 );
  bb_int_t __height = luaL_checknumber( L,2 );
  bb_int_t __depth;
  if( lua_gettop( L ) > 2 ){
    __depth = luaL_checknumber( L,3 );
  }else{
   __depth = 0;
  }
  bb_int_t __mode;
  if( lua_gettop( L ) > 3 ){
    __mode = luaL_checknumber( L,4 );
  }else{
   __mode = 0;
  }
  bbGraphics3D( __width,__height,__depth,__mode );
  return 0;
}

static int l_graphics_GraphicsBuffer( lua_State *L ){
  lua_pushnumber( L,(bb_int_t)bbGraphicsBuffer(  ) );
  return 1;
}

static int l_graphics_GraphicsDepth( lua_State *L ){
  lua_pushnumber( L,(bb_int_t)bbGraphicsDepth(  ) );
  return 1;
}

static int l_graphics_GraphicsHeight( lua_State *L ){
  lua_pushnumber( L,(bb_int_t)bbGraphicsHeight(  ) );
  return 1;
}

static int l_graphics_GraphicsLost( lua_State *L ){
  lua_pushnumber( L,(bb_int_t)bbGraphicsLost(  ) );
  return 1;
}

static int l_graphics_GraphicsOpen( lua_State *L ){
  lua_pushnumber( L,(bb_int_t)bbGraphicsOpen(  ) );
  return 1;
}

static int l_graphics_GraphicsWidth( lua_State *L ){
  lua_pushnumber( L,(bb_int_t)bbGraphicsWidth(  ) );
  return 1;
}

static int l_graphics_HandleImage( lua_State *L ){
  bb_int_t __image = luaL_checknumber( L,1 );
  bb_int_t __x = luaL_checknumber( L,2 );
  bb_int_t __y = luaL_checknumber( L,3 );
  bbHandleImage( __image,__x,__y );
  return 0;
}

static int l_graphics_ImageBuffer( lua_State *L ){
  bb_int_t __image = luaL_checknumber( L,1 );
  bb_int_t __frame;
  if( lua_gettop( L ) > 1 ){
    __frame = luaL_checknumber( L,2 );
  }else{
   __frame = 0;
  }
  lua_pushnumber( L,(bb_int_t)bbImageBuffer( __image,__frame ) );
  return 1;
}

static int l_graphics_ImageHeight( lua_State *L ){
  bb_int_t __image = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)bbImageHeight( __image ) );
  return 1;
}

static int l_graphics_ImageRectCollide( lua_State *L ){
  bb_int_t __image = luaL_checknumber( L,1 );
  bb_int_t __x = luaL_checknumber( L,2 );
  bb_int_t __y = luaL_checknumber( L,3 );
  bb_int_t __frame = luaL_checknumber( L,4 );
  bb_int_t __rect_x = luaL_checknumber( L,5 );
  bb_int_t __rect_y = luaL_checknumber( L,6 );
  bb_int_t __rect_width = luaL_checknumber( L,7 );
  bb_int_t __rect_height = luaL_checknumber( L,8 );
  lua_pushnumber( L,(bb_int_t)bbImageRectCollide( __image,__x,__y,__frame,__rect_x,__rect_y,__rect_width,__rect_height ) );
  return 1;
}

static int l_graphics_ImageRectOverlap( lua_State *L ){
  bb_int_t __image = luaL_checknumber( L,1 );
  bb_int_t __x = luaL_checknumber( L,2 );
  bb_int_t __y = luaL_checknumber( L,3 );
  bb_int_t __rect_x = luaL_checknumber( L,4 );
  bb_int_t __rect_y = luaL_checknumber( L,5 );
  bb_int_t __rect_width = luaL_checknumber( L,6 );
  bb_int_t __rect_height = luaL_checknumber( L,7 );
  lua_pushnumber( L,(bb_int_t)bbImageRectOverlap( __image,__x,__y,__rect_x,__rect_y,__rect_width,__rect_height ) );
  return 1;
}

static int l_graphics_ImageWidth( lua_State *L ){
  bb_int_t __image = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)bbImageWidth( __image ) );
  return 1;
}

static int l_graphics_ImageXHandle( lua_State *L ){
  bb_int_t __image = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)bbImageXHandle( __image ) );
  return 1;
}

static int l_graphics_ImageYHandle( lua_State *L ){
  bb_int_t __image = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)bbImageYHandle( __image ) );
  return 1;
}

static int l_graphics_ImagesCollide( lua_State *L ){
  bb_int_t __image1 = luaL_checknumber( L,1 );
  bb_int_t __x1 = luaL_checknumber( L,2 );
  bb_int_t __y1 = luaL_checknumber( L,3 );
  bb_int_t __frame1 = luaL_checknumber( L,4 );
  bb_int_t __image2 = luaL_checknumber( L,5 );
  bb_int_t __x2 = luaL_checknumber( L,6 );
  bb_int_t __y2 = luaL_checknumber( L,7 );
  bb_int_t __frame2 = luaL_checknumber( L,8 );
  lua_pushnumber( L,(bb_int_t)bbImagesCollide( __image1,__x1,__y1,__frame1,__image2,__x2,__y2,__frame2 ) );
  return 1;
}

static int l_graphics_ImagesOverlap( lua_State *L ){
  bb_int_t __image1 = luaL_checknumber( L,1 );
  bb_int_t __x1 = luaL_checknumber( L,2 );
  bb_int_t __y1 = luaL_checknumber( L,3 );
  bb_int_t __image2 = luaL_checknumber( L,4 );
  bb_int_t __x2 = luaL_checknumber( L,5 );
  bb_int_t __y2 = luaL_checknumber( L,6 );
  lua_pushnumber( L,(bb_int_t)bbImagesOverlap( __image1,__x1,__y1,__image2,__x2,__y2 ) );
  return 1;
}

static int l_graphics_Input( lua_State *L ){
  BBStr * __prompt;
  if( lua_gettop( L ) > 0 ){
    __prompt = _bbStrConst( luaL_checkstring( L,1 ) );
  }else{
   __prompt = "";
  }
  lua_pushstring( L,bbInput( __prompt ) );
  return 1;
}

static int l_graphics_LoadAnimImage( lua_State *L ){
  BBStr * __bmpfile = _bbStrConst( luaL_checkstring( L,1 ) );
  bb_int_t __cellwidth = luaL_checknumber( L,2 );
  bb_int_t __cellheight = luaL_checknumber( L,3 );
  bb_int_t __first = luaL_checknumber( L,4 );
  bb_int_t __count = luaL_checknumber( L,5 );
  lua_pushnumber( L,(bb_int_t)bbLoadAnimImage( __bmpfile,__cellwidth,__cellheight,__first,__count ) );
  return 1;
}

static int l_graphics_LoadBuffer( lua_State *L ){
  bb_int_t __buffer = luaL_checknumber( L,1 );
  BBStr * __bmpfile = _bbStrConst( luaL_checkstring( L,2 ) );
  lua_pushnumber( L,(bb_int_t)bbLoadBuffer( __buffer,__bmpfile ) );
  return 1;
}

static int l_graphics_LoadImage( lua_State *L ){
  BBStr * __bmpfile = _bbStrConst( luaL_checkstring( L,1 ) );
  lua_pushnumber( L,(bb_int_t)bbLoadImage( __bmpfile ) );
  return 1;
}

static int l_graphics_Locate( lua_State *L ){
  bb_int_t __x = luaL_checknumber( L,1 );
  bb_int_t __y = luaL_checknumber( L,2 );
  bbLocate( __x,__y );
  return 0;
}

static int l_graphics_LockBuffer( lua_State *L ){
  bb_int_t __buffer;
  if( lua_gettop( L ) > 0 ){
    __buffer = luaL_checknumber( L,1 );
  }else{
   __buffer = 0;
  }
  bbLockBuffer( __buffer );
  return 0;
}

static int l_graphics_MaskImage( lua_State *L ){
  bb_int_t __image = luaL_checknumber( L,1 );
  bb_int_t __red = luaL_checknumber( L,2 );
  bb_int_t __green = luaL_checknumber( L,3 );
  bb_int_t __blue = luaL_checknumber( L,4 );
  bbMaskImage( __image,__red,__green,__blue );
  return 0;
}

static int l_graphics_MidHandle( lua_State *L ){
  bb_int_t __image = luaL_checknumber( L,1 );
  bbMidHandle( __image );
  return 0;
}

static int l_graphics_Print( lua_State *L ){
  BBStr * __string;
  if( lua_gettop( L ) > 0 ){
    __string = _bbStrConst( luaL_checkstring( L,1 ) );
  }else{
   __string = "";
  }
  bbPrint( __string );
  return 0;
}

static int l_graphics_ReadPixel( lua_State *L ){
  bb_int_t __x = luaL_checknumber( L,1 );
  bb_int_t __y = luaL_checknumber( L,2 );
  bb_int_t __buffer;
  if( lua_gettop( L ) > 2 ){
    __buffer = luaL_checknumber( L,3 );
  }else{
   __buffer = 0;
  }
  lua_pushnumber( L,(bb_int_t)bbReadPixel( __x,__y,__buffer ) );
  return 1;
}

static int l_graphics_ReadPixelFast( lua_State *L ){
  bb_int_t __x = luaL_checknumber( L,1 );
  bb_int_t __y = luaL_checknumber( L,2 );
  bb_int_t __buffer;
  if( lua_gettop( L ) > 2 ){
    __buffer = luaL_checknumber( L,3 );
  }else{
   __buffer = 0;
  }
  lua_pushnumber( L,(bb_int_t)bbReadPixelFast( __x,__y,__buffer ) );
  return 1;
}

static int l_graphics_RectsOverlap( lua_State *L ){
  bb_int_t __x1 = luaL_checknumber( L,1 );
  bb_int_t __y1 = luaL_checknumber( L,2 );
  bb_int_t __width1 = luaL_checknumber( L,3 );
  bb_int_t __height1 = luaL_checknumber( L,4 );
  bb_int_t __x2 = luaL_checknumber( L,5 );
  bb_int_t __y2 = luaL_checknumber( L,6 );
  bb_int_t __width2 = luaL_checknumber( L,7 );
  bb_int_t __height2 = luaL_checknumber( L,8 );
  lua_pushnumber( L,(bb_int_t)bbRectsOverlap( __x1,__y1,__width1,__height1,__x2,__y2,__width2,__height2 ) );
  return 1;
}

static int l_graphics_ResizeImage( lua_State *L ){
  bb_int_t __image = luaL_checknumber( L,1 );
  bb_float_t __width = luaL_checknumber( L,2 );
  bb_float_t __height = luaL_checknumber( L,3 );
  bbResizeImage( __image,__width,__height );
  return 0;
}

static int l_graphics_RotateImage( lua_State *L ){
  bb_int_t __image = luaL_checknumber( L,1 );
  bb_float_t __angle = luaL_checknumber( L,2 );
  bbRotateImage( __image,__angle );
  return 0;
}

static int l_graphics_SaveBuffer( lua_State *L ){
  bb_int_t __buffer = luaL_checknumber( L,1 );
  BBStr * __bmpfile = _bbStrConst( luaL_checkstring( L,2 ) );
  lua_pushnumber( L,(bb_int_t)bbSaveBuffer( __buffer,__bmpfile ) );
  return 1;
}

static int l_graphics_SaveImage( lua_State *L ){
  bb_int_t __image = luaL_checknumber( L,1 );
  BBStr * __bmpfile = _bbStrConst( luaL_checkstring( L,2 ) );
  bb_int_t __frame;
  if( lua_gettop( L ) > 2 ){
    __frame = luaL_checknumber( L,3 );
  }else{
   __frame = 0;
  }
  lua_pushnumber( L,(bb_int_t)bbSaveImage( __image,__bmpfile,__frame ) );
  return 1;
}

static int l_graphics_ScaleImage( lua_State *L ){
  bb_int_t __image = luaL_checknumber( L,1 );
  bb_float_t __xscale = luaL_checknumber( L,2 );
  bb_float_t __yscale = luaL_checknumber( L,3 );
  bbScaleImage( __image,__xscale,__yscale );
  return 0;
}

static int l_graphics_ScanLine( lua_State *L ){
  lua_pushnumber( L,(bb_int_t)bbScanLine(  ) );
  return 1;
}

static int l_graphics_SetBuffer( lua_State *L ){
  bb_int_t __buffer = luaL_checknumber( L,1 );
  bbSetBuffer( __buffer );
  return 0;
}

static int l_graphics_SetGamma( lua_State *L ){
  bb_int_t __src_red = luaL_checknumber( L,1 );
  bb_int_t __src_green = luaL_checknumber( L,2 );
  bb_int_t __src_blue = luaL_checknumber( L,3 );
  bb_float_t __dest_red = luaL_checknumber( L,4 );
  bb_float_t __dest_green = luaL_checknumber( L,5 );
  bb_float_t __dest_blue = luaL_checknumber( L,6 );
  bbSetGamma( __src_red,__src_green,__src_blue,__dest_red,__dest_green,__dest_blue );
  return 0;
}

static int l_graphics_SetGfxDriver( lua_State *L ){
  bb_int_t __driver = luaL_checknumber( L,1 );
  bbSetGfxDriver( __driver );
  return 0;
}

static int l_graphics_TFormFilter( lua_State *L ){
  bb_int_t __enable = luaL_checknumber( L,1 );
  bbTFormFilter( __enable );
  return 0;
}

static int l_graphics_TFormImage( lua_State *L ){
  bb_int_t __image = luaL_checknumber( L,1 );
  bb_float_t __a = luaL_checknumber( L,2 );
  bb_float_t __b = luaL_checknumber( L,3 );
  bb_float_t __c = luaL_checknumber( L,4 );
  bb_float_t __d = luaL_checknumber( L,5 );
  bbTFormImage( __image,__a,__b,__c,__d );
  return 0;
}

static int l_graphics_TileBlock( lua_State *L ){
  bb_int_t __image = luaL_checknumber( L,1 );
  bb_int_t __x;
  if( lua_gettop( L ) > 1 ){
    __x = luaL_checknumber( L,2 );
  }else{
   __x = 0;
  }
  bb_int_t __y;
  if( lua_gettop( L ) > 2 ){
    __y = luaL_checknumber( L,3 );
  }else{
   __y = 0;
  }
  bb_int_t __frame;
  if( lua_gettop( L ) > 3 ){
    __frame = luaL_checknumber( L,4 );
  }else{
   __frame = 0;
  }
  bbTileBlock( __image,__x,__y,__frame );
  return 0;
}

static int l_graphics_TileImage( lua_State *L ){
  bb_int_t __image = luaL_checknumber( L,1 );
  bb_int_t __x;
  if( lua_gettop( L ) > 1 ){
    __x = luaL_checknumber( L,2 );
  }else{
   __x = 0;
  }
  bb_int_t __y;
  if( lua_gettop( L ) > 2 ){
    __y = luaL_checknumber( L,3 );
  }else{
   __y = 0;
  }
  bb_int_t __frame;
  if( lua_gettop( L ) > 3 ){
    __frame = luaL_checknumber( L,4 );
  }else{
   __frame = 0;
  }
  bbTileImage( __image,__x,__y,__frame );
  return 0;
}

static int l_graphics_TotalVidMem( lua_State *L ){
  lua_pushnumber( L,(bb_int_t)bbTotalVidMem(  ) );
  return 1;
}

static int l_graphics_UnlockBuffer( lua_State *L ){
  bb_int_t __buffer;
  if( lua_gettop( L ) > 0 ){
    __buffer = luaL_checknumber( L,1 );
  }else{
   __buffer = 0;
  }
  bbUnlockBuffer( __buffer );
  return 0;
}

static int l_graphics_UpdateGamma( lua_State *L ){
  bb_int_t __calibrate;
  if( lua_gettop( L ) > 0 ){
    __calibrate = luaL_checknumber( L,1 );
  }else{
   __calibrate = 0;
  }
  bbUpdateGamma( __calibrate );
  return 0;
}

static int l_graphics_VWait( lua_State *L ){
  bb_int_t __frames;
  if( lua_gettop( L ) > 0 ){
    __frames = luaL_checknumber( L,1 );
  }else{
   __frames = 1;
  }
  bbVWait( __frames );
  return 0;
}

static int l_graphics_Windowed3D( lua_State *L ){
  lua_pushnumber( L,(bb_int_t)bbWindowed3D(  ) );
  return 1;
}

static int l_graphics_Write( lua_State *L ){
  BBStr * __string = _bbStrConst( luaL_checkstring( L,1 ) );
  bbWrite( __string );
  return 0;
}

static int l_graphics_WritePixel( lua_State *L ){
  bb_int_t __x = luaL_checknumber( L,1 );
  bb_int_t __y = luaL_checknumber( L,2 );
  bb_int_t __argb = luaL_checknumber( L,3 );
  bb_int_t __buffer;
  if( lua_gettop( L ) > 3 ){
    __buffer = luaL_checknumber( L,4 );
  }else{
   __buffer = 0;
  }
  bbWritePixel( __x,__y,__argb,__buffer );
  return 0;
}

static int l_graphics_WritePixelFast( lua_State *L ){
  bb_int_t __x = luaL_checknumber( L,1 );
  bb_int_t __y = luaL_checknumber( L,2 );
  bb_int_t __argb = luaL_checknumber( L,3 );
  bb_int_t __buffer;
  if( lua_gettop( L ) > 3 ){
    __buffer = luaL_checknumber( L,4 );
  }else{
   __buffer = 0;
  }
  bbWritePixelFast( __x,__y,__argb,__buffer );
  return 0;
}

#endif
