// AUTOGENERATED. DO NOT EDIT.
// RUN `ruby bindings/luajit/generate.rb` TO UPDATE.

#include <bb/ode/commands.h>

#if defined(BB_WIN32) || defined(BB_WIN64) || defined(BB_MINGW32) || defined(BB_MAC) || defined(BB_LINUX)
#define BB_ODE_ENABLED

static int l_ode_dBodyCreate( lua_State *L ){
  bb_int_t __world = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)_odeBodyCreate( __world ) );
  return 1;
}

static int l_ode_dBodySetAutoDisableFlag( lua_State *L ){
  bb_int_t __body = luaL_checknumber( L,1 );
  bb_int_t __do_auto_disable = luaL_checknumber( L,2 );
  _odeBodySetAutoDisableFlag( __body,__do_auto_disable );
  return 0;
}

static int l_ode_dBodySetPosition( lua_State *L ){
  bb_int_t __body = luaL_checknumber( L,1 );
  bb_float_t __x = luaL_checknumber( L,2 );
  bb_float_t __y = luaL_checknumber( L,3 );
  bb_float_t __z = luaL_checknumber( L,4 );
  _odeBodySetPosition( __body,__x,__y,__z );
  return 0;
}

static int l_ode_dBodySetRotation( lua_State *L ){
  bb_int_t __body = luaL_checknumber( L,1 );
  bb_float_t __pitch = luaL_checknumber( L,2 );
  bb_float_t __yaw = luaL_checknumber( L,3 );
  bb_float_t __roll = luaL_checknumber( L,4 );
  _odeBodySetRotation( __body,__pitch,__yaw,__roll );
  return 0;
}

static int l_ode_dCloseODE( lua_State *L ){
  _odeCloseODE(  );
  return 0;
}

static int l_ode_dContactGetBounce( lua_State *L ){
  lua_pushnumber( L,(bb_float_t)_odeContactGetBounce(  ) );
  return 1;
}

static int l_ode_dContactGetBounceVel( lua_State *L ){
  lua_pushnumber( L,(bb_float_t)_odeContactGetBounceVel(  ) );
  return 1;
}

static int l_ode_dContactGetFDir1( lua_State *L ){
  _odeContactGetFDir1(  );
  return 0;
}

static int l_ode_dContactGetMaxContacts( lua_State *L ){
  lua_pushnumber( L,(bb_int_t)_odeContactGetMaxContacts(  ) );
  return 1;
}

static int l_ode_dContactGetMode( lua_State *L ){
  lua_pushnumber( L,(bb_int_t)_odeContactGetMode(  ) );
  return 1;
}

static int l_ode_dContactGetMotion1( lua_State *L ){
  lua_pushnumber( L,(bb_float_t)_odeContactGetMotion1(  ) );
  return 1;
}

static int l_ode_dContactGetMotion2( lua_State *L ){
  lua_pushnumber( L,(bb_float_t)_odeContactGetMotion2(  ) );
  return 1;
}

static int l_ode_dContactGetMu( lua_State *L ){
  lua_pushnumber( L,(bb_float_t)_odeContactGetMu(  ) );
  return 1;
}

static int l_ode_dContactGetMu2( lua_State *L ){
  lua_pushnumber( L,(bb_float_t)_odeContactGetMu2(  ) );
  return 1;
}

static int l_ode_dContactGetSlip1( lua_State *L ){
  lua_pushnumber( L,(bb_float_t)_odeContactGetSlip1(  ) );
  return 1;
}

static int l_ode_dContactGetSlip2( lua_State *L ){
  lua_pushnumber( L,(bb_float_t)_odeContactGetSlip2(  ) );
  return 1;
}

static int l_ode_dContactGetSoftCFM( lua_State *L ){
  lua_pushnumber( L,(bb_float_t)_odeContactGetSoftCFM(  ) );
  return 1;
}

static int l_ode_dContactGetSoftERP( lua_State *L ){
  lua_pushnumber( L,(bb_float_t)_odeContactGetSoftERP(  ) );
  return 1;
}

static int l_ode_dContactSetBounce( lua_State *L ){
  bb_float_t __bounce = luaL_checknumber( L,1 );
  _odeContactSetBounce( __bounce );
  return 0;
}

static int l_ode_dContactSetBounceVel( lua_State *L ){
  bb_float_t __vel = luaL_checknumber( L,1 );
  _odeContactSetBounceVel( __vel );
  return 0;
}

static int l_ode_dContactSetFDir1( lua_State *L ){
  bb_float_t __fdir1x = luaL_checknumber( L,1 );
  bb_float_t __fdir1y = luaL_checknumber( L,2 );
  bb_float_t __fdir1z = luaL_checknumber( L,3 );
  _odeContactSetFDir1( __fdir1x,__fdir1y,__fdir1z );
  return 0;
}

static int l_ode_dContactSetMaxContacts( lua_State *L ){
  bb_int_t __max = luaL_checknumber( L,1 );
  _odeContactSetMaxContacts( __max );
  return 0;
}

static int l_ode_dContactSetMode( lua_State *L ){
  bb_int_t __mode = luaL_checknumber( L,1 );
  _odeContactSetMode( __mode );
  return 0;
}

static int l_ode_dContactSetMotion1( lua_State *L ){
  bb_float_t __motion = luaL_checknumber( L,1 );
  _odeContactSetMotion1( __motion );
  return 0;
}

static int l_ode_dContactSetMotion2( lua_State *L ){
  bb_float_t __motion = luaL_checknumber( L,1 );
  _odeContactSetMotion2( __motion );
  return 0;
}

static int l_ode_dContactSetMu( lua_State *L ){
  bb_float_t __mu = luaL_checknumber( L,1 );
  _odeContactSetMu( __mu );
  return 0;
}

static int l_ode_dContactSetMu2( lua_State *L ){
  bb_float_t __mu = luaL_checknumber( L,1 );
  _odeContactSetMu2( __mu );
  return 0;
}

static int l_ode_dContactSetSlip1( lua_State *L ){
  bb_float_t __slip = luaL_checknumber( L,1 );
  _odeContactSetSlip1( __slip );
  return 0;
}

static int l_ode_dContactSetSlip2( lua_State *L ){
  bb_float_t __slip = luaL_checknumber( L,1 );
  _odeContactSetSlip2( __slip );
  return 0;
}

static int l_ode_dContactSetSoftCFM( lua_State *L ){
  bb_float_t __cfm = luaL_checknumber( L,1 );
  _odeContactSetSoftCFM( __cfm );
  return 0;
}

static int l_ode_dContactSetSoftERP( lua_State *L ){
  bb_float_t __erp = luaL_checknumber( L,1 );
  _odeContactSetSoftERP( __erp );
  return 0;
}

static int l_ode_dCreateBox( lua_State *L ){
  bb_int_t __space = luaL_checknumber( L,1 );
  bb_float_t __lx = luaL_checknumber( L,2 );
  bb_float_t __ly = luaL_checknumber( L,3 );
  bb_float_t __lz = luaL_checknumber( L,4 );
  lua_pushnumber( L,(bb_int_t)_odeCreateBox( __space,__lx,__ly,__lz ) );
  return 1;
}

static int l_ode_dCreatePlane( lua_State *L ){
  bb_int_t __space = luaL_checknumber( L,1 );
  bb_float_t __a = luaL_checknumber( L,2 );
  bb_float_t __b = luaL_checknumber( L,3 );
  bb_float_t __c = luaL_checknumber( L,4 );
  bb_float_t __d = luaL_checknumber( L,5 );
  lua_pushnumber( L,(bb_int_t)_odeCreatePlane( __space,__a,__b,__c,__d ) );
  return 1;
}

static int l_ode_dDemoTime( lua_State *L ){
  lua_pushnumber( L,(bb_int_t)_odeDemoTime(  ) );
  return 1;
}

static int l_ode_dGeomGetPitch( lua_State *L ){
  bb_int_t __geom = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_float_t)_odeGeomGetPitch( __geom ) );
  return 1;
}

static int l_ode_dGeomGetPositionX( lua_State *L ){
  bb_int_t __geom = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_float_t)_odeGeomGetPositionX( __geom ) );
  return 1;
}

static int l_ode_dGeomGetPositionY( lua_State *L ){
  bb_int_t __geom = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_float_t)_odeGeomGetPositionY( __geom ) );
  return 1;
}

static int l_ode_dGeomGetPositionZ( lua_State *L ){
  bb_int_t __geom = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_float_t)_odeGeomGetPositionZ( __geom ) );
  return 1;
}

static int l_ode_dGeomGetRoll( lua_State *L ){
  bb_int_t __geom = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_float_t)_odeGeomGetRoll( __geom ) );
  return 1;
}

static int l_ode_dGeomGetYaw( lua_State *L ){
  bb_int_t __geom = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_float_t)_odeGeomGetYaw( __geom ) );
  return 1;
}

static int l_ode_dGeomSetBody( lua_State *L ){
  bb_int_t __geom = luaL_checknumber( L,1 );
  bb_int_t __body = luaL_checknumber( L,2 );
  _odeGeomSetBody( __geom,__body );
  return 0;
}

static int l_ode_dGeomSyncEntity( lua_State *L ){
  bb_int_t __geom = luaL_checknumber( L,1 );
  bb_int_t __entity = luaL_checknumber( L,2 );
  _odeGeomSyncEntity( __geom,__entity );
  return 0;
}

static int l_ode_dGetVersion( lua_State *L ){
  lua_pushnumber( L,(bb_float_t)_odeGetVersion(  ) );
  return 1;
}

static int l_ode_dHashSpaceCreate( lua_State *L ){
  bb_int_t __space = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)_odeHashSpaceCreate( __space ) );
  return 1;
}

static int l_ode_dInitODE( lua_State *L ){
  _odeInitODE(  );
  return 0;
}

static int l_ode_dJointGroupCreate( lua_State *L ){
  bb_int_t __max_size = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)_odeJointGroupCreate( __max_size ) );
  return 1;
}

static int l_ode_dJointGroupDestroy( lua_State *L ){
  bb_int_t __group = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)_odeJointGroupDestroy( __group ) );
  return 1;
}

static int l_ode_dJointGroupEmpty( lua_State *L ){
  bb_int_t __group = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)_odeJointGroupEmpty( __group ) );
  return 1;
}

static int l_ode_dRegisterODE( lua_State *L ){
  bb_int_t __key1 = luaL_checknumber( L,1 );
  bb_int_t __key2 = luaL_checknumber( L,2 );
  bb_int_t __key3 = luaL_checknumber( L,3 );
  bb_int_t __key4 = luaL_checknumber( L,4 );
  _odeRegisterODE( __key1,__key2,__key3,__key4 );
  return 0;
}

static int l_ode_dSpaceCollide( lua_State *L ){
  bb_int_t __space = luaL_checknumber( L,1 );
  bb_int_t __world = luaL_checknumber( L,2 );
  bb_int_t __group = luaL_checknumber( L,3 );
  _odeSpaceCollide( __space,__world,__group );
  return 0;
}

static int l_ode_dSpaceDestroy( lua_State *L ){
  bb_int_t __space = luaL_checknumber( L,1 );
  _odeSpaceDestroy( __space );
  return 0;
}

static int l_ode_dWorldCreate( lua_State *L ){
  lua_pushnumber( L,(bb_int_t)_odeWorldCreate(  ) );
  return 1;
}

static int l_ode_dWorldDestroy( lua_State *L ){
  bb_int_t __world = luaL_checknumber( L,1 );
  _odeWorldDestroy( __world );
  return 0;
}

static int l_ode_dWorldQuickStep( lua_State *L ){
  bb_int_t __world = luaL_checknumber( L,1 );
  bb_float_t __stepsize = luaL_checknumber( L,2 );
  lua_pushnumber( L,(bb_int_t)_odeWorldQuickStep( __world,__stepsize ) );
  return 1;
}

static int l_ode_dWorldSetAutoDisableFlag( lua_State *L ){
  bb_int_t __world = luaL_checknumber( L,1 );
  bb_int_t __do_auto_disable = luaL_checknumber( L,2 );
  _odeWorldSetAutoDisableFlag( __world,__do_auto_disable );
  return 0;
}

static int l_ode_dWorldSetGravity( lua_State *L ){
  bb_int_t __world = luaL_checknumber( L,1 );
  bb_float_t __x = luaL_checknumber( L,2 );
  bb_float_t __y = luaL_checknumber( L,3 );
  bb_float_t __z = luaL_checknumber( L,4 );
  _odeWorldSetGravity( __world,__x,__y,__z );
  return 0;
}

#endif
