// AUTOGENERATED. DO NOT EDIT.
// RUN `ruby src/bindings/luajit/generate.rb` TO UPDATE.

#include <bb/stdio/commands.h>

#if defined(BB_WIN32) || defined(BB_WIN64) || defined(BB_MINGW32) || defined(BB_MACOS) || defined(BB_LINUX) || defined(BB_IOS) || defined(BB_ANDROID) || defined(BB_EMSCRIPTEN) || defined(BB_NX)
#define BB_STDIO_ENABLED

static int l_stdio_WriteStderr( lua_State *L ){
  BBStr * __str = _bbStrConst( luaL_checkstring( L,1 ) );
  bbWriteStderr( __str );
  return 0;
}

static int l_stdio_WriteStdout( lua_State *L ){
  BBStr * __str = _bbStrConst( luaL_checkstring( L,1 ) );
  bbWriteStdout( __str );
  return 0;
}

#endif
