// AUTOGENERATED. DO NOT EDIT.
// RUN `ruby src/bindings/luajit/generate.rb` TO UPDATE.

#include <bb/stream/commands.h>

#if defined(BB_WIN32) || defined(BB_WIN64) || defined(BB_MINGW32) || defined(BB_MACOS) || defined(BB_LINUX) || defined(BB_IOS) || defined(BB_ANDROID) || defined(BB_EMSCRIPTEN)
#define BB_STREAM_ENABLED

static int l_stream_CopyStream( lua_State *L ){
  bb_int_t __src_stream = luaL_checknumber( L,1 );
  bb_int_t __dest_stream = luaL_checknumber( L,2 );
  bb_int_t __buffer_size;
  if( lua_gettop( L ) > 2 ){
    __buffer_size = luaL_checknumber( L,3 );
  }else{
   __buffer_size = 16384;
  }
  bbCopyStream( __src_stream,__dest_stream,__buffer_size );
  return 0;
}

static int l_stream_Eof( lua_State *L ){
  bb_int_t __stream = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)bbEof( __stream ) );
  return 1;
}

static int l_stream_ReadAvail( lua_State *L ){
  bb_int_t __stream = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)bbReadAvail( __stream ) );
  return 1;
}

static int l_stream_ReadByte( lua_State *L ){
  bb_int_t __stream = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)bbReadByte( __stream ) );
  return 1;
}

static int l_stream_ReadFloat( lua_State *L ){
  bb_int_t __stream = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_float_t)bbReadFloat( __stream ) );
  return 1;
}

static int l_stream_ReadInt( lua_State *L ){
  bb_int_t __stream = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)bbReadInt( __stream ) );
  return 1;
}

static int l_stream_ReadLine( lua_State *L ){
  bb_int_t __stream = luaL_checknumber( L,1 );
  lua_pushstring( L,bbReadLine( __stream ) );
  return 1;
}

static int l_stream_ReadShort( lua_State *L ){
  bb_int_t __stream = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)bbReadShort( __stream ) );
  return 1;
}

static int l_stream_ReadString( lua_State *L ){
  bb_int_t __stream = luaL_checknumber( L,1 );
  lua_pushstring( L,bbReadString( __stream ) );
  return 1;
}

static int l_stream_WriteByte( lua_State *L ){
  bb_int_t __stream = luaL_checknumber( L,1 );
  bb_int_t __byte = luaL_checknumber( L,2 );
  bbWriteByte( __stream,__byte );
  return 0;
}

static int l_stream_WriteFloat( lua_State *L ){
  bb_int_t __stream = luaL_checknumber( L,1 );
  bb_float_t __float = luaL_checknumber( L,2 );
  bbWriteFloat( __stream,__float );
  return 0;
}

static int l_stream_WriteInt( lua_State *L ){
  bb_int_t __stream = luaL_checknumber( L,1 );
  bb_int_t __int = luaL_checknumber( L,2 );
  bbWriteInt( __stream,__int );
  return 0;
}

static int l_stream_WriteLine( lua_State *L ){
  bb_int_t __stream = luaL_checknumber( L,1 );
  BBStr * __string = _bbStrConst( luaL_checkstring( L,2 ) );
  bbWriteLine( __stream,__string );
  return 0;
}

static int l_stream_WriteShort( lua_State *L ){
  bb_int_t __stream = luaL_checknumber( L,1 );
  bb_int_t __short = luaL_checknumber( L,2 );
  bbWriteShort( __stream,__short );
  return 0;
}

static int l_stream_WriteString( lua_State *L ){
  bb_int_t __stream = luaL_checknumber( L,1 );
  BBStr * __string = _bbStrConst( luaL_checkstring( L,2 ) );
  bbWriteString( __stream,__string );
  return 0;
}

#endif
