// AUTOGENERATED. DO NOT EDIT.
// RUN `ruby src/bindings/luajit/generate.rb` TO UPDATE.

#include <bb/timer/commands.h>

#if defined(BB_WIN32) || defined(BB_WIN64) || defined(BB_MACOS) || defined(BB_LINUX)
#define BB_TIMER_ENABLED

static int l_timer_CreateTimer( lua_State *L ){
  bb_int_t __hertz = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)bbCreateTimer( __hertz ) );
  return 1;
}

static int l_timer_FreeTimer( lua_State *L ){
  bb_int_t __timer = luaL_checknumber( L,1 );
  bbFreeTimer( __timer );
  return 0;
}

static int l_timer_WaitTimer( lua_State *L ){
  bb_int_t __timer = luaL_checknumber( L,1 );
  lua_pushnumber( L,(bb_int_t)bbWaitTimer( __timer ) );
  return 1;
}

#endif
