// AUTOGENERATED. DO NOT EDIT.
// RUN `ruby src/bindings/luajit/generate.rb` TO UPDATE.

#include <bb/unit-test/commands.h>

#if defined(BB_WIN32) || defined(BB_WIN64) || defined(BB_MINGW32) || defined(BB_MACOS) || defined(BB_LINUX) || defined(BB_IOS) || defined(BB_ANDROID) || defined(BB_EMSCRIPTEN)
#define BB_UNIT_TEST_ENABLED

static int l_unit_test_Context( lua_State *L ){
  BBStr * __mesg = _bbStrConst( luaL_checkstring( L,1 ) );
  bbContext( __mesg );
  return 0;
}

static int l_unit_test_Expect( lua_State *L ){
  bb_int_t __condition = luaL_checknumber( L,1 );
  BBStr * __mesg = _bbStrConst( luaL_checkstring( L,2 ) );
  bbExpect( __condition,__mesg );
  return 0;
}

static int l_unit_test_ExpectFloatEq( lua_State *L ){
  bb_float_t __a = luaL_checknumber( L,1 );
  bb_float_t __b = luaL_checknumber( L,2 );
  BBStr * __mesg = _bbStrConst( luaL_checkstring( L,3 ) );
  bbExpectFloatEq( __a,__b,__mesg );
  return 0;
}

static int l_unit_test_ExpectIntEq( lua_State *L ){
  bb_int_t __a = luaL_checknumber( L,1 );
  bb_int_t __b = luaL_checknumber( L,2 );
  BBStr * __mesg = _bbStrConst( luaL_checkstring( L,3 ) );
  bbExpectIntEq( __a,__b,__mesg );
  return 0;
}

#endif
