#ifndef BB_SYSTEM_WINDOWS_COMMANDS_H
#define BB_SYSTEM_WINDOWS_COMMANDS_H

#include <bb/blitz/module.h>
#include <bb/system.windows/system.windows.h>

#ifdef __cplusplus
extern "C" {
#endif

// AUTOGENERATED. DO NOT EDIT.
// RUN `make` TO UPDATE.
bb_int_t BBCALL bbCallDLL( BBStr *dll_name,BBStr *func_name,bbBank *in_bank,bbBank *out_bank );

#ifdef __cplusplus
}
#endif


#endif
