// AUTOGENERATED. DO NOT EDIT.
// RUN `make` TO UPDATE.

#include <bb/blitz/module.h>
#include <bb/system.windows/system.windows.h>

BBMODULE_LINK( system_windows ){
	rtSym( "%CallDLL$dll_name$func_name%in_bank=0%out_bank=0","bbCallDLL",bbCallDLL );
}
