name: CI
on: [push]

jobs:
  macos:
    name: macOS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: brew install ninja
      - run: make ENV=release PLATFORM=macos

  windows:
    name: Windows
    runs-on: windows-2019
    strategy:
      matrix:
        arch:
          - win32
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: .\make.bat release ${{ matrix.arch }}
