name: CI
on: [push]

jobs:
  macos:
    name: macOS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: make ENV=release PLATFORM=macos

  win32:
    name: Windows (32-bit)
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: 'x86'
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: make.bat release win32
