name: CI
on: [push]

jobs:
  windows:
    name: Windows
    runs-on: windows-2019
    strategy:
      matrix:
        arch:
          - win32
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - run: .\make.bat release ${{ matrix.arch }}
      - name: Archive build
        uses: actions/upload-artifact@v2
        with:
          name: blitz3d-ng-win32-v${{ github.run_id }}
          path: _release/

  macos:
    name: macOS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: brew install ninja
      - run: make ENV=release PLATFORM=macos

  linux:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dist:
          - debian-10
          - debian-11
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: ./env.sh ${{ matrix.dist }} make ENV=release PLATFORM=linux

  ios:
    name: iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: make ENV=release PLATFORM=ios

  android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: ./env.sh android make ENV=release PLATFORM=android

  nx:
    name: Switch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: ./env.sh nx make ENV=release PLATFORM=nx

  help:
    name: Help
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bin/blitz3d help --build
