name: CI
on: 
  - push
  - pull_request

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dist:
          - debian-10
          - debian-11
          - ubuntu-20.04
          - ubuntu-22.04
    steps:
      - name: Find module
        run: |
          sudo apt-get install -y apt-file
          sudo apt-file update
          apt-file find snd-dummy

      - name: Install dummy sound card
        run: |
          sudo apt-get install -y linux-sound-base linux-modules-extra-`uname -r`
          sudo modprobe snd-dummy

      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: ./env.sh ${{ matrix.dist }} make ENV=release PLATFORM=linux
      - run: ./env.sh ${{ matrix.dist }} ./test/suite.sh
