name: CI
on: [push]

jobs:
  windows:
    name: Windows
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          # - windows-2019
          - windows-2022
        arch:
          - win32
          - win64
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - if: matrix.arch == 'win64'
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://github.com/blitz3d-ng/env/releases/download/v1/llvm-14.0.4-win64-msvc$env:VisualStudioVersion.zip" -OutFile "llvm.zip"
          Expand-Archive llvm.zip -DestinationPath .\
          Rename-Item llvm-14.0.4 llvm
      - run: .\make.bat release ${{ matrix.arch }}
      - name: Upload toolchain and package
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.arch }}
          path: |
            _release/bin
            _release/*.exe

  # mingw:
  #   name: MinGW
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       arch:
  #         - mingw32
  #         # - mingw64
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         submodules: recursive
  #     - run: ./env.sh mingw make ENV=release PLATFORM=${{ matrix.arch }}
  #     - run: ./env.sh mingw sh ./test/entry.mingw32.sh
  #       continue-on-error: true

  macos:
    name: macOS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          # - macos-10.15
          - macos-11
          - macos-12
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: |
          mkdir _release/toolchains
          wget https://github.com/llvm/llvm-project/releases/download/llvmorg-14.0.4/clang+llvm-14.0.4-x86_64-apple-darwin.tar.xz
          tar xf clang+llvm-14.0.4-x86_64-apple-darwin.tar.xz
          mv clang+llvm-14.0.4-x86_64-apple-darwin llvm
      - run: brew install ninja gcovr
      - run: make ENV=release PLATFORM=macos LLVM_ROOT=$GITHUB_WORKSPACE/llvm
      - run: blitzpath=$GITHUB_WORKSPACE/_release ./test/suite.sh
      - name: Upload toolchain and package
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: |
            _release/bin
            _release/*.app

  linux:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dist:
          - debian-10
          - debian-11
          - ubuntu-20.04
          - ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: ./env.sh ${{ matrix.dist }} make ENV=release PLATFORM=linux
      #- run: ./env.sh ${{ matrix.dist }} ./test/suite.sh

  ios:
    name: iOS
    runs-on: macos-latest
    strategy:
      matrix:
        device:
          - ios
          - ios-sim
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: brew install ninja gcovr
      - run: make ENV=release PLATFORM=${{ matrix.device }}
      - name: Upload toolchain and package
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.device }}
          path: _release/bin

  android:
    name: Android
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - arm64-v8a
          - armeabi-v7a
          - 'x86'
          - 'x86_64'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: ./env.sh android make ENV=release PLATFORM=android ARCH=${{ matrix.arch }}
      - name: Upload toolchain and package
        uses: actions/upload-artifact@v2
        with:
          name: android-${{ matrix.arch }}
          path: _release/bin

  emscripten:
    name: Emscripten (Web)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      # TODO: find out why the first time always fails...
      - run: ./env.sh emscripten make ENV=release PLATFORM=emscripten
        continue-on-error: true
      - run: ./env.sh emscripten make ENV=release PLATFORM=emscripten

  nx:
    name: Switch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: ./env.sh nx make ENV=release PLATFORM=nx

  help:
    name: Help
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bin/blitz3d help --build

  package_windows:
    name: Build Windows Package
    runs-on: ubuntu-latest
    needs:
      - windows
    steps:
      - uses: actions/checkout@v2
      - name: Get tag name
        run: |
          export GITHUB_TAG=$(echo ${GITHUB_REF#refs/tags/})
          export GITHUB_TAG=$(echo ${GITHUB_TAG#refs/heads/})
          echo "GITHUB_TAG=$GITHUB_TAG" >> $GITHUB_ENV

      - name: Download win32
        uses: actions/download-artifact@v3
        with:
          name: win32
          path: _release

      - name: Download win64
        uses: actions/download-artifact@v3
        with:
          name: win64
          path: _release

      - name: Create Windows package
        run: |
          make dist-pkg
          mv package.zip blitz3d-ng-${{ env.GITHUB_TAG }}-windows.zip
          git clean -xfd _release

      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: windows-package
          path: "*.zip"

  package_macos_11:
    name: Build macOS 11 Package
    runs-on: ubuntu-latest
    needs:
      - macos
    steps:
      - uses: actions/checkout@v2
      - name: Get tag name
        run: |
          export GITHUB_TAG=$(echo ${GITHUB_REF#refs/tags/})
          export GITHUB_TAG=$(echo ${GITHUB_TAG#refs/heads/})
          echo "GITHUB_TAG=$GITHUB_TAG" >> $GITHUB_ENV

      - name: Download macos-11
        uses: actions/download-artifact@v3
        with:
          name: macos-11
          path: _release

      - name: Download ios
        uses: actions/download-artifact@v3
        with:
          name: ios
          path: _release

      - name: Download ios-sim
        uses: actions/download-artifact@v3
        with:
          name: ios-sim
          path: _release

      - name: Create macOS 11 package
        run: |
          make dist-pkg
          mv package.zip blitz3d-ng-${{ env.GITHUB_TAG }}-macos11.zip
          git clean -xfd _release

      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: macos-11-package
          path: "*.zip"

  package_macos_12:
    name: Build macOS 12 Package
    runs-on: ubuntu-latest
    needs:
      - macos
    steps:
      - uses: actions/checkout@v2
      - name: Get tag name
        run: |
          export GITHUB_TAG=$(echo ${GITHUB_REF#refs/tags/})
          export GITHUB_TAG=$(echo ${GITHUB_TAG#refs/heads/})
          echo "GITHUB_TAG=$GITHUB_TAG" >> $GITHUB_ENV

      - name: Download macos-12
        uses: actions/download-artifact@v3
        with:
          name: macos-12
          path: _release

      - name: Download ios
        uses: actions/download-artifact@v3
        with:
          name: ios
          path: _release

      - name: Download ios-sim
        uses: actions/download-artifact@v3
        with:
          name: ios-sim
          path: _release

      - name: Create macOS 12 package
        run: |
          make dist-pkg
          mv package.zip blitz3d-ng-${{ env.GITHUB_TAG }}-macos12.zip
          git clean -xfd _release

      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: macos-12-package
          path: "*.zip"

  release:
    name: Build release
    runs-on: ubuntu-latest
    needs:
      - package_windows
      - package_macos_11
      - package_macos_12
    steps:
      - uses: actions/checkout@v2

      - name: Get tag name
        run: |
          export GITHUB_TAG=$(echo ${GITHUB_REF#refs/tags/})
          export GITHUB_TAG=$(echo ${GITHUB_TAG#refs/heads/})
          echo "GITHUB_TAG=$GITHUB_TAG" >> $GITHUB_ENV

      - uses: actions/download-artifact@v3
        with:
          name: windows-package

      - uses: actions/download-artifact@v3
        with:
          name: macos-11-package

      - uses: actions/download-artifact@v3
        with:
          name: macos-12-package

      - name: Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ contains(github.ref, 'beta') }}
          generate_release_notes: false
          files: "*.zip"
