name: CI
on: [push]

jobs:
  windows:
    name: Windows
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          # - windows-2019
          - windows-2022
        arch:
          - win32
          - win64
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - if: matrix.arch == 'win64'
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://github.com/blitz3d-ng/env/releases/download/v1/llvm-14.0.4-win64-msvc$env:VisualStudioVersion.zip" -OutFile "llvm.zip"
          Expand-Archive llvm.zip -DestinationPath .\
          Rename-Item llvm-14.0.4 llvm
      - run: .\make.bat release ${{ matrix.arch }}
      - name: Archive toolchain
        uses: actions/upload-artifact@v2
        with:
          name: toolchain-${{ matrix.arch }}
          path: _release/bin
      - name: Archive package
        uses: actions/upload-artifact@v2
        with:
          name: package-${{ matrix.arch }}
          path: _release

  # mingw:
  #   name: MinGW
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       arch:
  #         - mingw32
  #         # - mingw64
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         submodules: recursive
  #     - run: ./env.sh mingw make ENV=release PLATFORM=${{ matrix.arch }}
  #     - run: ./env.sh mingw sh ./test/entry.mingw32.sh
  #       continue-on-error: true

  macos:
    name: macOS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          # - macos-10.15
          - macos-11
          - macos-12
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: |
          mkdir _release/toolchains
          wget https://github.com/llvm/llvm-project/releases/download/llvmorg-14.0.4/clang+llvm-14.0.4-x86_64-apple-darwin.tar.xz
          tar xf clang+llvm-14.0.4-x86_64-apple-darwin.tar.xz
          mv clang+llvm-14.0.4-x86_64-apple-darwin llvm
      - run: brew install ninja gcovr
      - run: make ENV=release PLATFORM=macos LLVM_ROOT=$GITHUB_WORKSPACE/llvm
      - run: blitzpath=$GITHUB_WORKSPACE/_release ./test/suite.sh
      - name: Archive toolchain
        uses: actions/upload-artifact@v2
        with:
          name: toolchain-${{ matrix.os }}
          path: _release/bin
      - name: Archive package
        uses: actions/upload-artifact@v2
        with:
          name: package-${{ matrix.os }}
          path: _release

  linux:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dist:
          - debian-10
          - debian-11
          - ubuntu-20.04
          - ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: ./env.sh ${{ matrix.dist }} make ENV=release PLATFORM=linux
      #- run: ./env.sh ${{ matrix.dist }} ./test/suite.sh

  ios:
    name: iOS
    runs-on: macos-latest
    strategy:
      matrix:
        device:
          - ios
          - ios-sim
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: brew install ninja gcovr
      - run: make ENV=release PLATFORM=${{ matrix.device }}
      - name: Archive toolchain
        uses: actions/upload-artifact@v2
        with:
          name: toolchain-${{ matrix.device }}
          path: _release/bin

  android:
    name: Android
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - arm64-v8a
          - armeabi-v7a
          - 'x86'
          - 'x86_64'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: ./env.sh android make ENV=release PLATFORM=android ARCH=${{ matrix.arch }}
      - name: Archive toolchain
        uses: actions/upload-artifact@v2
        with:
          name: toolchain-android-${{ matrix.arch }}
          path: _release/bin

  emscripten:
    name: Emscripten (Web)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      # TODO: find out why the first time always fails...
      - run: ./env.sh emscripten make ENV=release PLATFORM=emscripten
        continue-on-error: true
      - run: ./env.sh emscripten make ENV=release PLATFORM=emscripten

  nx:
    name: Switch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: ./env.sh nx make ENV=release PLATFORM=nx

  help:
    name: Help
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bin/blitz3d help --build

  release:
    name: Build release
    runs-on: ubuntu-latest
    needs:
      - windows
      - macos
      - ios
      - android
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Get tag name
        run: |
          export GITHUB_TAG=$(echo ${GITHUB_REF#refs/tags/})
          echo "GITHUB_TAG=$GITHUB_TAG" >> $GITHUB_ENV


      - name: Download win32
        uses: actions/download-artifact@v3
        with:
          name: package-win32
          path: blitz3d-ng-${{ env.GITHUB_TAG }}.zip

      - name: Download macos-11
        uses: actions/download-artifact@v3
        with:
          name: package-macos-11
          path: blitz3d-ng-${{ env.GITHUB_TAG }}-macos11.zip

      - name: Download macos-12
        uses: actions/download-artifact@v3
        with:
          name: package-macos-12
          path: blitz3d-ng-${{ env.GITHUB_TAG }}-macos12.zip

      - name: Download ios
        uses: actions/download-artifact@v3
        with:
          name: toolchain-ios
          path: toolchain-${{ env.GITHUB_TAG }}-ios.zip

      - name: Download ios-sim
        uses: actions/download-artifact@v3
        with:
          name: toolchain-ios-sim
          path: toolchain-${{ env.GITHUB_TAG }}-ios-sim.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: contains(github.ref, 'beta')
          generate_release_notes: false
          files: ${{ env.GITHUB_WORKSPACE }}/*.zip
