name: CI
on: [push]

jobs:
  macos:
    name: macOS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: brew install ninja
      - run: make ENV=release PLATFORM=macos

  windows:
    name: Windows
    runs-on: windows-2019
    strategy:
      matrix:
        arch:
          - win32
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: .\make.bat release ${{ matrix.arch }}
      - run: ruby bin\blitz3d help --build

  linux:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dist:
          - debian10
          - debian11
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: docker build -t b3d:${{ matrix.dist }} - < test/Dockerfile.${{ matrix.dist }}
      - run: docker run --rm -it -w /b3d -v $(pwd):/b3d b3d:${{ matrix.dist }} make ENV=release PLATFORM=linux
