name: CI
on: [push]

jobs:
  windows:
    name: Windows
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-2019
          - windows-2022
        arch:
          - win32
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - run: .\make.bat release ${{ matrix.arch }}
      - run: .\test\entry.win32.bat
      - name: Archive build
        uses: actions/upload-artifact@v2
        with:
          name: blitz3d-ng-win32-v${{ github.run_id }}
          path: _release/

  mingw:
    name: MinGW
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: ./env.sh mingw make ENV=release PLATFORM=mingw32
      # TODO: figure out why this triggers an infinite loop
      # - run: ./env.sh mingw sh ./test/entry.mingw32.sh

  macos:
    name: macOS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-10.15
          - macos-11
          - macos-12
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: brew install ninja
      - run: make ENV=release PLATFORM=macos

  linux:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dist:
          - debian-10
          - debian-11
          - ubuntu-21.04
          - ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: ./env.sh ${{ matrix.dist }} make ENV=release PLATFORM=linux

  ios:
    name: iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: make ENV=release PLATFORM=ios

  android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: ./env.sh android make ENV=release PLATFORM=android

  emscripten:
    name: Emscripten (Web)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      # TODO: find out why the first time always fails...
      - run: ./env.sh emscripten make ENV=release PLATFORM=emscripten
        continue-on-error: true
      - run: ./env.sh emscripten make ENV=release PLATFORM=emscripten

  nx:
    name: Switch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: ./env.sh nx make ENV=release PLATFORM=nx

  help:
    name: Help
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bin/blitz3d help --build
