// AUTOGENERATED. DO NOT EDIT.
// RUN `ruby src/bindings/luajit/generate.rb` TO UPDATE.

#include <luajit.h>
#include <lauxlib.h>

#include "../modules/blitz.c"
#include "../modules/math.c"
#include "../modules/string.c"
#include "../modules/stdio.c"
#include "../modules/stream.c"
#include "../modules/sockets.c"
#include "../modules/enet.c"
#include "../modules/runtime.c"
#include "../modules/system.c"
#include "../modules/bank.c"
#include "../modules/system.windows.c"
#include "../modules/filesystem.c"
#include "../modules/timer.c"
#include "../modules/input.c"
#include "../modules/audio.c"
#include "../modules/blitz2d.c"
#include "../modules/blitz3d.c"
#include "../modules/graphics.c"
#include "../modules/loadlib.c"

